### ISSUE TITLE
[Usage] AttributeError: 'Parameter' object has no attribute 'quant_state'

### ISSUE THREAD

**Issue by gameveloster** [haotian-liu/LLaVA#1028]
### Describe the issue

Issue: Trying to do inference on a LoRA adapter created from finetuning on ` liuhaotian/llava-v1.5-13b` base model.

Due to an error, I have modified `llava/server/cli.py` so that

```py
        with torch.inference_mode():
            output_ids = model.generate(
                input_ids,
```

is changed to

```py
        with torch.inference_mode():
            output_ids = model.generate(
                input_ids=input_ids,
```

But there is now a new error shown below.

Here are my installed pip packages
```
torch                     2.0.1
bitsandbytes              0.41.0
flash-attn                2.3.2
llava                     1.1.3        /home/x/LLaVA
peft                      0.4.0
transformers              4.31.0
```

Command:
```
python -m llava.serve.cli --model-path ./checkpoints/llava-v1.5-13b-lora-test --model-base ./base/llava-v1.5-13b --image-file ./data/testimg.jpg --load-4bit
```

Log: 
```
[2024-01-29 22:03:11,676] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading LLaVA from base model...
Loading checkpoint shards: 100%|██████████████████████████████████| 3/3 [00:14<00:00,  4.73s/it]
Loading additional LLaVA weights...
Loading LoRA weights...
Model is loaded...
USER: Foo bar baz
ASSISTANT: FP4 quantization state not initialized. Please call .cuda() or .to(device) on the LinearFP4 layer first.

Traceback (most recent call last):
  File "/home/x/anaconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/x/anaconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/x/temp/LLaVA/llava/serve/cli.py", line 125, in <module>
    main(args)
  File "/home/x/temp/LLaVA/llava/serve/cli.py", line 94, in main
    output_ids = model.generate(
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/peft/peft_model.py", line 977, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/x/temp/LLaVA/llava/model/language_model/llava_llama.py", line 88, in forward
    return super().forward(
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 824, in forward
    logits = self.lm_head(hidden_states)
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/x/anaconda3/envs/llava/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 249, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
AttributeError: 'Parameter' object has no attribute 'quant_state'

```

It might be `lm_head` raising this error. Strangely there are many `0`s in it
```
torch.Size([32000, 5120])

Parameter containing:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float16)
```

Anyone knows a fix? Thanks

**Comment by HelloWorldLTY** [comment]
Same quesion here.

**Comment by Adrian0999** [comment]
same question here. Anyone has solved?

**Comment by Andcircle** [comment]
Any updates here?

**Comment by PranjalSahu** [comment]
I am also facing the same error. Did anyone solve it ?

**Comment by sgonzalezsilot** [comment]
Same issue here
