### ISSUE TITLE
[Usage] RuntimeError: The size of tensor a (81) must match the size of tensor b (8) at non-singleton dimension 1

### ISSUE THREAD

**Issue by Suhail** [haotian-liu/LLaVA#1054]
### Describe the issue

Issue: RuntimeError: The size of tensor a (81) must match the size of tensor b (8) at non-singleton dimension 1

Command:
```
python -m llava.eval.run_llava --model-path liuhaotian/llava-v1.5-13b --image-file "https://llava-vl.github.io/static/images/view.jpg" --query "What are 3 objects in the image? Separate each object by a comma. Order largest to smallest. Exclude background. Format: object1, object2, object3."
```

Log: 
```
Namespace(model_path='liuhaotian/llava-v1.5-13b', model_base=None, image_file='https://llava-vl.github.io/static/images/view.jpg', query='What are 3 objects in the image? Separate each object by a comma. Order largest to smallest. Exclude background. Format: object1, object2, object3.', conv_mode=None, sep=',', temperature=0.2, top_p=None, num_beams=1, max_new_tokens=512)
llava-v1.5-13b
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:16<00:00,  5.42s/it]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/research/suhail/LLaVA/llava/eval/run_llava.py", line 158, in <module>
    eval_model(args)
  File "/root/research/suhail/LLaVA/llava/eval/run_llava.py", line 129, in eval_model
    n_diff_input_output = (input_ids != output_ids[:, :input_token_len]).sum().item()
RuntimeError: The size of tensor a (81) must match the size of tensor b (8) at non-singleton dimension 1
```

Other info

```

Python 3.10.12

>>> transformers.__version__
'4.36.2'
```

Also curious about this warning: 
```
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
```

**Comment by ninatu** [comment]
I have the same issue  :(

**Comment by TerryYiDa** [comment]
I have the same issue

**Comment by Suhail** [comment]
Sounds like @haotian-liu is aware!

**Comment by haotian-liu** [comment]
Thanks for reporting! Can you check the current main branch fixes it?

**Comment by Suhail** [comment]
Now fixed! Thanks.
