### ISSUE TITLE
[Usage] gradio_web_server is not working after v1.2.1

### ISSUE THREAD

**Issue by luoluoter** [haotian-liu/LLaVA#1067]
### Describe the issue

Issue:

Command:
```
python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload
```

Log: 
```
(llava) zhixin@xxxx-xx-xxxx-machine-02:~/LLaVA$ python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload
2024-02-04 10:44:41 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-02-04 10:44:41 | INFO | gradio_web_server | Models: ['llava-v1.6-34b']
2024-02-04 10:44:41 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-02-04 10:44:42 | ERROR | stderr | /home/zhixin/LLaVA/llava/serve/gradio_web_server.py:353: UserWarning: `layout` parameter is deprecated, and it has no effect
2024-02-04 10:44:42 | ERROR | stderr |   chatbot = gr.Chatbot(
2024-02-04 10:44:42 | ERROR | stderr | Traceback (most recent call last):
2024-02-04 10:44:42 | ERROR | stderr |   File "/home/zhixin/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-02-04 10:44:42 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-02-04 10:44:42 | ERROR | stderr |   File "/home/zhixin/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
2024-02-04 10:44:42 | ERROR | stderr |     exec(code, run_globals)
2024-02-04 10:44:42 | ERROR | stderr |   File "/home/zhixin/LLaVA/llava/serve/gradio_web_server.py", line 473, in <module>
2024-02-04 10:44:42 | ERROR | stderr |     demo = build_demo(args.embed, concurrency_count=args.concurrency_count)
2024-02-04 10:44:42 | ERROR | stderr |   File "/home/zhixin/LLaVA/llava/serve/gradio_web_server.py", line 395, in build_demo
2024-02-04 10:44:42 | ERROR | stderr |     regenerate_btn.click(
2024-02-04 10:44:42 | ERROR | stderr | TypeError: EventListenerMethod.__call__() got an unexpected keyword argument 'concurrency_limit'
```

Screenshots:
None. But message above should be enough.

---

i get the problem at 'main' branch after i 'git pull' , commitID[24fa1d065bbeac8a145a796ab7218c6945a2536e]
So i checkout the old version.
for now, i checkout the branch of v1.2.1, which is not problem

**Comment by haotian-liu** [comment]
Hi, you would need to run `pip install -e .` to upgrade the gradio version.

**Comment by luoluoter** [comment]
oh, you are right. 
It is working after upgrade. 
Sorry for not realizing this.
Thank you for you help.

**Comment by dazhangyu123** [comment]
I have updated packages by running 
```Shell
git pull
pip install -e .
```
but this issue still occurs. How to avoid this issue?
