### ISSUE TITLE
[Usage] 

### ISSUE THREAD

**Issue by shelbywhite** [haotian-liu/LLaVA#1099]
### Describe the issue

Issue:
When running `llava-v1.6-vicuna-13b` or `llava-v1.6-34b` this error happens. This doesn't happen when using the `llava-v1.6-mistral-7b` model. Any idea on what's going on? By the looks of the GPU it isn't running of memory...

<img width="676" alt="Screenshot 2024-02-07 at 2 20 44 PM" src="https://github.com/haotian-liu/LLaVA/assets/252104/b84fbeba-e2a3-4163-837e-5715481c24c4">

Log: 
```
2024-02-07 22:17:41 | INFO | model_worker | Register to controller
2024-02-07 22:17:41 | ERROR | stderr | INFO:     Started server process [13973]
2024-02-07 22:17:41 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-07 22:17:41 | ERROR | stderr | INFO:     Application startup complete.
2024-02-07 22:17:41 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:40000 (Press CTRL+C to quit)
2024-02-07 22:17:56 | INFO | model_worker | Send heart beat. Models: ['llava-v1.6-vicuna-13b']. Semaphore: None. global_counter: 0
2024-02-07 22:18:11 | INFO | model_worker | Send heart beat. Models: ['llava-v1.6-vicuna-13b']. Semaphore: None. global_counter: 0
2024-02-07 22:18:16 | INFO | model_worker | Send heart beat. Models: ['llava-v1.6-vicuna-13b']. Semaphore: Semaphore(value=4, locked=False). global_counter: 1
2024-02-07 22:18:16 | INFO | stdout | INFO:     127.0.0.1:43234 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2024-02-07 22:18:16 | ERROR | stderr | Exception in thread Thread-4 (generate):
2024-02-07 22:18:16 | ERROR | stderr | Traceback (most recent call last):
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-02-07 22:18:16 | ERROR | stderr |     self.run()
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/threading.py", line 953, in run
2024-02-07 22:18:16 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-02-07 22:18:16 | ERROR | stderr |     return func(*args, **kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/LLaVA/llava/model/language_model/llava_llama.py", line 125, in generate
2024-02-07 22:18:16 | ERROR | stderr |     ) = self.prepare_inputs_labels_for_multimodal(
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/LLaVA/llava/model/llava_arch.py", line 157, in prepare_inputs_labels_for_multimodal
2024-02-07 22:18:16 | ERROR | stderr |     image_features = self.encode_images(concat_images)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/LLaVA/llava/model/llava_arch.py", line 141, in encode_images
2024-02-07 22:18:16 | ERROR | stderr |     image_features = self.get_model().get_vision_tower()(images)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-02-07 22:18:16 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-02-07 22:18:16 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2024-02-07 22:18:16 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-02-07 22:18:16 | ERROR | stderr |     return func(*args, **kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/LLaVA/llava/model/multimodal_encoder/clip_encoder.py", line 54, in forward
2024-02-07 22:18:16 | ERROR | stderr |     image_forward_outs = self.vision_tower(images.to(device=self.device, dtype=self.dtype), output_hidden_states=True)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-02-07 22:18:16 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-02-07 22:18:16 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
2024-02-07 22:18:16 | ERROR | stderr |     args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 290, in pre_forward
2024-02-07 22:18:16 | ERROR | stderr |     return send_to_device(args, self.execution_device), send_to_device(
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/utils/operations.py", line 151, in send_to_device
2024-02-07 22:18:16 | ERROR | stderr |     return honor_type(
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/utils/operations.py", line 83, in honor_type
2024-02-07 22:18:16 | ERROR | stderr |     return type(obj)(generator)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/utils/operations.py", line 152, in <genexpr>
2024-02-07 22:18:16 | ERROR | stderr |     tensor, (send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys) for t in tensor)
2024-02-07 22:18:16 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/utils/operations.py", line 167, in send_to_device
2024-02-07 22:18:16 | ERROR | stderr |     return tensor.to(device, non_blocking=non_blocking)
2024-02-07 22:18:16 | ERROR | stderr | NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Comment by haotian-liu** [comment]
This is the OOM issue. For 13B, it requires >30GB memory (you can use --load-4bit to reduce it to 1/4), and for 34B, it requires ~80GB.
