### ISSUE TITLE
Error when finetuning LLaVA-13B

### ISSUE THREAD

**Issue by heaplax** [haotian-liu/LLaVA#110]
### When did you clone our code?

I cloned the code base before 5/1/23, but have pulled the latest code base

### Describe the issue

Issue:
I used LLaVA-13B as the model and extracted projector features from it.  So I didn't do any pre-training.
I don't know if it's the right thing to do.

Command:
```
torchrun --nnodes=1 --nproc_per_node=4 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path /nobackup/users/zfchen/zt/LLaVA/checkpoints/llava-13b-pretrain \
    --data_path /nobackup/users/zfchen/zt/LLaVA/LLaVA-Instruct-150K/llava_instruct_150k.json \
    --image_folder /nobackup/users/zitian/multi_data/COCO/train2017 \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter ./checkpoints/mm_projector/llava-13b-pretrain.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 False \
    --output_dir ./checkpoints \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 5000 \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to wandb
```

Log: 
```
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:49<00:00, 36.62s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:49<00:00, 36.41s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:49<00:00, 36.48s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:50<00:00, 36.71s/it]
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Traceback (most recent call last):
  File "/nobackup/users/zfchen/zt/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/nobackup/users/zfchen/zt/LLaVA/llava/train/train.py", line 535, in train
    model.initialize_vision_tokenizer(mm_use_im_start_end=model_args.mm_use_im_start_end, tokenizer=tokenizer, device=training_args.device,
  File "/nobackup/users/zfchen/zt/LLaVA/llava/model/llava.py", line 316, in initialize_vision_tokenizer
    assert num_new_tokens == 2
AssertionError
```
I found num_new_tokens was 0.

**Comment by haotian-liu** [comment]
Hi @heaplax, thank you for the interest in our work.

I saw the `--model_name_or_path /nobackup/users/zfchen/zt/LLaVA/checkpoints/llava-13b-pretrain` and `--pretrain_mm_mlp_adapter ./checkpoints/mm_projector/llava-13b-pretrain.bin`, when `--pretrain_mm_mlp_adapter` is used, it is expected that `--model_name_or_path` is a base model like Vicuna, instead of LLaVA.  You may also remove `--pretrain_mm_mlp_adapter` if it is already contained in the pretrained checkpoint.

If there is something special in your specific usage, please let me know, thanks.

**Comment by heaplax** [comment]
> Hi @heaplax, thank you for the interest in our work.
> 
> I saw the `--model_name_or_path /nobackup/users/zfchen/zt/LLaVA/checkpoints/llava-13b-pretrain` and `--pretrain_mm_mlp_adapter ./checkpoints/mm_projector/llava-13b-pretrain.bin`, when `--pretrain_mm_mlp_adapter` is used, it is expected that `--model_name_or_path` is a base model like Vicuna, instead of LLaVA. You may also remove `--pretrain_mm_mlp_adapter` if it is already contained in the pretrained checkpoint.
> 
> If there is something special in your specific usage, please let me know, thanks.

It works. Thanks a lot!
