### ISSUE TITLE
[Usage] TypeError: LlavaLlamaForCausalLM.__init__() got an unexpected keyword argument 'attn_implementation'

### ISSUE THREAD

**Issue by ThugJudy** [haotian-liu/LLaVA#1103]
### Describe the issue

Issue:
Getting an error when trying to finetune the LLaVA-v1.6-34b
Command:
```
PASTE THE COMMANDS HERE.
```
#!/bin/bash

deepspeed LLaVA/llava/train/train_mem.py \
    --deepspeed LLaVA/scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-v1.6-34b \
    --version v1 \
    --data_path datasets/bargraph_data.json \
    --image_folder datasets \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.6-34b-task \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb \
    --cache_dir <>
Log: 
```
PASTE THE LOGS HERE.
```
[2024-02-08 11:13:01,934] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-08 11:13:40,223] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0,1: setting --include=localhost:0,1
[2024-02-08 11:13:40,223] [INFO] [runner.py:555:main] cmd = /u/psg4/.conda/envs/llava/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None LLaVA/llava/train/train_mem.py --deepspeed LLaVA/scripts/zero3.json --model_name_or_path liuhaotian/llava-v1.6-34b --version v1 --data_path datasets/bargraph_data.json --image_folder datasets --vision_tower openai/clip-vit-large-patch14-336 --mm_projector_type mlp2x_gelu --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --image_aspect_ratio pad --group_by_modality_length True --bf16 True --output_dir ./checkpoints/llava-v1.6-34b-task --num_train_epochs 1 --per_device_train_batch_size 16 --per_device_eval_batch_size 4 --gradient_accumulation_steps 1 --evaluation_strategy no --save_strategy steps --save_steps 50000 --save_total_limit 1 --learning_rate 2e-5 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 1 --tf32 True --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to wandb --cache_dir /projects/bbpr/psg4
[2024-02-08 11:13:41,852] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-08 11:13:44,216] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2024-02-08 11:13:44,216] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=2, node_rank=0
[2024-02-08 11:13:44,216] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2024-02-08 11:13:44,216] [INFO] [launch.py:163:main] dist_world_size=2
[2024-02-08 11:13:44,216] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2024-02-08 11:13:47,502] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-08 11:13:47,505] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-08 11:13:52,414] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2024-02-08 11:13:52,414] [INFO] [comm.py:594:init_distributed] cdb=None
[2024-02-08 11:13:52,414] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2024-02-08 11:13:52,414] [INFO] [comm.py:594:init_distributed] cdb=None
[2024-02-08 11:13:52,414] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/projects/bbpr/psg4/LLaVA_dataviz/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "/projects/bbpr/psg4/LLaVA_dataviz/LLaVA/llava/train/train.py", line 827, in train
[2024-02-08 11:13:52,907] [INFO] [partition_parameters.py:453:__exit__] finished initializing model with 0.00B parameters
Traceback (most recent call last):
  File "/projects/bbpr/psg4/LLaVA_dataviz/LLaVA/llava/train/train_mem.py", line 4, in <module>
    model = LlavaLlamaForCausalLM.from_pretrained(
      File "/u/psg4/.conda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
train(attn_implementation="flash_attention_2")
  File "/projects/bbpr/psg4/LLaVA_dataviz/LLaVA/llava/train/train.py", line 827, in train
    model = LlavaLlamaForCausalLM.from_pretrained(
  File "/u/psg4/.conda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/u/psg4/.conda/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    model = cls(config, *model_args, **model_kwargs)
  File "/u/psg4/.conda/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
TypeError: LlavaLlamaForCausalLM.__init__() got an unexpected keyword argument 'attn_implementation'
    f(module, *args, **kwargs)
TypeError: LlavaLlamaForCausalLM.__init__() got an unexpected keyword argument 'attn_implementation'
[2024-02-08 11:14:00,233] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1260646
[2024-02-08 11:14:00,247] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1260647
[2024-02-08 11:14:00,247] [ERROR] [launch.py:321:sigkill_handler] ['/u/psg4/.conda/envs/llava/bin/python', '-u', 'LLaVA/llava/train/train_mem.py', '--local_rank=1', '--deepspeed', 'LLaVA/scripts/zero3.json', '--model_name_or_path', 'liuhaotian/llava-v1.6-34b', '--version', 'v1', '--data_path', 'datasets/bargraph_data.json', '--image_folder', 'datasets', '--vision_tower', 'openai/clip-vit-large-patch14-336', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'True', '--bf16', 'True', '--output_dir', './checkpoints/llava-v1.6-34b-task', '--num_train_epochs', '1', '--per_device_train_batch_size', '16', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '50000', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb', '--cache_dir', '/projects/bbpr/psg4'] exits with return code = 1
Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by CrossLee1** [comment]
have you solved this problem?

**Comment by ThugJudy** [comment]
> have you solved this problem?

No I wasn't able to fix the bug, but I deleted and cloned the repo again.

**Comment by zhangboshen** [comment]
same paroblem here.

**Comment by clairej12** [comment]
I am also having this issue.

**Comment by nopanderer** [comment]
I removed the parameter `attn_implementation` in train_mem.py, just call `train()`.

**Comment by LALBJ** [comment]
In my environment, this problem is caused by invoking the llava package in the pip environment. So, I solved this problem by adding the local folder llava to the python environment through the addition of the `PYTHONPATH` parameter when executing bash in the terminal.

Here is an example:
`PYTHONPATH=/path/to/your/llava:$PYTHONPATH bash your_script.sh`

**Comment by pritamqu** [comment]
it should be resolved if you update HF, e.g., 4.38

**Comment by xianghan864** [comment]
> 如果你更新 HF 应该可以解决，例如 4.38

what means HF?

**Comment by pritamqu** [comment]
HuggingFace!

**Comment by howardgriffin** [comment]
same error

**Comment by yhZhai** [comment]
> it should be resolved if you update HF, e.g., 4.38

I believe you were refering to transformers, not HF 😂

**Comment by pritamqu** [comment]
yeah correct!

**Comment by xay2001** [comment]
Upgrade transformers to transformers 4.35.0 using
`pip install transformers==4.35.0
`

**Comment by yonghoonkwon** [comment]
`pip install transformers==4.38.0` works fine

**Comment by Wenchuan-Zhang** [comment]
`pip install transformers==4.36.0` works for me, but versions 4.35 and 4.38 do not.

**Comment by zebin-huang** [comment]
I tried versions 4.35, 4.36, and 4.38; only 4.38 work for me.

`pip install transformers==4.38.0`

**Comment by MassEast** [comment]
All of `transformers==4.35`, `4.36`, and `4.38` require `tokenizer>=0.14`. So I adjusted the cog file with `tokenizers~=0.14`. Still,

- with `4.35`, I get `LlavaLlamaForCausalLM.__init__() got an unexpected keyword argument 'attn_implementation'`
- with `4.36` and `4.38` I get `ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed.`

I tried adding `flash_attn==2.7.3` (which should work for CUDA 11.8) to the cog file, but couldn't get this to build.

> I removed the parameter attn_implementation in train_mem.py, just call train().

This, together with `transformers==4.38` leads me to `TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler' `.

I am thankful for any help!

EDIT: With the latter, `accelerate==0.27.2` helped. But that doesn't change the fact that I couldn't get the flash attention to work.
