### ISSUE TITLE
[Usage] New MPT Training crashed

### ISSUE THREAD

**Issue by tensorboy** [haotian-liu/LLaVA#114]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:

Command:
```
# Visual instruction tuning (1 hour)
torchrun --nnodes=1 --nproc_per_node=8 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path mosaicml/mpt-7b-chat \
    --version v1 \
    --data_path /mnt/bd/data-tns-algo-masp-videocaption/experiment/llava_data/LLaVA-Instruct-150K/llava_instruct_80k.json \
    --image_folder /mnt/bd/data-tns-algo-masp-videocaption/experiment/llava_data/LLaVA-Instruct-150K/train2017 \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter ./checkpoints/mm_projector/llava-lightning-mpt-7b-pretrain.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir ./checkpoints \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 5000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

```

Log: 
```
WARNING:root:Loading data...
WARNING:root:Formatting inputs...Skip in lazy mode
Traceback (most recent call last):
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train.py", line 664, in train
    trainer.train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1451, in _wrap_model
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.
WARNING:root:Loading data...
WARNING:root:Loading data...
WARNING:root:Loading data...
WARNING:root:Loading data...
WARNING:root:Formatting inputs...Skip in lazy mode
Traceback (most recent call last):
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train.py", line 664, in train
    trainer.train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1451, in _wrap_model
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.
WARNING:root:Formatting inputs...Skip in lazy mode
Traceback (most recent call last):
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train.py", line 664, in train
    trainer.train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1451, in _wrap_model
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.
WARNING:root:Formatting inputs...Skip in lazy mode
WARNING:root:Formatting inputs...Skip in lazy mode
Traceback (most recent call last):
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train.py", line 664, in train
    trainer.train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1451, in _wrap_model
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.
Traceback (most recent call last):
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/experiment/LLaVA/llava/train/train.py", line 664, in train
    trainer.train()
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1451, in _wrap_model
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 299585 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 299586 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 299587 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 299589 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 299590 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 299591 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 299592 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 3 (pid: 299588) of binary: /mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/bin/python
Traceback (most recent call last):
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/bd/data-tns-algo-masp-videocaption/environment/anaconda3/envs/llava/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
llava/train/train_mem.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-07_06:51:26
  host      : n214-178-206.byted.org
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 299588)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```
the verision of the trainsfoerms:
transformers==4.28.0.dev0 (installed by: 
```
pip uninstall transformers
pip install git+https://github.com/huggingface/transformers@cae78c46
```
Screenshots:

<img width="998" alt="Screen Shot 2023-05-06 at 3 57 04 PM" src="https://user-images.githubusercontent.com/17189055/236649533-5968f9d4-20cf-429a-bb70-3846126134b2.png">

**Comment by haotian-liu** [comment]
Hi, sorry for the confusion.  There was a mistake in the train lightning command, and it is fixed in https://github.com/haotian-liu/LLaVA/commit/fee35939829370eef8371a553c57c3b3b4bdeed9. 

```
--fsdp_transformer_layer_cls_to_wrap 'MPTBlock'
```

Please change this line and try again. Thanks!

**Comment by tensorboy** [comment]
> fee3593

you always response so fast.
