### ISSUE TITLE
[Usage] failure: pip install flash-attn --no-build-isolation

### ISSUE THREAD

**Issue by yinincanada** [haotian-liu/LLaVA#1140]
### Describe the issue

Issue: pip install flash-atten failure

Command:
```
pip install flash-attn --no-build-isolation
```

Log: 
```
Collecting flash-attn
  Downloading flash_attn-2.5.3.tar.gz (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 20.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      
      
      torch.__version__  = 2.0.1+cu117
      
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qg0blifr/flash-attn_a733b692349f44378614a22ba51e77c1/setup.py", line 114, in <module>
          raise RuntimeError(
      RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Screenshots:
<img width="805" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/149828936/ae7c265c-17cb-4208-9265-356c08c3ebca">

I checked my cuda version by running nvidia-smi,  I am having cuda version 12.2 (> required 11.6)
<img width="515" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/149828936/df911801-5557-40a4-9f31-50ab891f6c89">

when running nvcc -V I am getting below
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by yinincanada** [comment]
I think the cuda version listed by nvidia-smi is a bit misleading, and the actual version of cuda installed should be 10.1 as shown by nvcc -V.

**Comment by copperwiring** [comment]
I had the same issue. Depends on the version of os (e.g. ubuntu), cuda version supported by nvidia might not have compatibility with cudo toolkit. 

Check your nvidia cuda driver using `nvidia-smi` and see if it is compatible for 11.6 and above (that's what flash attention expects). 

If you want to install 11.6, see here: https://forums.developer.nvidia.com/t/how-does-one-install-cuda-11-6-on-ubuntu-22-04/232137/2 or if you have Ubuntu 22, you can even get 11.8,  which you can get from here: https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04
