### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0 

### ISSUE THREAD

**Issue by fan-chao** [haotian-liu/LLaVA#116]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue: RuntimeError: probability tensor contains either inf, nan or element < 0

Command:
```
python -m llava.serve.controller --host 0.0.0.0 --port 10000

python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path weights/LLaVA-13B-v0 --multi-modal

python -m llava.serve.test_message --model-name LLaVA-13B-v0 --controller http://localhost:1000

```

Log: 
```
2023-05-07 15:54:33 | INFO | model_worker | Register to controller
2023-05-07 15:54:33 | ERROR | stderr | INFO:     Started server process [20537]
2023-05-07 15:54:33 | ERROR | stderr | INFO:     Waiting for application startup.
2023-05-07 15:54:33 | ERROR | stderr | INFO:     Application startup complete.
2023-05-07 15:54:33 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:40000 (Press CTRL+C to quit)
2023-05-07 15:54:42 | INFO | stdout | INFO:     127.0.0.1:33944 - "POST /worker_get_status HTTP/1.1" 200 OK
2023-05-07 15:54:42 | INFO | model_worker | Send heart beat. Models: ['LLaVA-13B-v0']. Semaphore: Semaphore(value=4, locked=False). global_counter: 1
2023-05-07 15:54:42 | INFO | stdout | INFO:     127.0.0.1:33960 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-05-07 15:54:43 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-05-07 15:54:43 | ERROR | stderr | Traceback (most recent call last):
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-05-07 15:54:43 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     raise exc
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     raise exc
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     raise e
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     await self.app(scope, receive, send)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-05-07 15:54:43 | ERROR | stderr |     await self.app(scope, receive, send)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
2023-05-07 15:54:43 | ERROR | stderr |     await response(scope, receive, send)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2023-05-07 15:54:43 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
2023-05-07 15:54:43 | ERROR | stderr |     raise exceptions[0]
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2023-05-07 15:54:43 | ERROR | stderr |     await func()
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
2023-05-07 15:54:43 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
2023-05-07 15:54:43 | ERROR | stderr |     yield await anyio.to_thread.run_sync(_next, iterator)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-05-07 15:54:43 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-05-07 15:54:43 | ERROR | stderr |     return await future
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-05-07 15:54:43 | ERROR | stderr |     result = context.run(func, *args)
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/concurrency.py", line 53, in _next
2023-05-07 15:54:43 | ERROR | stderr |     return next(iterator)
2023-05-07 15:54:43 | ERROR | stderr |   File "/data1/fc/LLaVA/llava/serve/model_worker.py", line 306, in generate_stream_gate
2023-05-07 15:54:43 | ERROR | stderr |     for x in self.generate_stream(params):
2023-05-07 15:54:43 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
2023-05-07 15:54:43 | ERROR | stderr |     response = gen.send(None)
2023-05-07 15:54:43 | ERROR | stderr |   File "/data1/fc/LLaVA/llava/serve/model_worker.py", line 272, in generate_stream
2023-05-07 15:54:43 | ERROR | stderr |     token = int(torch.multinomial(probs, num_samples=1))
2023-05-07 15:54:43 | ERROR | stderr | RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
2023-05-07 15:54:48 | INFO | model_worker | Send heart beat. Models: ['LLaVA-13B-v0']. Semaphore: Semaphore(value=4, locked=False). global_counter: 1
```

Screenshots:
![image](https://user-images.githubusercontent.com/10006853/236665486-cd8e924a-48bd-4118-b2ef-5bf404b060e3.png)

**Comment by haotian-liu** [comment]
Hi @fan-chao, thank you for your interest in our work.  If you directly try running [`run_llava.py`](https://github.com/haotian-liu/LLaVA/blob/main/llava/eval/run_llava.py), is it working correctly?  If so, you may skip this `test_message` step and go ahead directly to launching the gradio demo.  We'll fix the issues with `test message` soon.  Thanks!

**Comment by fan-chao** [comment]
Thanks for your suggestion. I found the cause is that I used the wrong base model. It can be fixed by switching to the correct base model.

**Comment by peiyixuan** [comment]
> Thanks for your suggestion. I found the cause is that I used the wrong base model. It can be fixed by switching to the correct base model.

Hi, I wonder what is wrong with your base model. I encountered the same problem.

**Comment by fan-chao** [comment]
> > Thanks for your suggestion. I found the cause is that I used the wrong base model. It can be fixed by switching to the correct base model.
> 
> Hi, I wonder what is wrong with your base model. I encountered the same problem.

The LLaMA model I firtsly used is not huggingface format. So it reported this error. Later, I used this model https://huggingface.co/huggyllama/llama-13b and it worked.

**Comment by kahnchana** [comment]
Have you been getting this with MPT models? I've been running following code and getting the same error. 

```
python -m llava.eval.run_llava \
    --model-name "liuhaotian/LLaVA-Lightning-MPT-7B-preview" \
    --image-file "llava/serve/examples/extreme_ironing.jpg" \
    --query "What is unusual about this image?"
```
