### ISSUE TITLE
[Question] after finetune i run cli.py

### ISSUE THREAD

**Issue by conheaven** [haotian-liu/LLaVA#1215]
### Question

after finetune with finetune_lora.sh, I merge the model with 'python scripts/merge_lora_weights.py \
    --model-path /data1/khw/output_llava/finetune/llava-v1.5-13b-lora \
    --model-base /data1/khw/llava \
    --save-model-path /data1/khw/output_llava/merge_model-lora'
    then i run 
    'python -m llava.serve.cli \
    --model-base /data1/khw/llava \
    --model-path /data1/khw/output_llava/merge_model-lora \
    --image-file /data1/khw/img/1.jpg \'
    it shows 
    "Traceback (most recent call last):
  File "/home/khw/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/khw/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/khw/llava/LLaVA/llava/serve/cli.py", line 126, in <module>
    main(args)
  File "/home/khw/llava/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/home/khw/llava/LLaVA/llava/model/builder.py", line 122, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, **kwargs)
  File "/home/khw/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, LlavaConfig, LlavaMptConfig, LlavaMistralConfig."
thank you in advance

**Comment by sayedmohamedscu** [comment]
try to upgrade transformers

**Comment by conheaven** [comment]
> try to upgrade transformers

my transformers is 4.37.2, should i upgrade it？

**Comment by Namzakku** [comment]
I've managed to merge the model by installing llava 1.1.3 from previous releases and change the transformers_version in config.json in the finetuned model to 4.31.0

**Comment by DemonsAH** [comment]
#1567
