### ISSUE TITLE
[Usage] TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by alvinxjm** [haotian-liu/LLaVA#1218]
### Describe the issue

Issue:
Model Worker is showing this error when i chat with it.
TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'

Log: 

2024-03-04 08:41:32 | ERROR | stderr | Exception in thread Thread-3 (generate):
2024-03-04 08:41:32 | ERROR | stderr | Traceback (most recent call last):
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-03-04 08:41:32 | ERROR | stderr |     self.run()
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/threading.py", line 953, in run
2024-03-04 08:41:32 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-03-04 08:41:32 | ERROR | stderr |     return func(*args, **kwargs)
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/LLaVA/llava/model/language_model/llava_llama.py", line 138, in generate
2024-03-04 08:41:32 | ERROR | stderr |     return super().generate(
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-03-04 08:41:32 | ERROR | stderr |     return func(*args, **kwargs)
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1592, in generate
2024-03-04 08:41:32 | ERROR | stderr |     return self.sample(
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2696, in sample
2024-03-04 08:41:32 | ERROR | stderr |     outputs = self(
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-03-04 08:41:32 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-03-04 08:41:32 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-03-04 08:41:32 | ERROR | stderr |   File "/home/ec2-user/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2024-03-04 08:41:32 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2024-03-04 08:41:32 | ERROR | stderr | TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'

Screenshots:
![image](https://github.com/haotian-liu/LLaVA/assets/80762904/a0c435ce-655a-4465-8681-58a98558a05b)
![image](https://github.com/haotian-liu/LLaVA/assets/80762904/f378b1b6-4606-40b1-b2d5-be455e782075)
![image](https://github.com/haotian-liu/LLaVA/assets/80762904/1ea249d4-b81c-43ed-aa62-1bd58687fb47)

**Comment by londee** [comment]
I encountered the same error while running "eval_mode".

>>> eval_model(args)
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.27s/it]
/root/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/humaodi/code/LLaVA/llava/eval/run_llava.py", line 115, in eval_model
    output_ids = model.generate(
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/humaodi/code/LLaVA/llava/model/language_model/llava_llama.py", line 137, in generate
    return super().generate(
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1544, in generate
    return self.greedy_search(
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2404, in greedy_search
    outputs = self(
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'

**Comment by scp92** [comment]
I encountered the same error too. Any ideas?

**Comment by zfreeman32** [comment]
Got this error as well. Not been able to fix yet. Tracking this Issue.

**Comment by shashwat14** [comment]
I had the same issue. Fixed it by ensuring the transformers version to be same as the one mentioned in pyproject.toml, i.e. transformers==4.37.2

**Comment by FanHengbo** [comment]
> I had the same issue. Fixed it by ensuring the transformers version to be same as the one mentioned in pyproject.toml, i.e. transformers==4.37.2

Problem solved. Thanks!

**Comment by lixiaoxiangzhi** [comment]
> Problem solved. Thanks!

**Comment by aliencaocao** [comment]
this was because transformers 4.38.0 added static cache. So have to use any version below.

**Comment by lixiaoxiangzhi** [comment]
您的来信已收到，祝您每天有个好心情。

**Comment by YFCYFC** [comment]
https://github.com/haotian-liu/LLaVA/issues/1218#issuecomment-1977497811
Thank you so much, my problem was solved via degrading transformers==4.37.2.The transformers package interfaces changes frequently, which makes me so confused that I have to spend too much time to debug the meaningless bugs.

**Comment by RandomInternetPreson** [comment]
> I had the same issue. Fixed it by ensuring the transformers version to be same as the one mentioned in pyproject.toml, i.e. transformers==4.37.2

TY <3

**Comment by wyxscir** [comment]
> I had the same issue. Fixed it by ensuring the transformers version to be same as the one mentioned in pyproject.toml, i.e. transformers==4.37.2

thank you!!!!!!

**Comment by segalinc** [comment]
new models use transformers>4.39 is there a way to actually fix this ?

**Comment by lixiaoxiangzhi** [comment]
您的来信已收到，祝您每天有个好心情。

**Comment by foundwant** [comment]
TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'
my transformers version is 4.37.2，also have this problem.

**Comment by diongzy** [comment]
I still got this error after installing transformers==4.37.2

TypeError: llama_model_forward_4_36() got an unexpected keyword argument 'cache_position'

**Comment by baichuanzhou** [comment]
Hey, adding cache_position=None to the forward method also works. Check [here](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/inference/llava/model/language_model/llava_llama.py#L80C9-L80C23)

**Comment by lixiaoxiangzhi** [comment]
您的来信已收到，祝您每天有个好心情。
