### ISSUE TITLE
While processing image, it reports RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by fan-chao** [haotian-liu/LLaVA#123]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:
I use gradio demo to test conversation. There is no problem when using plain text for conversations. 
But it reports "RuntimeError: GET was unable to find an engine to execute this computation" while processing image. And all subsequent conversations also showed this error. The model_worker must be restarted to solve this problem. The image I use is what the webpage provides "What is unusual about this image?".

Command:
```
python -m llava.serve.controller --host 0.0.0.0 --port 10000

python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path weights/llava-13b-v0 --multi-modal

python -m llava.serve.gradio_web_server --controller http://localhost:10000
```

Log: 
```
2023-05-08 19:28:47 | INFO | model_worker | Register to controller
2023-05-08 19:28:47 | ERROR | stderr | INFO:     Started server process [31603]
2023-05-08 19:28:47 | ERROR | stderr | INFO:     Waiting for application startup.
2023-05-08 19:28:47 | ERROR | stderr | INFO:     Application startup complete.
2023-05-08 19:28:47 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:40000 (Press CTRL+C to quit)
2023-05-08 19:29:02 | INFO | model_worker | Send heart beat. Models: ['llava-13b-v0']. Semaphore: None. global_counter: 0
2023-05-08 19:29:17 | INFO | model_worker | Send heart beat. Models: ['llava-13b-v0']. Semaphore: None. global_counter: 0
2023-05-08 19:29:20 | INFO | model_worker | Send heart beat. Models: ['llava-13b-v0']. Semaphore: Semaphore(value=4, locked=False). global_counter: 1
2023-05-08 19:29:20 | INFO | stdout | INFO:     127.0.0.1:48850 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-05-08 19:29:28 | INFO | model_worker | Send heart beat. Models: ['llava-13b-v0']. Semaphore: Semaphore(value=5, locked=False). global_counter: 1
2023-05-08 19:29:32 | INFO | model_worker | Send heart beat. Models: ['llava-13b-v0']. Semaphore: Semaphore(value=5, locked=False). global_counter: 1
2023-05-08 19:29:47 | INFO | model_worker | Send heart beat. Models: ['llava-13b-v0']. Semaphore: Semaphore(value=5, locked=False). global_counter: 1
2023-05-08 19:29:52 | INFO | model_worker | Send heart beat. Models: ['llava-13b-v0']. Semaphore: Semaphore(value=4, locked=False). global_counter: 2
2023-05-08 19:29:52 | INFO | stdout | INFO:     127.0.0.1:35472 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-05-08 19:29:52 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-05-08 19:29:52 | ERROR | stderr | Traceback (most recent call last):
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-05-08 19:29:52 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     raise exc
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     raise exc
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     raise e
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     await self.app(scope, receive, send)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-05-08 19:29:52 | ERROR | stderr |     await self.app(scope, receive, send)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
2023-05-08 19:29:52 | ERROR | stderr |     await response(scope, receive, send)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2023-05-08 19:29:52 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
2023-05-08 19:29:52 | ERROR | stderr |     raise exceptions[0]
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2023-05-08 19:29:52 | ERROR | stderr |     await func()
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
2023-05-08 19:29:52 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
2023-05-08 19:29:52 | ERROR | stderr |     yield await anyio.to_thread.run_sync(_next, iterator)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-05-08 19:29:52 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-05-08 19:29:52 | ERROR | stderr |     return await future
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-05-08 19:29:52 | ERROR | stderr |     result = context.run(func, *args)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/concurrency.py", line 53, in _next
2023-05-08 19:29:52 | ERROR | stderr |     return next(iterator)
2023-05-08 19:29:52 | ERROR | stderr |   File "/data1/fc/LLaVA/llava/serve/model_worker.py", line 306, in generate_stream_gate
2023-05-08 19:29:52 | ERROR | stderr |     for x in self.generate_stream(params):
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
2023-05-08 19:29:52 | ERROR | stderr |     response = gen.send(None)
2023-05-08 19:29:52 | ERROR | stderr |   File "/data1/fc/LLaVA/llava/serve/model_worker.py", line 251, in generate_stream
2023-05-08 19:29:52 | ERROR | stderr |     out = model(
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-08 19:29:52 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-05-08 19:29:52 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-05-08 19:29:52 | ERROR | stderr |   File "/data1/fc/LLaVA/llava/model/llava.py", line 223, in forward
2023-05-08 19:29:52 | ERROR | stderr |     outputs = self.model(
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-08 19:29:52 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-05-08 19:29:52 | ERROR | stderr |   File "/data1/fc/LLaVA/llava/model/llava.py", line 126, in forward
2023-05-08 19:29:52 | ERROR | stderr |     image_forward_outs = vision_tower(images, output_hidden_states=True)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-08 19:29:52 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 934, in forward
2023-05-08 19:29:52 | ERROR | stderr |     return self.vision_model(
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-08 19:29:52 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 859, in forward
2023-05-08 19:29:52 | ERROR | stderr |     hidden_states = self.embeddings(pixel_values)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-08 19:29:52 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 195, in forward
2023-05-08 19:29:52 | ERROR | stderr |     patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, width, grid, grid]
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-08 19:29:52 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
2023-05-08 19:29:52 | ERROR | stderr |     return self._conv_forward(input, self.weight, self.bias)
2023-05-08 19:29:52 | ERROR | stderr |   File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
2023-05-08 19:29:52 | ERROR | stderr |     return F.conv2d(input, weight, bias, self.stride,
2023-05-08 19:29:52 | ERROR | stderr | RuntimeError: GET was unable to find an engine to execute this computation

```

Screenshots:
![image](https://user-images.githubusercontent.com/10006853/236814943-7049c28f-0be0-4b27-b9e4-a740b6e05e4d.png)

![image](https://user-images.githubusercontent.com/10006853/236815272-3d5264b6-96da-4037-87d8-be102bdafe64.png)

![image](https://user-images.githubusercontent.com/10006853/236815338-9b72751f-65d2-48a9-9020-f15fdc115597.png)

![image](https://user-images.githubusercontent.com/10006853/236815672-d389b855-50e6-4add-bd5c-1a205475210f.png)

![image](https://user-images.githubusercontent.com/10006853/236815770-d567ea54-da08-405f-9a9f-fdadf423580a.png)

**Comment by haotian-liu** [comment]
Hi, there is another user who met a similar issue, which seems to be related to CUDA/PyTorch versions.  He has provided detailed solution on how he solved the issue.  Can you try [this](https://github.com/haotian-liu/LLaVA/issues/102#issuecomment-1537465794)?

Meanwhile, would you please share your CUDA version, GPU type, GCC version, OS version?  Thanks.

**Comment by fan-chao** [comment]
Hi, the detail version info is as below:
CUDA version: 11.0
GPU type: Tesla V100 SXM2
GCC version: 7.5.0
OS version: Ubuntu 18.04

**Comment by fan-chao** [comment]
Thanks for your useful info about downgrading torch version.
It works after downgrading the torch version to 1.13.1 and setting the CUDA version to 11.7. I used the following command to reinstall pytorch.
`
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
`

**Comment by JulioZhao97** [comment]
> Thanks for your useful info about downgrading torch version. It works after downgrading the torch version to 1.13.1 and setting the CUDA version to 11.7. I used the following command to reinstall pytorch. `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`

Hi, can I ask you could you run ```import flash_attn_cuda```

I have the same env as you, but the flash_attn_cuda can not be imported.

**Comment by fan-chao** [comment]
> > Thanks for your useful info about downgrading torch version. It works after downgrading the torch version to 1.13.1 and setting the CUDA version to 11.7. I used the following command to reinstall pytorch. `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`
> 
> Hi, can I ask you could you run `import flash_attn_cuda`
> 
> I have the same env as you, but the flash_attn_cuda can not be imported.

Hi, I only used the demo provided by the author and did not modify any code. Btw, was flash-attn installed successfully? In additional, another user seems to have encountered a problem with flash-attn, and you can also refer to [his solution](https://github.com/haotian-liu/LLaVA/issues/102#issuecomment-1537465794?).

**Comment by kyusonglee** [comment]
> > Thanks for your useful info about downgrading torch version. It works after downgrading the torch version to 1.13.1 and setting the CUDA version to 11.7. I used the following command to reinstall pytorch. `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`
> 
> Hi, can I ask you could you run `import flash_attn_cuda`
> 
> I have the same env as you, but the flash_attn_cuda can not be imported.

I'm encountering the same problem. How did you resolve this issue?
