### ISSUE TITLE
[Usage] Launching Demo : Connection Refused by SGL backend

### ISSUE THREAD

**Issue by deadpipe** [haotian-liu/LLaVA#1230]
### Describe the issue

I am trying to launch the 34b model on WSL2 (ubuntu 22.04)

I have launched 4 instances of command prompt and entered the following commands: 

1. `python -m llava.serve.controller --host 0.0.0.0 --port 10000`

2. `python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload`

3. `CUDA_VISIBLE_DEVICES=0,1 python3 -m sglang.launch_server --model-path "/mnt/s/Models/llava-v1.6-34b" --tokenizer-path liuhaotian/llava-v1.6-34b-tokenizer --port 30000 --tp 2`

4. `python -m llava.serve.sglang_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --sgl-endpoint http://127.0.0.1:30000`

after the 4th command, i get error : 

(llava) badapadda@DESKTOP-UHHHGJ4:~/llava/LLaVA$ python -m llava.serve.sglang_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --sgl-endpoint http://localhost:30000
2024-03-06 02:16:59 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, worker_address='http://localhost:40000', controller_address='http://localhost:10000', model_name=None, sgl_endpoint='http://localhost:30000', limit_model_concurrency=5, stream_interval=1, no_register=False)
2024-03-06 02:16:59 | ERROR | stderr | Traceback (most recent call last):
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 1348, in do_open
2024-03-06 02:16:59 | ERROR | stderr |     h.request(req.get_method(), req.selector, req.data, headers,
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/http/client.py", line 1283, in request
2024-03-06 02:16:59 | ERROR | stderr |     self._send_request(method, url, body, headers, encode_chunked)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/http/client.py", line 1329, in _send_request
2024-03-06 02:16:59 | ERROR | stderr |     self.endheaders(body, encode_chunked=encode_chunked)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/http/client.py", line 1278, in endheaders
2024-03-06 02:16:59 | ERROR | stderr |     self._send_output(message_body, encode_chunked=encode_chunked)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/http/client.py", line 1038, in _send_output
2024-03-06 02:16:59 | ERROR | stderr |     self.send(msg)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/http/client.py", line 976, in send
2024-03-06 02:16:59 | ERROR | stderr |     self.connect()
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/http/client.py", line 942, in connect
2024-03-06 02:16:59 | ERROR | stderr |     self.sock = self._create_connection(
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/socket.py", line 845, in create_connection
2024-03-06 02:16:59 | ERROR | stderr |     raise err
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/socket.py", line 833, in create_connection
2024-03-06 02:16:59 | ERROR | stderr |     sock.connect(sa)
2024-03-06 02:16:59 | ERROR | stderr | ConnectionRefusedError: [Errno 111] Connection refused
2024-03-06 02:16:59 | ERROR | stderr |
2024-03-06 02:16:59 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-03-06 02:16:59 | ERROR | stderr |
2024-03-06 02:16:59 | ERROR | stderr | Traceback (most recent call last):
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-03-06 02:16:59 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
2024-03-06 02:16:59 | ERROR | stderr |     exec(code, run_globals)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/llava/LLaVA/llava/serve/sglang_worker.py", line 238, in <module>
2024-03-06 02:16:59 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/llava/LLaVA/llava/serve/sglang_worker.py", line 62, in __init__
2024-03-06 02:16:59 | ERROR | stderr |     backend = RuntimeEndpoint(sgl_endpoint)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/site-packages/sglang/backend/runtime_endpoint.py", line 22, in __init__
2024-03-06 02:16:59 | ERROR | stderr |     res = http_request(
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/site-packages/sglang/utils.py", line 110, in http_request
2024-03-06 02:16:59 | ERROR | stderr |     resp = urllib.request.urlopen(req, data=data)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 216, in urlopen
2024-03-06 02:16:59 | ERROR | stderr |     return opener.open(url, data, timeout)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 519, in open
2024-03-06 02:16:59 | ERROR | stderr |     response = self._open(req, data)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 536, in _open
2024-03-06 02:16:59 | ERROR | stderr |     result = self._call_chain(self.handle_open, protocol, protocol +
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 496, in _call_chain
2024-03-06 02:16:59 | ERROR | stderr |     result = func(*args)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 1377, in http_open
2024-03-06 02:16:59 | ERROR | stderr |     return self.do_open(http.client.HTTPConnection, req)
2024-03-06 02:16:59 | ERROR | stderr |   File "/home/badapadda/miniconda3/envs/llava/lib/python3.10/urllib/request.py", line 1351, in do_open
2024-03-06 02:16:59 | ERROR | stderr |     raise URLError(err)
2024-03-06 02:16:59 | ERROR | stderr | urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

Any help is highly appreciated

**Comment by deadpipe** [comment]
UPDATE :

I installed Ubuntu 22 dual boot on my computer and followed the same steps as above and i get the exact same error

**Comment by EYcab** [comment]
Met the exact save problem

**Comment by deadpipe** [comment]
have you found a solution @EYcab ?

**Comment by EYcab** [comment]
@deadpipe ,no,have you?

**Comment by deadpipe** [comment]
no, @EYcab 

but a temporary solution is to not use Sgl backend at all. Use the traditional old way and launch llava-1.6-34b with these three commands -

`python -m llava.serve.controller --host 0.0.0.0 --port 10000`


`python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload`

`CUDA_VISIBLE_DEVICES=0 python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1.6-34b --load-4bit`

And the model runs on 20GB Vram

**Comment by EYcab** [comment]
@deadpipe ,got you.
