### ISSUE TITLE
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

### ISSUE THREAD

**Issue by 20191864218** [haotian-liu/LLaVA#1239]
### Question

When I encountered this error during run finetune_lora.sh, how should I resolve it? Thank you for your assistance

Traceback (most recent call last):
  File "/root/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train()
  File "/root/LLaVA/llava/train/train.py", line 1098, in train
    trainer.train()
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1690, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = self._prepare_deepspeed(*args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 304, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1208, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1279, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 458, in load
    return self.jit_load(verbose)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 490, in jit_load
    cxx_args = self.strip_empty_entries(self.cxx_args())
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 738, in cxx_args
    CUDA_ENABLE = self.is_cuda_enable()
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 350, in is_cuda_enable
    assert_no_cuda_mismatch(self.name)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 101, in assert_no_cuda_mismatch
    raise CUDAMismatchException(
deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 11.8 does not match the version torch was compiled with 12.1, unable to compile cuda/cpp extensions without a matching cuda version.
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f7e8ecc7be0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
[2024-03-07 21:33:13,113] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 38255

**Comment by happywinder** [comment]
hello，could you share your recipe to solve this problem ，i met the same bug

**Comment by YanzhaoDrew** [comment]
`import subprocess
import sys
import os


def install_deepspeed():
    # Set environment variables
    os.environ['DS_BUILD_CPU_ADAM'] = '1'
    os.environ['BUILD_UTILS'] = '1'

    # Construct the pip command
    pip_command = [sys.executable, '-m', 'pip', 'install', 'deepspeed==0.14.4', '-U']

    # Run the pip command
    try:
        subprocess.check_call(pip_command)
        print("DeepSpeed installed successfully!")
    except subprocess.CalledProcessError as e:
        print(f"Error installing DeepSpeed: {e}")


if __name__ == "__main__":
    install_deepspeed()`

**Comment by YanzhaoDrew** [comment]
`
import subprocess
import sys
import os


def install_deepspeed():
    # Set environment variables
    os.environ['DS_BUILD_CPU_ADAM'] = '1'
    os.environ['BUILD_UTILS'] = '1'

    # Construct the pip command
    pip_command = [sys.executable, '-m', 'pip', 'install', 'deepspeed==0.14.4', '-U']

    # Run the pip command
    try:
        subprocess.check_call(pip_command)
        print("DeepSpeed installed successfully!")
    except subprocess.CalledProcessError as e:
        print(f"Error installing DeepSpeed: {e}")


if __name__ == "__main__":
    install_deepspeed()
    `

**Comment by YanzhaoDrew** [comment]
```
import subprocess
import sys
import os

def install_deepspeed():
    # Set environment variables
    os.environ['DS_BUILD_CPU_ADAM'] = '1'
    os.environ['BUILD_UTILS'] = '1'

    # Construct the pip command
    pip_command = [sys.executable, '-m', 'pip', 'install', 'deepspeed==0.14.4', '-U']

    # Run the pip command
    try:
        subprocess.check_call(pip_command)
        print("DeepSpeed installed successfully!")
    except subprocess.CalledProcessError as e:
        print(f"Error installing DeepSpeed: {e}")

if __name__ == "__main__":
    install_deepspeed()
```

**Comment by YanzhaoDrew** [comment]
> hello，could you share your recipe to solve this problem ，i met the same bug

```
import subprocess
import sys
import os

def install_deepspeed():
    # Set environment variables
    os.environ['DS_BUILD_CPU_ADAM'] = '1'
    os.environ['BUILD_UTILS'] = '1'

    # Construct the pip command
    pip_command = [sys.executable, '-m', 'pip', 'install', 'deepspeed==0.14.4', '-U']

    # Run the pip command
    try:
        subprocess.check_call(pip_command)
        print("DeepSpeed installed successfully!")
    except subprocess.CalledProcessError as e:
        print(f"Error installing DeepSpeed: {e}")

if __name__ == "__main__":
    install_deepspeed()
```

**Comment by SStoica12** [comment]
If anyone has this issue and above does not work (as did not for me), what may help is following https://github.com/deepspeedai/DeepSpeed/issues/3488#issuecomment-1663170272
