### ISSUE TITLE
Error during this command: pip install flash-attn==2.0.4 --no-build-isolation

### ISSUE THREAD

**Issue by chanangad** [haotian-liu/LLaVA#1248]
### Describe the issue

Issue: 

Command:
```
pip install flash-attn==2.0.4 --no-build-isolation
```

Log: 
```
(llava) achandhok@achandhok-0-0:/sensei-fs/users/achandhok/LLaVA$ pip install flash-attn==2.0.4 --no-build-isolation
Collecting flash-attn==2.0.4
  Using cached flash_attn-2.0.4.tar.gz (4.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-v8_kacfm/flash-attn_d20678f39509460397d2b69d9bc4b015/setup.py", line 13, in <module>
          import torch
        File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/__init__.py", line 235, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /opt/conda/envs/llava/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
![Uploading Screenshot 2024-03-08 at 3.10.00 PM.png…]()

**Comment by chanangad** [comment]
Used the v1.1.3 release and this issue wasn't there anymore

**Comment by Zero-coder** [comment]
![Image](https://github.com/user-attachments/assets/229b6540-b327-4a26-b70c-0f391dc4ac3f) I don't think so~
