### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for LlavaLlamaForCausalLM:[Question] 

### ISSUE THREAD

**Issue by zhyhome** [haotian-liu/LLaVA#1268]
### Question

**when I finetuned llava-v1.5-13b by :**

deepspeed llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero3_offload.json \
    --model_name_or_path llava-v1.5-13b \
    --version v1 \
    --data_path ./playground/data/llava-1.5-13B-lora-sacarasm.json \
    --image_folder ./playground/data/twitter/ \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir llava-v1.5-13b-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

**Then, I tried many ways to use the finetuned model,such as run_llava.py, but there's a problem with all of them when inference:**

[2024-03-11 22:31:41,166] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading LLaVA from base model...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.31s/it]
Loading additional LLaVA weights...
Traceback (most recent call last):
  File "/root/autodl-tmp/LLaVA/llava/eval/run_llava.py", line 149, in <module>
    eval_model(args)
  File "/root/autodl-tmp/LLaVA/llava/eval/run_llava.py", line 57, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(
  File "/root/autodl-tmp/LLaVA/llava/model/builder.py", line 79, in load_pretrained_model
    model.load_state_dict(non_lora_trainables, strict=False)
  File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlavaLlamaForCausalLM:
        size mismatch for model.mm_projector.0.weight: copying a param with shape torch.Size([5120, 1024]) from checkpoint, the shape in current model is torch.Size([2621440, 1]).
        size mismatch for model.mm_projector.2.weight: copying a param with shape torch.Size([5120, 5120]) from checkpoint, the shape in current model is torch.Size([13107200, 1]).

**I tried 4-bit,do-sample,temperature and so on to handle this. But this model can't generate anything. This code can be inferred on the base model: llava-v1.5-13b. I print the output_ids[0] below:**
![1](https://github.com/haotian-liu/LLaVA/assets/94852722/0839b734-b659-4610-bf1a-f81bbb602bd4)
This is a normal result based on llava-v1.5-13b
![2](https://github.com/haotian-liu/LLaVA/assets/94852722/8403baa5-32f4-4c5d-a7be-566c044a0470)
This is a abnormal result based on finetuned model, whether merge or unmerged.

**Comment by sreejank** [comment]
Having the same issue

**Comment by 20191864218** [comment]
Did you manage to resolve it

**Comment by awzhgw** [comment]
Having the same issue

**Comment by Xuefei98** [comment]
same issue here
