### ISSUE TITLE
[Usage] SGLang Launch: AttributeError: 'str' object has no attribute 'eos_token_id'

### ISSUE THREAD

**Issue by charliedream1** [haotian-liu/LLaVA#1274]
### Describe the issue

Issue:
router init state: Traceback (most recent call last):
  File "/home/a/miniconda3/envs/py310/lib/python3.10/site-packages/sglang/srt/managers/router/manager.py", line 68, in start_router_process
    model_client = ModelRpcClient(server_args, port_args)
  File "/home/a/miniconda3/envs/py310/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 619, in __init__
    self.model_server.exposed_init_model(0, server_args, port_args)
  File "/home/a/miniconda3/envs/py310/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 137, in exposed_init_model
    self.regex_fsm_cache = FSMCache(
  File "/home/a/miniconda3/envs/py310/lib/python3.10/site-packages/sglang/srt/constrained/fsm_cache.py", line 8, in __init__
    self.outlines_tokenizer = TransformerTokenizer(
  File "/home/a/miniconda3/envs/py310/lib/python3.10/site-packages/outlines/models/transformers.py", line 63, in __init__
    self.eos_token_id = self.tokenizer.eos_token_id
AttributeError: 'str' object has no attribute 'eos_token_id'

Command:
```
CUDA_VISIBLE_DEVICES=0 python3 -m sglang.launch_server --model-path liuhaotian/llava-v1.5-7b --tokenizer-path llava-hf/llava-1.5-7b-hf --port 30000
```

Log: 
```
PASTE THE LOGS HERE.
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by tfcoe-depop** [comment]
https://github.com/sgl-project/sglang/issues/292 This has been raised and a temporary solution addressed in sglang project.

**Comment by butchmarshall** [comment]
fyi https://github.com/haotian-liu/LLaVA/pull/1302 works around the issue
