### ISSUE TITLE
[Usage] 

### ISSUE THREAD

**Issue by Get-David** [haotian-liu/LLaVA#1366]
### Describe the issue

This is my error message:
```python
(llava) zdw@ai-gpu-server149:~/LLaVA$ python test.py
Traceback (most recent call last):
  File "/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 55, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zdw/LLaVA/test.py", line 1, in <module>
    from llava.model.builder import load_pretrained_model
  File "/home/zdw/LLaVA/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/home/zdw/LLaVA/llava/model/__init__.py", line 2, in <module>
    from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
  File "/home/zdw/LLaVA/llava/model/language_model/llava_llama.py", line 21, in <module>
    from transformers import AutoConfig, AutoModelForCausalLM, \
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1355, in __getattr__
    value = getattr(module, name)
  File "/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1354, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1366, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_
(llava) zdw@ai-gpu-server149:~/LLaVA$ 
```
我尝试安装但是没有任何问题：
```python
(llava) zdw@ai-gpu-server149:~/LLaVA$ pip install flash-attn --no-build-isolation --no-cache-dir
Looking in indexes: http://registry.xtrfr.cn/repository/pypi-test/simple/
Requirement already satisfied: flash-attn in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (2.5.6)
Requirement already satisfied: torch in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from flash-attn) (2.1.2)
Requirement already satisfied: einops in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from flash-attn) (0.6.1)
Requirement already satisfied: packaging in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from flash-attn) (24.0)
Requirement already satisfied: ninja in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from flash-attn) (1.11.1.1)
Requirement already satisfied: filelock in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (3.13.3)
Requirement already satisfied: typing-extensions in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (4.10.0)
Requirement already satisfied: sympy in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (1.12)
Requirement already satisfied: networkx in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (3.2.1)
Requirement already satisfied: jinja2 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (3.1.3)
Requirement already satisfied: fsspec in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (2024.3.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (2.18.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: triton==2.1.0 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from torch->flash-attn) (2.1.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->flash-attn) (12.4.99)
Requirement already satisfied: MarkupSafe>=2.0 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from jinja2->torch->flash-attn) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /data/share8/zdw/miniconda3/envs/llava/lib/python3.10/site-packages (from sympy->torch->flash-attn) (1.3.0)
(llava) zdw@ai-gpu-server149:~/LLaVA$ 
```
test.py内容如下：
```python
from llava.model.builder import load_pretrained_model
from llava.mm_utils import get_model_name_from_path
from llava.eval.run_llava import eval_model

model_path = "/home/zdw/Open-Sora/pre_training/llava-v1.6-34b"

tokenizer, model, image_processor, context_len = load_pretrained_model(
    model_path=model_path,
    model_base=None,
    model_name=get_model_name_from_path(model_path)
)

prompt = "What are the things I should be cautious about when I visit here?"
image_file = "https://llava-vl.github.io/static/images/view.jpg"

args = type('Args', (), {
    "model_path": model_path,
    "model_base": None,
    "model_name": get_model_name_from_path(model_path),
    "query": prompt,
    "conv_mode": None,
    "image_file": image_file,
    "sep": ",",
    "temperature": 0,
    "top_p": None,
    "num_beams": 1,
    "max_new_tokens": 512
})()

eval_model(args)
```

**Comment by Joe-J** [comment]
I have the same problem

**Comment by KatameRonin** [comment]
I have a similar issue. 
My error looks like this:
`RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'OutOfResources' from partially initialized module 'triton.runtime.autotuner' (most likely due to a circular import)`

I tried reinstalling several times too. Does anyone have a solution?

**Comment by eware-godaddy** [comment]
I solved this by:

```
pip uninstall flash-attn
pip install flash-attn --no-build-isolation --no-cache-dir
```
