### ISSUE TITLE
[Question]  Error during this command: pip install flash-attn --no-build-isolation

### ISSUE THREAD

**Issue by Ahnhojin1223** [haotian-liu/LLaVA#1369]
### Question

Command:
`pip install flash-attn --no-build-isolation`

Log:
`Collecting flash-attn
  Downloading flash_attn-2.5.6.tar.gz (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 11.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9u5e9dng/flash-attn_e362cbbd46404df8a4978593d8bb899c/setup.py", line 114, in <module>
          raise RuntimeError(
      RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
      
      
      torch.__version__  = 2.1.2+cu121
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

Enviroment:
`Ubuntu 20.04`

How can I do????
My Cuda version is:
`Cuda compilation tools, release 10.1, V10.1.243`

![1](https://github.com/haotian-liu/LLaVA/assets/63521098/acd80c26-f04f-4bf4-922f-0b374ea3a1c0)

![2](https://github.com/haotian-liu/LLaVA/assets/63521098/5abf0060-f7a5-4858-a745-547fedc9586f)

![3](https://github.com/haotian-liu/LLaVA/assets/63521098/b5490987-5170-4933-96c0-0cb9199195d0)

**Comment by iFe1er** [comment]
same question

**Comment by FuZening** [comment]
Same question! If you find any solution, please tell me! Thank you very much in advance!

**Comment by JonathonYan1993** [comment]
try to install the version of flash-attention compiled with torch which you can download from https://github.com/Dao-AILab/flash-attention/releases/tag/v2.5.8  will be useful

**Comment by zs-zhong** [comment]
`pip install flash-attn=2.5.5 --no-build-isolation`

**Comment by 2416602906** [comment]
同样的问题！请问您解决了吗？希望能得到最新的消息，万分感谢！

**Comment by lwwdww** [comment]
same question

**Comment by riderexin** [comment]
Same problem, solved by downgrading to 2.7.3 with `pip install flash-attn==2.7.3 --no-build-isolation`

https://github.com/Dao-AILab/flash-attention/issues/1503#issuecomment-2676484761
