### ISSUE TITLE
It's so strange, accelerate==0.21.0, It said cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' when I change accelerate==0.28.0. It worked

### ISSUE THREAD

**Issue by 459737087** [haotian-liu/LLaVA#1379]
### Describe the issue

Issue:

Command:
```
python -m llava.serve.controller --host 0.0.0.0 --port 10000
```

Log: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/data/yanxin/LLaVA-main/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model'
```

when I use accelerate==0.28.0
run 
```
python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload --port 8080
``` 
ERROR | stderr | /usr/local/lib/python3.10/site-packages/gradio/components/dropdown.py:163: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.

and I can't curl the http

**Comment by nj159** [comment]
Have you solved this problem? How was it resolved?thanks

**Comment by 459737087** [comment]
No, I'm waiting for somebody solving it.
@nj159

**Comment by wentaoyuan** [comment]
Also have the same problem.

**Comment by MismatchQuest** [comment]
I am having the same issue.

**Comment by Hameed92** [comment]
I had the same problem, it worked when I ran `pip install accelerate -U`

**Comment by xing0047** [comment]
same issue.

**Comment by 1835969208** [comment]
卧槽 牛逼啊

**Comment by cumthxy** [comment]
牛逼！！！！！！！
