### ISSUE TITLE
[Usage] Merging and Finetuning llava 1.5 13b

### ISSUE THREAD

**Issue by VictorYrotciV** [haotian-liu/LLaVA#1406]
### Describe the issue

Issue:
It seems that current environment(2024/4/16) has a confilict between lora merging and model vqa, that I have to switch the environment before and after lora merging to make both lora merging and model vqa run successfully. I'm finetuning and evaluating on my custom dataset. Are there any more general and simple solutions to this?

**To reproduce:**
Install the newest environment following llava readme.

Command:
First finetune with lora
```
scripts/v1_5/finetune_lora.sh
```
Then merge the lora weights
```
python scripts/merge_lora_weights.py --model-path checkpoints/my-llava-v1.5-13b-lora-path/ --model-base lmsys/vicuna-13b-v1.5 --save-model-path checkpoints/my-merged-llava-v1.5-13b-lora-path
```
However this will cause some error, and there will be only a config file in the merged path:
```
Loading checkpoint shards:   0%|                                                                                                                                                      | 0/3 [00:00<?, ?it/s]/root/miniconda3/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  8.66it/s]
Some weights of LlavaLlamaForCausalLM were not initialized from the model checkpoint at lmsys/vicuna-13b-v1.5 and are newly initialized: ['model.mm_projector.0.bias', 'model.mm_projector.0.weight', 'model.mm_projector.2.bias', 'model.mm_projector.2.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/root/miniconda3/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:392: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/root/miniconda3/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:397: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
Loading additional LLaVA weights...
Loading LoRA weights...
Merging LoRA weights...
Model is loaded...
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'max_length': 4096}
Your generation config was originally created from the model config, but the model config has changed since then. Unless you pass the `generation_config` argument to this model's `generate` calls, they will revert to the legacy behavior where the base `generate` parameterization is loaded from the model config instead. To avoid this behavior and this warning, we recommend you to overwrite the generation config model attribute before calling the model's `save_pretrained`, preferably also removing any generation kwargs from the model config. This warning will be raised to an exception in v4.41.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 558, in save_pretrained
    raise ValueError(str([w.message for w in caught_warnings]))
ValueError: [UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.'), UserWarning('`do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/LLaVA/scripts/merge_lora_weights.py", line 22, in <module>
    merge_lora(args)
  File "/home/LLaVA/scripts/merge_lora_weights.py", line 10, in merge_lora
    model.save_pretrained(args.save_model_path)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2364, in save_pretrained
    model_to_save.generation_config.save_pretrained(save_directory)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 560, in save_pretrained
    raise ValueError(
ValueError: The generation config instance is invalid -- `.validate()` throws warnings and/or exceptions. Fix these issues to save the configuration.

Thrown during validation:
[UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.'), UserWarning('`do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.')]
```
Following [this issue](https://github.com/haotian-liu/LLaVA/issues/1194), I downgraded transformer by this command:
```
pip install git+https://github.com/huggingface/transformers@v4.31-release
```
Afterwards merging process succeeded. However as I followed up to evaluate by the following command,
```
python llava/eval/model_vqa.py --model-path ./checkpoints/my-merged-llava-v1.5-13b-lora-path/  --model-base lmsys/vicuna-13b-v1.5 --question-file   playground/data/my-questions.jsonl  --image-folder   my-image-folder --answers-file  playground/data/my-llava-answers-path.jsonl
```
Some error occured
```
Loading LLaVA from base model...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:17<00:00,  5.82s/it]
Some weights of LlavaLlamaForCausalLM were not initialized from the model checkpoint at lmsys/vicuna-13b-v1.5 and are newly initialized: ['model.mm_projector.2.bias', 'model.mm_projector.2.weight', 'model.mm_projector.0.weight', 'model.mm_projector.0.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/LLaVA/llava/eval/model_vqa.py", line 101, in <module>
    eval_model(args)
  File "/home/LLaVA/llava/eval/model_vqa.py", line 34, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, args.model_base, model_name)
  File "/home/LLaVA/llava/model/builder.py", line 157, in load_pretrained_model
    vision_tower.load_model(device_map=device_map)
  File "/home/LLaVA/llava/model/multimodal_encoder/clip_encoder.py", line 30, in load_model
    self.vision_tower = CLIPVisionModel.from_pretrained(self.vision_tower_name, device_map=device_map)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2804, in from_pretrained
    raise ValueError(
ValueError: CLIPVisionModel does not support `device_map='auto'`. To implement support, the modelclass needs to implement the `_no_split_modules` attribute.
```
I had searched tfor similar issues in llava repository, but found nothing. I figured one solution out by upgrading environments:
```
pip install -e .
```
Afterwards I could go through model_vqa successfully. However these operations are annoying, as I need to manually switch the environment twice everytime I need to merge model params after finetuning with lora. This simple solution even may not work anymore after some codebases like transformer updates in future. Did I do something incorrect like incomplete command to get this issue? Or are there more general and simple solutions to this?

**Comment by VictorYrotciV** [comment]
NVM. I've mistaken some of the checkpoint paths.  model_vqa.py is able to directly work on lora unmerged path.
