### ISSUE TITLE
Testing LLaVA-MPT model after pre-training

### ISSUE THREAD

**Issue by chanangad** [haotian-liu/LLaVA#1415]
### Question

I ran pre-training for the the LLaVA model using the following command:

```
torchrun --nnodes=1 --nproc_per_node=8 --master_port=25001 \
     train_mem.py \
    --model_name_or_path customMPTmodel \
    --version mpt\
    --data_path /mnt/localssd/LLaVA-Pretrain/blip_laion_cc_sbu_558k.json \
    --image_folder /mnt/localssd/LLaVA-Pretrain/images \
    --vision_tower openai/clip-vit-large-patch14 \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```
    
I get a lot of Tokenizer mismatch messages on every other iteration but the loss keeps decreasing and the pre-training completes. Now I want to test out the pre-trained model on a sample image before starting the instruction tuning.

I run this command:

```
python -m llava.serve.cli \
    --model-base  customMPTmodel \
    --model-path ./checkpoints/llava-v1.5-pretrain/ \
    --image-file ./PXL_20230304_023217466.jpg \
    --temperature 0.1
```

When I give the prompt as: "Describe the image"

I get this runtime error:

```
Traceback (most recent call last):
  File "/opt/conda/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/sensei-fs/users/achandhok/LLaVA-1.1.3-adobeone/llava/serve/cli.py", line 120, in <module>
    main(args)
  File "/sensei-fs/users/achandhok/LLaVA-1.1.3-adobeone/llava/serve/cli.py", line 97, in main
    output_ids=model.generate(input_ids,images=image_tensor,do_sample=True,temperature=args.temperature,max_new_tokens=args.max_new_tokens,streamer=streamer,use_cache=True,stopping_criteria=[stopping_criteria])
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2679, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

I saw a couple other people facing similar issue but there wasn't any clear solution posted for the same. I'd appreciate it a lot if someone can point me in the correct direction.

**Comment by asunaperisi** [comment]
same problem but after finetuning with my own data. Did you solved it?

**Comment by chanangad** [comment]
I was using the older version of the code (v1.1.3 to be specific). Didn't get this after switching to the latest code base

**Comment by asunaperisi** [comment]
I switched with latest code base tried it again with cli but I got same error. Did you finetune it again with new code base or just switched the code base and worked for inference ?Thank you so much for your quick answer.

**Comment by chanangad** [comment]
yes, I pre-trained again. I was working with the MPT model. If you get a tokeniser mismatch warning while training, you need to rectify that as it can lead to bad learning during pretraining

**Comment by zihui-debug** [comment]
> yes, I pre-trained again. I was working with the MPT model. If you get a tokeniser mismatch warning while training, you need to rectify that as it can lead to bad learning during pretraining

Hello, I encounter the same error, how did you solve the mismatch problem?
