### ISSUE TITLE
How to merge lora which is of safetensors type(adapter_model.safetensor) for LLaVA-v1.6

### ISSUE THREAD

**Issue by rohithbojja** [haotian-liu/LLaVA#1416]
Command:

python scripts/merge_lora_weights.py --model-path /home/rohith/Documents/mistral-llava/  --model-base /media/rohith/CC2A79902A7977F2/models/llava-v1.6-mistral-7b/  --save-model-path /home/rohith/Desktop/mistral-llava-merge

Log: 

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.30it/s]
Traceback (most recent call last):
  File "/home/rohith/LLaVA-1.6-ft/scripts/merge_lora_weights.py", line 22, in <module>
    merge_lora(args)
  File "/home/rohith/LLaVA-1.6-ft/scripts/merge_lora_weights.py", line 8, in merge_lora
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, device_map='cpu')
  File "/home/rohith/LLaVA-1.6-ft/llava/model/builder.py", line 112, in load_pretrained_model
    mm_projector_weights = torch.load(os.path.join(model_path, 'mm_projector.bin'), map_location='cpu')
  File "/home/rohith/miniconda3/envs/llava/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/rohith/miniconda3/envs/llava/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/rohith/miniconda3/envs/llava/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/rohith/Documents/mistral-llava/mm_projector.bin'

**Comment by rohithbojja** [comment]
had to include lora in model name
thats all fixed

**Comment by DebaratiD** [comment]
Hi Rohith,

I am trying to use the med-vqa dataset you uploaded on hugging face but need help on that. Please let me know how I can find the entire image dataset for the same.

Regards,
Debarati

**Comment by rohithbojja** [comment]
> Hi Rohith,
> 
> I am trying to use the med-vqa dataset you uploaded on hugging face but need help on that. Please let me know how I can find the entire image dataset for the same.
> 
> Regards, Debarati

https://huggingface.co/datasets/rbojja/medical-vqa/tree/main/vqa-rad/images
