### ISSUE TITLE
[Question] Failed to satart LoRA because of TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'

### ISSUE THREAD

**Issue by fisher75** [haotian-liu/LLaVA#1438]
### Question

Hi I got problems encountered when trying to LoRA.

Seems like the main problem is: `TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'`

The logging part:
```
[2024-04-22 03:43:13,255] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-22 03:43:28,314] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0,1,2,3: setting --include=localhost:0,1,2,3
[2024-04-22 03:43:28,314] [INFO] [runner.py:571:main] model/lora/llava-v1.6-vicuna-7b-DSLLM-lora --num_train_epochs 1 --per_device_train_batch_size 16 --per_device_eval_batch_size 4 --gradient_accumulation_steps 1 --evaluation_strategy no --save_strategy steps --save_steps 50000 --save_total_limit 1 --learning_rate 2e-4 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 1 --tf32 True --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to wandb
[2024-04-22 03:43:31,655] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-22 03:43:35,116] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2024-04-22 03:43:35,116] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=4, node_rank=0
[2024-04-22 03:43:35,116] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2024-04-22 03:43:35,116] [INFO] [launch.py:163:main] dist_world_size=4
[2024-04-22 03:43:35,116] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2024-04-22 03:43:45,842] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-22 03:43:45,843] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-22 03:43:45,844] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-22 03:43:45,844] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-22 03:43:56,196] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-22 03:43:56,196] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-22 03:43:56,196] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-04-22 03:43:56,196] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-22 03:43:56,196] [INFO] [comm.py:637:init_distributed] cdb=None
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
anaconda3/envs/llava/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
anaconda3/envs/llava/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
anaconda3/envs/llava/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
anaconda3/envs/llava/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
[2024-04-22 03:44:17,345] [INFO] [partition_parameters.py:348:__exit__] finished initializing model - num_params = 687, num_elems = 7.06B

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:  33%|███▎      | 1/3 [00:01<00:03,  1.82s/it]
Loading checkpoint shards:  33%|███▎      | 1/3 [00:01<00:03,  1.83s/it]
Loading checkpoint shards:  33%|███▎      | 1/3 [00:01<00:03,  1.84s/it]
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:04<00:02,  2.04s/it]
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:04<00:02,  2.04s/it]
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:04<00:02,  2.04s/it]
Loading checkpoint shards:  33%|███▎      | 1/3 [00:05<00:11,  5.65s/it]
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:09<00:04,  4.30s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:13<00:00,  5.52s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:13<00:00,  4.56s/it]

Loading checkpoint shards: 100%|██████████| 3/3 [00:13<00:00,  5.52s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:13<00:00,  4.56s/it]

Loading checkpoint shards: 100%|██████████| 3/3 [00:13<00:00,  5.52s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:13<00:00,  4.56s/it]

Loading checkpoint shards: 100%|██████████| 3/3 [00:14<00:00,  4.64s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:14<00:00,  4.69s/it]
Adding LoRA adapters...
openai/clip-vit-large-patch14-336 is already loaded, `load_model` called again, skipping.
openai/clip-vit-large-patch14-336 is already loaded, `load_model` called again, skipping.
openai/clip-vit-large-patch14-336 is already loaded, `load_model` called again, skipping.
openai/clip-vit-large-patch14-336 is already loaded, `load_model` called again, skipping.
Formatting inputs...Skip in lazy mode
Traceback (most recent call last):
  File "VLM/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "VLM/LLaVA/llava/train/train.py", line 961, in train
    trainer = LLaVATrainer(model=model,
  File "anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 367, in __init__
    self.create_accelerator_and_postprocess()
  File "anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 4127, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'
Traceback (most recent call last):
  File "VLM/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "VLM/LLaVA/llava/train/train.py", line 961, in train
    trainer = LLaVATrainer(model=model,
  File "anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 367, in __init__
    self.create_accelerator_and_postprocess()
  File "anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 4127, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'
Traceback (most recent call last):
  File "VLM/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "VLM/LLaVA/llava/train/train.py", line 961, in train
    trainer = LLaVATrainer(model=model,
  File "anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 367, in __init__
    self.create_accelerator_and_postprocess()
  File "anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 4127, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'
Traceback (most recent call last):
  File "VLM/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "VLM/LLaVA/llava/train/train.py", line 961, in train
    trainer = LLaVATrainer(model=model,
  File "anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 367, in __init__
    self.create_accelerator_and_postprocess()
  File "anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 4127, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'
```

**Comment by foreverhell** [comment]
Excuse me. I also encounter this error. Could you please tell me how do you fix it? Thanks very much.

**Comment by ashmalvayani** [comment]
@fisher75 what was the solution of this error?
