### ISSUE TITLE
[Usage] Vicuna v1.5 is not downloaded automatically

### ISSUE THREAD

**Issue by glahoti6** [haotian-liu/LLaVA#1476]
### Describe the issue

Looks like base model Vicuna v1.5 is not downloaded automatically when I run the provided training scripts. Did anyone face this issue?

```
Traceback (most recent call last):
  File "/miniconda/envs/llava/lib/python3.10/site-packages/transformers/utils/hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "/miniconda/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 111, in _inner_fn
    validate_repo_id(arg_value)
  File "/miniconda/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 159, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './checkpoints/vicuna-7b-v1-5'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "/LLaVA/llava/train/train.py", line 827, in train
    model = LlavaLlamaForCausalLM.from_pretrained(
  File "/miniconda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3075, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/miniconda/envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 605, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/miniconda/envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 634, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/miniconda/envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/miniconda/envs/llava/lib/python3.10/site-packages/transformers/utils/hub.py", line 450, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: './checkpoints/vicuna-7b-v1-5'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

**Comment by dennismyself** [comment]
I have exactly the same error, it took me a while to find it.
Ensure the script you are calling is bash scripts/v1_5/pretrain.sh NOT bash scripts/pretrain.sh and in the file --model_name_or_path lmsys/vicuna-13b-v1.5

**Comment by tianke0711** [comment]
@dennismyself 

Thanks for your comment, could you give more details, please, I have the same issue when I run sh pretrain.sh

**Comment by yuezhao238** [comment]
Try absolute path, not relative path
