### ISSUE TITLE
[Usage] Need to install protobuf in order to run CLI Inference

### ISSUE THREAD

**Issue by cuihenggang** [haotian-liu/LLaVA#1522]
### Describe the issue

Issue:

Command:
```
$ python -m llava.serve.cli \
>     --model-path liuhaotian/llava-v1.5-7b \
>     --image-file "https://llava-vl.github.io/static/images/view.jpg" \
>     --load-4bit
```

Log: 
```
/home/hcui/python/envs/llava/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 749/749 [00:00<00:00, 3.09MB/s]
tokenizer.model: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 16.3MB/s]
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 438/438 [00:00<00:00, 2.31MB/s]
Traceback (most recent call last):
  File "/home/hcui/python/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hcui/python/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hcui/repos/LLaVA/llava/serve/cli.py", line 126, in <module>
    main(args)
  File "/home/hcui/repos/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/home/hcui/repos/LLaVA/llava/model/builder.py", line 116, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "/home/hcui/python/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 814, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/hcui/python/envs/llava/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
    return cls._from_pretrained(
  File "/home/hcui/python/envs/llava/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2261, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/hcui/python/envs/llava/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 178, in __init__
    self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
  File "/home/hcui/python/envs/llava/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 208, in get_spm_processor
    model_pb2 = import_protobuf(f"The new behaviour of {self.__class__.__name__} (with `self.legacy = False`)")
  File "/home/hcui/python/envs/llava/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 43, in import_protobuf
    raise ImportError(PROTOBUF_IMPORT_ERROR.format(error_message))
ImportError: 
The new behaviour of LlamaTokenizer (with `self.legacy = False`) requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
```

**Comment by ggcr** [comment]
`pip install protobuf` and you will be able to run it fine.

**Comment by cuihenggang** [comment]
I think it will be useful to add this dependency to the requirement list for `pip install`

**Comment by ggcr** [comment]
Agree. The dependency comes from the `transformers` library, not LLaVA.

https://github.com/huggingface/transformers/issues/24533

**Comment by cuihenggang** [comment]
I see. Thank you for the explanation. Feel free to close the ticket if nothing we can do in this project.

**Comment by KansaiTraining** [comment]
At least it would be a good idea to include this info in the readme, so that users do not have to come to here
