### ISSUE TITLE
[Usage] Error when loading adapter_model.safetensors 

### ISSUE THREAD

**Issue by NicoZenith** [haotian-liu/LLaVA#1540]
### Describe the issue

Issue:

After fine-tuning llava v.1.5 13b, with the last version of the repository, when I try to load the Lora weights, I get the following error 

Command:
```
python -m llava.serve.cli     --model-path checkpoints/llava-v1.5-13b-lora --model-base liuhaotian/llava-v1.5-13b    --image-file "https://llava-vl.github.io/static/images/view.jpg"  
```

Log: 
```
Loading LLaVA from base model...
Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  8.41it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:11<00:00,  3.92s/it]
Loading additional LLaVA weights...
Loading LoRA weights...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/iopsstor/scratch/cscs/ndeperr/LLaVA/llava/serve/cli.py", line 126, in <module>
    main(args)
  File "/iopsstor/scratch/cscs/ndeperr/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/iopsstor/scratch/cscs/ndeperr/LLaVA/llava/model/builder.py", line 83, in load_pretrained_model
    model = PeftModel.from_pretrained(model, model_path)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 430, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 984, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py", line 444, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 311, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

It seems that the loading works for 1.6 lora weights, but there is no training script for llava 1.6 (I used the one from llava 1.5).

**Comment by Searen-da** [comment]
I had similar issue and [this comment](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8123#issuecomment-2056883519) really helped. Try redownloading the file using git-lfs

**Comment by NicoZenith** [comment]
Nevermind, it's because I wanted to modify the key names of the weights and it corrupted the file. 
Indeed, I need to change the name of the weights so that it matches the one of the huggingface version (https://huggingface.co/llava-hf/llava-1.5-13b-hf) otherwise the LoRA merging wouldn't occur :)
