### ISSUE TITLE
Finetuning Using Multiple GPUS -- deepspeed batch size check not passing

### ISSUE THREAD

**Issue by dipikakhullar** [haotian-liu/LLaVA#1617]
### Describe the issue

I've just been following the finetuning instructions on this repo, using deepspeed==0.14.0. When I run finetune_task_lora.sh using either zero2.json or zero3.json I see the folllowing issue:

I have put prints everywhere, and somehow it gives me a runtime error on this last line within train:
```
def train(attn_implementation=None):
    global local_rank

    parser = transformers.HfArgumentParser(
        (ModelArguments, DataArguments, TrainingArguments))
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
    local_rank = training_args.local_rank

    # Ensure only one precision mode is enabled
    # print(training_args.fp16, training_args.bf16)
    # if training_args.fp16 and training_args.bf16:
    #     print("Both fp16 and bf16 are enabled. Disabling bf16 and using fp16.")
    #     training_args.bf16 = False


    compute_dtype = (torch.float16 if training_args.fp16 else (torch.bfloat16 if training_args.bf16 else torch.float32))

    # Ensure correct initialization of distributed environment
    if dist.is_available() and not dist.is_initialized():
        dist.init_process_group(backend='nccl')
    print(f"Distributed backend initialized. World size: {dist.get_world_size()}, Rank: {dist.get_rank()}")

    # DeepSpeed configuration
    print(f"DeepSpeed configuration file: {training_args.deepspeed}")
    expected_train_batch_size = training_args.per_device_train_batch_size * dist.get_world_size() * training_args.gradient_accumulation_steps
    print(f"Expected train_batch_size: {expected_train_batch_size}")

    # DeepSpeed configuration

    # DeepSpeed configuration
    print(f"DeepSpeed configuration file: {training_args.deepspeed}")
    print(f"Expected train_batch_size: {training_args.per_device_train_batch_size * dist.get_world_size() * training_args.gradient_accumulation_steps}")
    
    deepspeed_config = deepspeed.runtime.config.DeepSpeedConfig(training_args.deepspeed)

```

It seems like the same issue here https://github.com/microsoft/DeepSpeed/issues/3982, Here is my traceback with the prints output as well:
```
initialize_distributed_training LOCAL_RANK 2
Available GPUs: 4
CUDA_VISIBLE_DEVICES: 0,1,2,3
WORLD_SIZE: 4
Manually set WORLD_SIZE: 4
Distributed backend initialized. World size: 4, Rank: 2
DeepSpeed configuration file: ./scripts/zero2.json
Expected train_batch_size: 64
DeepSpeed configuration file: ./scripts/zero2.json
Expected train_batch_size: 64
Traceback (most recent call last):
  File "/home/rmendonc/research/dipika/LLaVa2/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "/home/rmendonc/research/dipika/LLaVa2/LLaVA/llava/train/train.py", line 845, in train
    deepspeed_config = deepspeed.runtime.config.DeepSpeedConfig(training_args.deepspeed)
  File "/grogu/user/rmendonc/anaconda2/envs/llava2/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 796, in __init__
    self._configure_train_batch_size()
  File "/grogu/user/rmendonc/anaconda2/envs/llava2/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 979, in _configure_train_batch_size
    self._batch_assertion()
  File "/grogu/user/rmendonc/anaconda2/envs/llava2/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 927, in _batch_assertion
    assert train_batch == micro_batch * grad_acc * self.world_size, (
AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * gradient_acc_step * world_size 64 != 16 * 1 * 1
initialize_distributed_training LOCAL_RANK 3
Available GPUs: 4
CUDA_VISIBLE_DEVICES: 0,1,2,3
WORLD_SIZE: 4
Manually set WORLD_SIZE: 4
initialize_distributed_training LOCAL_RANK 1
Available GPUs: 4
CUDA_VISIBLE_DEVICES: 0,1,2,3
WORLD_SIZE: 4
Manually set WORLD_SIZE: 4
Distributed backend initialized. World size: 4, Rank: 3
DeepSpeed configuration file: ./scripts/zero2.json
Expected train_batch_size: 64
DeepSpeed configuration file: ./scripts/zero2.json
Expected train_batch_size: 64
Traceback (most recent call last):
  File "/home/rmendonc/research/dipika/LLaVa2/LLaVA/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "/home/rmendonc/research/dipika/LLaVa2/LLaVA/llava/train/train.py", line 845, in train
    deepspeed_config = deepspeed.runtime.config.DeepSpeedConfig(training_args.deepspeed)
  File "/grogu/user/rmendonc/anaconda2/envs/llava2/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 796, in __init__
    self._configure_train_batch_size()
  File "/grogu/user/rmendonc/anaconda2/envs/llava2/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 979, in _configure_train_batch_size
    self._batch_assertion()
  File "/grogu/user/rmendonc/anaconda2/envs/llava2/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 927, in _batch_assertion
    assert train_batch == micro_batch * grad_acc * self.world_size, (
AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * gradient_acc_step * world_size 64 != 16 * 1 * 1
```

**Comment by wlh1027** [comment]
这个问题解决了吗，现在我也遇到一样的报错
