### ISSUE TITLE
[Question] "Size mismatch" Error when finetuning from a projector

### ISSUE THREAD

**Issue by hvgupta** [haotian-liu/LLaVA#1619]
### Question

when using the `finetune.sh` bash command I get this error
```
Traceback (most recent call last):
  File "/tmp/code/llava_train/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "/tmp/code/llava_train/llava/train/train.py", line 913, in train
    model.get_model().initialize_vision_modules(
  File "/tmp/code/llava_train/llava/model/llava_arch.py", line 97, in initialize_vision_modules
    self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sequential:
	size mismatch for 0.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([0]).
	size mismatch for 0.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).
	size mismatch for 2.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([0]).
	size mismatch for 2.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).
``` 
How can I solve this?

**Comment by Davidup1** [comment]
use zero2.json may help.

**Comment by shenyichong** [comment]
> use zero2.json may help.

this works for me！but I don't know the reason why? are there anyone who can explain this?

**Comment by hvgupta** [comment]
I got it working without using zero2, for me the images were in the wrong directory.

**Comment by Camellia-hz** [comment]
Hi, I'm guessing this is because zero3 slices and dices the parameters of the model, causing the SIZE to be off.
@shenyichong

**Comment by hehulingxiao** [comment]
Hi, I encounter the same problem, is there some ways to load the checkpoint successfully and finetune the model using zero3?

**Comment by Yinhance** [comment]
> Hi, I encounter the same problem, is there some ways to load the checkpoint successfully and finetune the model using zero3?

Have you solved this problem?

**Comment by Jay-zzcoder** [comment]
> > Hi, I encounter the same problem, is there some ways to load the checkpoint successfully and finetune the model using zero3?
> 
> Have you solved this problem?

Have you solved this problem?
