### ISSUE TITLE
[Usage] Visual instruction tuning for LLaVa 1.6

### ISSUE THREAD

**Issue by mattia-re-learn** [haotian-liu/LLaVA#1630]
### Describe the issue

Issue:

We are trying to finetune the model on our dataset.
Currently, we are able to successfully finetune model `lmsys/vicuna-13b-v1.5`  using projector weights `llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5`.

We would like to leverage the new version of the model and try to finetune it. 
Without using a pretrained projector, the model does not predict anything, I guess because of the small dataset we have.

But trying to use 
--model_name_or_path liuhaotian/llava-v1.6-vicuna-13b
together with `pretrain_mm_mlp_adapter` set to `llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5` is giving error loading the state.

Is there a way to to a visual instruction tuning of LLaVa 1.6?

Command:
```
deepspeed /home/llava/LLaVA/llava/train/train_mem.py \
    --deepspeed /home/llava/LLaVA/scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-v1.6-vicuna-13b \
    --version v1 \
    --data_path /tmp/dataset/conversations.json \
    --image_folder /tmp/dataset/images/ \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --pretrain_mm_mlp_adapter /tmp/checkpoints/mm_projector.bin \
    --image_aspect_ratio pad \
    --group_by_modality_length False \
    --bf16 True \
    --output_dir /tmp/checkpoints/llava-v1.6-13b \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --freeze_backbone \
    --report_to tensorboard
```

Where the projector comes from [https://huggingface.co/liuhaotian/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5/resolve/main/mm_projector.bin](https://huggingface.co/liuhaotian/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5/resolve/main/mm_projector.bin)

Log: 
```
2024-07-24T06:54:38.990825998-04:00 Traceback (most recent call last):
2024-07-24T06:54:38.990849605-04:00   File "/home/llava/LLaVA/llava/train/train_mem.py", line 4, in <module>
2024-07-24T06:54:38.990929643-04:00     train(attn_implementation="flash_attention_2")
2024-07-24T06:54:38.990937186-04:00   File "/home/llava/LLaVA/llava/train/train.py", line 911, in train
2024-07-24T06:54:38.991068208-04:00     model.get_model().initialize_vision_modules(
2024-07-24T06:54:38.991073865-04:00   File "/home/llava/LLaVA/llava/model/llava_arch.py", line 97, in initialize_vision_modules
2024-07-24T06:54:38.991085319-04:00     self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
2024-07-24T06:54:38.991089999-04:00   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
2024-07-24T06:54:38.991553186-04:00     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
2024-07-24T06:54:38.991581612-04:00 RuntimeError: Error(s) in loading state_dict for Sequential:
2024-07-24T06:54:38.991591948-04:00 	size mismatch for 0.weight: copying a param with shape torch.Size([5120, 1024]) from checkpoint, the shape in current model is torch.Size([0]).
2024-07-24T06:54:38.991600469-04:00 	size mismatch for 0.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([0]).
2024-07-24T06:54:38.991608501-04:00 	size mismatch for 2.weight: copying a param with shape torch.Size([5120, 5120]) from checkpoint, the shape in current model is torch.Size([0]).
2024-07-24T06:54:38.991616113-04:00 	size mismatch for 2.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([0]).

2024-07-24T06:54:40.587171362-04:00 [2024-07-24 10:54:40,586] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1794
2024-07-24T06:54:40.587524341-04:00 [2024-07-24 10:54:40,587] [ERROR] [launch.py:321:sigkill_handler] ['/usr/bin/python3', '-u', '/home/llava/LLaVA/llava/train/train_mem.py', '--local_rank=0', '--deepspeed', '/home/llava/LLaVA/scripts/zero3.json', '--model_name_or_path', 'liuhaotian/llava-v1.6-vicuna-13b', '--version', 'v1', '--data_path', '/tmp/dataset/conversations.json', '--image_folder', '/tmp/dataset/images/', '--vision_tower', 'openai/clip-vit-large-patch14-336', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--pretrain_mm_mlp_adapter', '/tmp/checkpoints/mm_projector.bin', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'False', '--bf16', 'True', '--output_dir', '/tmp/checkpoints/llava-v1.6-13b', '--num_train_epochs', '1', '--per_device_train_batch_size', '16', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '50000', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--freeze_backbone', '--report_to', 'tensorboard'] exits 
```

**Comment by Davidup1** [comment]
use zero2.json may help? But I don't know why, do you have any idea?

**Comment by sujoyrc** [comment]
where is the zero2.json file ?

**Comment by Davidup1** [comment]
under directory scripts

**Comment by sujoyrc** [comment]
thanks. where do I pass this file in the run command?  like this ?

```
--pretrain_mm_mlp_adapter zero2.json
```

**Comment by sujoyrc** [comment]
@Davidup1 can you clarify if this is the correct way to run the code with zero2.json

**Comment by dandingsky** [comment]
zero3 provides a wrapper around the model such that when you access its weights they have `torch.Size([0])`. I guess this issue is due to `load_state_dict` after deepspeed engine wraps the model. 
zero2's model wrapper keeps the shape of model weights for `load_state_dict`, so does not have this issue.
Possible workaround: finish loading all pretrained weights before deepspeed engine wraps the model. This is easily achieved using huggingface `accelerate` library, by calling `accelerator.prepare()` after loading all weights. However, I am not sure how to do so with deepspeed only.

**Comment by linzangsc** [comment]
> zero3 provides a wrapper around the model such that when you access its weights they have `torch.Size([0])`. I guess this issue is due to `load_state_dict` after deepspeed engine wraps the model. zero2's model wrapper keeps the shape of model weights for `load_state_dict`, so does not have this issue. Possible workaround: finish loading all pretrained weights before deepspeed engine wraps the model. This is easily achieved using huggingface `accelerate` library, by calling `accelerator.prepare()` after loading all weights. However, I am not sure how to do so with deepspeed only.

great help! thanks!
