### ISSUE TITLE
[Usage] KeyError: 'LlavaMistralConfig' when I start a model-worker with a fine-tuned Llava-v1.6-mistral-7B model.

### ISSUE THREAD

**Issue by yunsaijc** [haotian-liu/LLaVA#1639]
### Describe the issue

Issue: When I try to start a model-worker with a fine-tuned Llava-v1.6-mistral-7B model, I get: KeyError: 'LlavaMistralConfig'.

Command:
```
python -m llava.serve.model_worker \
             --host 0.0.0.0 \
             --controller http://localhost:10000 \
             --port 40000 \
             --worker http://localhost:40000 \
             --model-path ./llava-v1.6-mistral-7b \
             --model-base ./checkpoints/llava-v1.6-mistral-7b-task-lora # this is the fine-tuned weights of my own
```

Log: 
```
2024-07-31 16:02:25 | INFO | model_worker | Loading the model llava-v1.6-mistral-7b on worker cc01df ...
2024-07-31 16:02:25 | INFO | stdout | Loading LLaVA from base model...
2024-07-31 16:02:25 | ERROR | stderr | Traceback (most recent call last):
2024-07-31 16:02:25 | ERROR | stderr |   File "/home/jc/app/anaconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-07-31 16:02:25 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-07-31 16:02:25 | ERROR | stderr |   File "/home/jc/app/anaconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
2024-07-31 16:02:25 | ERROR | stderr |     exec(code, run_globals)
2024-07-31 16:02:25 | ERROR | stderr |   File "/home/jc/workspace/LLaVA/llava/serve/model_worker.py", line 277, in <module>
2024-07-31 16:02:25 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-07-31 16:02:25 | ERROR | stderr |   File "/home/jc/workspace/LLaVA/llava/serve/model_worker.py", line 65, in __init__
2024-07-31 16:02:25 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2024-07-31 16:02:25 | ERROR | stderr |   File "/home/jc/workspace/LLaVA/llava/model/builder.py", line 97, in load_pretrained_model
2024-07-31 16:02:25 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(model_base, use_fast=False)
2024-07-31 16:02:25 | ERROR | stderr |   File "/home/jc/app/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 830, in from_pretrained
2024-07-31 16:02:25 | ERROR | stderr |     tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
2024-07-31 16:02:25 | ERROR | stderr |   File "/home/jc/app/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 737, in __getitem__
2024-07-31 16:02:25 | ERROR | stderr |     model_type = self._reverse_config_mapping[key.__name__]
2024-07-31 16:02:25 | ERROR | stderr | KeyError: 'LlavaMistralConfig'
```

**Comment by bxdgfw** [comment]
hello，have you solved it and how did you solve it?

**Comment by yunsaijc** [comment]
> hello，have you solved it and how did you solve it?

Hello, I have solved this issue by merging the lora module and the base model. (Using scripts/merge_lora_weights.py)
