### ISSUE TITLE
[Usage] Error - `ollama._types.ResponseError: error parsing llm response stream: error: {"content":"internal_error"}`

### ISSUE THREAD

**Issue by laksh-2193** [haotian-liu/LLaVA#1666]
### Describe the issue

Code : 
```
import ollama


prompt = "What all finanicial data is there in this pdf?"
image = "bank statement.pdf"

result = ollama.generate(
        model='llava',
        prompt=prompt,
        images=[image],
    )

print(result)
```

Logs : 
```
python main.py 
Traceback (most recent call last):
  File "/home/ubuntu/llava-demo/main.py", line 7, in <module>
    result = ollama.generate(
             ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/fastapi/env/lib/python3.12/site-packages/ollama/_client.py", line 162, in generate
    return self._request_stream(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/fastapi/env/lib/python3.12/site-packages/ollama/_client.py", line 98, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/fastapi/env/lib/python3.12/site-packages/ollama/_client.py", line 74, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: error parsing llm response stream: error: {"content":"internal_error"}
```

**Comment by SouravBeraAkaSpeed** [comment]
I'm also getting the same issue

**Comment by netojoa** [comment]
Had the same issue. I was also trying to send a PDF file. I believe it is not supported, you must convert it to an image before. After I converted the PDF to JPEG, it worked.

**Comment by stajilov** [comment]
yes, with image it works fine... need to plug in additional service then
