### ISSUE TITLE
[Usage] Encountered an issue while installing the environment with 'pip install flash-attn --no-build-isolation“

### ISSUE THREAD

**Issue by freya-7** [haotian-liu/LLaVA#1740]
### Describe the issue

Issue:“pip install flash-attn --no-build-isolation”
“Collecting flash-attn
  Using cached flash_attn-2.6.3.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-e17h729i/flash-attn_04e1e09780f64807ac90bf9b6ff6b492/setup.py", line 21, in <module>
          import torch
        File "/home/me/enter/envs/llava/lib/python3.10/site-packages/torch/__init__.py", line 235, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /home/me/enter/envs/llava/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
”
Command:
```
PASTE THE COMMANDS HERE.
```

Log: 
```
PASTE THE LOGS HERE.
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by hotpot-killer** [comment]
same question
