### ISSUE TITLE
[Question] 打开网页后显示：error Could not parse server response: SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON

### ISSUE THREAD

**Issue by BinTangHuLu** [haotian-liu/LLaVA#1744]
### Question

gradio_web_server显示：
python -m llava.serve.gradio_web_server --controller http://localhost:10001 --model-list-mode reload                                                         
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
2024-10-22 14:46:23 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10001', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-10-22 14:46:32 | INFO | gradio_web_server | Models: []
2024-10-22 14:46:32 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10001', concurrency_count=16, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-10-22 14:46:32 | ERROR | stderr | E:\Anaconda\envs\llava\lib\site-packages\gradio\components\dropdown.py:163: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
2024-10-22 14:46:32 | ERROR | stderr |   warnings.warn(
2024-10-22 14:46:32 | INFO | stdout | Running on local URL:  http://0.0.0.0:7860
2024-10-22 14:46:32 | INFO | httpx | HTTP Request: GET http://localhost:7860/startup-events "HTTP/1.1 200 OK"
2024-10-22 14:46:32 | INFO | httpx | HTTP Request: HEAD http://localhost:7860/ "HTTP/1.1 200 OK"
2024-10-22 14:46:32 | INFO | stdout | 
2024-10-22 14:46:32 | INFO | stdout | To create a public link, set `share=True` in `launch()`.
2024-10-22 14:46:33 | INFO | httpx | HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
2024-10-22 14:46:33 | INFO | httpx | HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
2024-10-22 14:46:33 | INFO | stdout | IMPORTANT: You are using gradio version 4.16.0, however version 4.44.1 is available, please upgrade.
2024-10-22 14:46:33 | INFO | stdout | --------
2024-10-22 14:46:33 | INFO | httpx | HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
2024-10-22 14:46:34 | INFO | httpx | HTTP Request: POST https://api.gradio.app/gradio-initiated-analytics/ "HTTP/1.1 200 OK"
2024-10-22 14:46:35 | INFO | httpx | HTTP Request: POST https://api.gradio.app/gradio-launched-telemetry/ "HTTP/1.1 200 OK"
2024-10-22 14:50:10 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-10-22 14:50:10 | ERROR | stderr | Traceback (most recent call last):
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
2024-10-22 14:50:10 | ERROR | stderr |     self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
2024-10-22 14:50:10 | ERROR | stderr |     raise AttributeError(attribute)
2024-10-22 14:50:10 | ERROR | stderr | AttributeError: __pydantic_core_schema__
2024-10-22 14:50:10 | ERROR | stderr |
2024-10-22 14:50:10 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-10-22 14:50:10 | ERROR | stderr |
2024-10-22 14:50:10 | ERROR | stderr | Traceback (most recent call last):
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
2024-10-22 14:50:10 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\applications.py", line 113, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     raise exc
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     await self.simple_response(scope, receive, send, request_headers=headers)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
2024-10-22 14:50:10 | ERROR | stderr |     await self.app(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
2024-10-22 14:50:10 | ERROR | stderr |     raise exc
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
2024-10-22 14:50:10 | ERROR | stderr |     await app(scope, receive, sender)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\routing.py", line 715, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\routing.py", line 735, in app
2024-10-22 14:50:10 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\routing.py", line 288, in handle
2024-10-22 14:50:10 | ERROR | stderr |     await self.app(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\routing.py", line 76, in app
2024-10-22 14:50:10 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
2024-10-22 14:50:10 | ERROR | stderr |     raise exc
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
2024-10-22 14:50:10 | ERROR | stderr |     await app(scope, receive, sender)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\starlette\routing.py", line 73, in app
2024-10-22 14:50:10 | ERROR | stderr |     response = await f(request)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\fastapi\routing.py", line 291, in app
2024-10-22 14:50:10 | ERROR | stderr |     solved_result = await solve_dependencies(
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\fastapi\dependencies\utils.py", line 658, in solve_dependencies
2024-10-22 14:50:10 | ERROR | stderr |     ) = await request_body_to_args(  # body_params checked above
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\fastapi\dependencies\utils.py", line 883, in request_body_to_args
2024-10-22 14:50:10 | ERROR | stderr |     fields_to_extract = get_cached_model_fields(first_field.type_)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\fastapi\_compat.py", line 658, in get_cached_model_fields
2024-10-22 14:50:10 | ERROR | stderr |     return get_model_fields(model)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\fastapi\_compat.py", line 284, in get_model_fields
2024-10-22 14:50:10 | ERROR | stderr |     return [
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\fastapi\_compat.py", line 285, in <listcomp>
2024-10-22 14:50:10 | ERROR | stderr |     ModelField(field_info=field_info, name=name)
2024-10-22 14:50:10 | ERROR | stderr |   File "<string>", line 6, in __init__
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\fastapi\_compat.py", line 110, in __post_init__
2024-10-22 14:50:10 | ERROR | stderr |     self._type_adapter: TypeAdapter[Any] = TypeAdapter(
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
2024-10-22 14:50:10 | ERROR | stderr |     self._init_core_attrs(rebuild_mocks=False)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
2024-10-22 14:50:10 | ERROR | stderr |     return func(self, *args, **kwargs)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
2024-10-22 14:50:10 | ERROR | stderr |     self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
2024-10-22 14:50:10 | ERROR | stderr |     schema = gen.generate_schema(type_)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
2024-10-22 14:50:10 | ERROR | stderr |     schema = self._generate_schema_inner(obj)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
2024-10-22 14:50:10 | ERROR | stderr |     return self._annotated_schema(obj)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema
2024-10-22 14:50:10 | ERROR | stderr |     schema = self._apply_annotations(source_type, annotations)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations
2024-10-22 14:50:10 | ERROR | stderr |     schema = get_inner_schema(source_type)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     schema = self._handler(source_type)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler
2024-10-22 14:50:10 | ERROR | stderr |     schema = metadata_get_schema(source, get_inner_schema)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>
2024-10-22 14:50:10 | ERROR | stderr |     lambda source, handler: handler(source)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
2024-10-22 14:50:10 | ERROR | stderr |     schema = self._handler(source_type)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler
2024-10-22 14:50:10 | ERROR | stderr |     schema = self._generate_schema_inner(obj)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
2024-10-22 14:50:10 | ERROR | stderr |     return self.match_type(obj)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
2024-10-22 14:50:10 | ERROR | stderr |     return self._match_generic_type(obj, origin)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
2024-10-22 14:50:10 | ERROR | stderr |     return self._union_schema(obj)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
2024-10-22 14:50:10 | ERROR | stderr |     choices.append(self.generate_schema(arg))
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
2024-10-22 14:50:10 | ERROR | stderr |     schema = self._generate_schema_inner(obj)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
2024-10-22 14:50:10 | ERROR | stderr |     return self.match_type(obj)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
2024-10-22 14:50:10 | ERROR | stderr |     return self._unknown_type_schema(obj)
2024-10-22 14:50:10 | ERROR | stderr |   File "E:\Anaconda\envs\llava\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
2024-10-22 14:50:10 | ERROR | stderr |     raise PydanticSchemaGenerationError(
2024-10-22 14:50:10 | ERROR | stderr | pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
2024-10-22 14:50:10 | ERROR | stderr |
2024-10-22 14:50:10 | ERROR | stderr | If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
2024-10-22 14:50:10 | ERROR | stderr |
2024-10-22 14:50:10 | ERROR | stderr | For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

**Comment by YixFeng** [comment]
I met the same error. How did you fix it out?

**Comment by trinn22** [comment]
This worked for me
(mi_env) fv@fv01:~/LLaVA$ pip install gradio -U

**Comment by ErwinCheung** [comment]
> This worked for me (mi_env) fv@fv01:~/LLaVA$ pip install gradio -U

Thank you very much. I have been working on this issue for a long time, but when I saw your solution, I upgraded Gradio and it was immediately resolved.
