### ISSUE TITLE
[Question] Having an issue using the merge weights script.

### ISSUE THREAD

**Issue by Silverasdf** [haotian-liu/LLaVA#1745]
### Question

Hello,

So I've fine-tuned a model using the `finetune-lora.sh` script and I ended up getting an error. Is there anyway I can fix this?

From the looks of it, the Traceback is from a python library rather than the code I could try modifying, but I figured it would be worth asking anyways.

I want to go ahead and [link](https://github.com/haotian-liu/LLaVA/issues/1726) the previous issue I made for any missing context here.

Thanks!

```py
Traceback (most recent call last):
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 558, in save_pretrained
    raise ValueError(str([w.message for w in caught_warnings]))
ValueError: [UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.'), UserWarning('`do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rdpperuski/LLaVA/scripts/merge_lora_weights.py", line 22, in <module>
    merge_lora(args)
  File "/home/rdpperuski/LLaVA/scripts/merge_lora_weights.py", line 10, in merge_lora
    model.save_pretrained(args.save_model_path)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2364, in save_pretrained
    model_to_save.generation_config.save_pretrained(save_directory)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 560, in save_pretrained
    raise ValueError(
ValueError: The generation config instance is invalid -- `.validate()` throws warnings and/or exceptions. Fix these issues to save the configuration.

Thrown during validation:
[UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.'), UserWarning('`do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.')]```

**Comment by shadowdyj** [comment]
@Silverasdf same issue. do you solve it?

**Comment by shadowdyj** [comment]
> #1635 
it works.

**Comment by Silverasdf** [comment]
No, I'm still having an issue with it.

![image](https://github.com/user-attachments/assets/b35a1954-797a-4923-9d8c-1365079225b1)

I changed the code however, and I still get the same issue:

```py
Model is loaded...
Traceback (most recent call last):
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 558, in save_pretrained
    raise ValueError(str([w.message for w in caught_warnings]))
ValueError: [UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.'), UserWarning('`do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rdpperuski/LLaVA/scripts/merge_lora_weights.py", line 22, in <module>
    merge_lora(args)
  File "/home/rdpperuski/LLaVA/scripts/merge_lora_weights.py", line 10, in merge_lora
    model.save_pretrained(args.save_model_path)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2364, in save_pretrained
    model_to_save.generation_config.save_pretrained(save_directory)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 560, in save_pretrained
    raise ValueError(
ValueError: The generation config instance is invalid -- `.validate()` throws warnings and/or exceptions. Fix these issues to save the configuration.

Thrown during validation:
[UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.'), UserWarning('`do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.')]```

**Comment by YUECHE77** [comment]
You can try to downgrade transformers to 4.36.2, this should solve the issue.

But even successfully merge the lora weights with the base model, I still cannot run CLI with merged model.

**Comment by xiaomatiaobugao** [comment]
@YUECHE77 hello,I wanna know the basic model you mentioned, is the basic moedel like llava-v1.5-13b/7b，or vicuna-13b-v1.5.plz

**Comment by Silverasdf** [comment]
Oh, good point. I’m using llava-1.5-7b in this instance.
