### ISSUE TITLE
Invalidate trace cache @ step 4: expected module 458, but got module 466

### ISSUE THREAD

**Issue by waybarrios** [haotian-liu/LLaVA#1749]
### Describe the issue

Issue:
I am getting this error when I am running the finetune process and `zero3.json`

Command:
```
bash llava/script/finetune.sh
```

Log: 
```
{'loss': 10.6907, 'grad_norm': 119.82210773358251, 'learning_rate': 4.5850527281063734e-09, 'epoch': 0.0}              
{'loss': 11.1586, 'grad_norm': 100.0709938853891, 'learning_rate': 9.170105456212747e-09, 'epoch': 0.0}                
{'loss': 11.0917, 'grad_norm': 107.5783807489403, 'learning_rate': 1.3755158184319121e-08, 'epoch': 0.0}               
  0%|                                                                           | 3/145374 [00:14<168:23:32,  4.17s/it]
Invalidate trace cache @ step 4: expected module 458, but got module 466
^C[2024-10-29 01:28:46,598] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 489270
^CTraceback (most recent call last):
  File "/scratch/miniconda3/envs/cvpr/lib/python3.12/subprocess.py", line 1264, in wait
[2024-10-29 01:28:46,742] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 489270
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/miniconda3/envs/cvpr/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/scratch/miniconda3/envs/cvpr/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

```

Any suggestion?

**Comment by Confetti-lxy** [comment]
Hello, have you solved this problem?

**Comment by youngwanLEE** [comment]
+1

**Comment by keanshi-nlp** [comment]
+ 1, have you got any solutions?

**Comment by Confetti-lxy** [comment]
@keanshi-nlp This problem occurs only when I use the A6000 for training, but not when I use the A800. Besides, I think that this was not a fatal bug; it was re-caching and should only affect training speed.

**Comment by keanshi-nlp** [comment]
> [@keanshi-nlp](https://github.com/keanshi-nlp) This problem occurs only when I use the A6000 for training, but not when I use the A800. Besides, I think that this was not a fatal bug; it was re-caching and should only affect training speed.

Thanks!
