### ISSUE TITLE
[Usage] fine-tuning raises error at "assert num_new_tokens == 2"

### ISSUE THREAD

**Issue by alpayariyak** [haotian-liu/LLaVA#180]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:

I am trying to fine-tune on a custom dataset. When running the script, I get this error:

```
Traceback (most recent call last):
  File "llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/aariyak/gradelight/LLaVA_finetuning/LLaVA_code/LLaVA/llava/train/train.py", line 632, in train
    model.initialize_vision_tokenizer(mm_use_im_start_end=model_args.mm_use_im_start_end, tokenizer=tokenizer, device=training_args.device,
  File "/home/aariyak/gradelight/LLaVA_finetuning/LLaVA_code/LLaVA/llava/model/llava.py", line 319, in initialize_vision_tokenizer
    assert num_new_tokens == 2
AssertionError
```

Also, is this correct? I made a custom dataset of images of different sizes with conversations and formatted everything the same as LLaVA-instruct-150k.json. I didn't touch most of the parameters.
Command:
```
torchrun --nnodes=1 --nproc_per_node=1 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path LLaVA-7B-base \
    --data_path /home/aariyak/gradelight/LLaVA_finetuning/LLaVA_code/data/IAM_LLAVA.json \
    --image_folder /home/aariyak/gradelight/LLaVA_finetuning/LLaVA_code/data/images \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter projector/llava-7b-pretrain.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir ./checkpoints \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to wandb 
```

**Comment by alpayariyak** [comment]
Fixed using solution described in #110
