### ISSUE TITLE
使用finetune_task_lora.sh微调llava_1.5模型无法运行

### ISSUE THREAD

**Issue by zhangye0402** [haotian-liu/LLaVA#1811]
<img width="995" alt="image" src="https://github.com/user-attachments/assets/db62243b-2303-496f-b0b6-d8b3686c363d" />

报错信息如图，问题：第一轮训练显示loss为0后直接结束训练 我的环境如下：
<img width="173" alt="image" src="https://github.com/user-attachments/assets/d6c5c70e-762e-4c2f-a505-15ab63ad2463" />
<img width="170" alt="image" src="https://github.com/user-attachments/assets/cbe93209-2566-42c2-a909-0d8c5adc985d" />
<img width="155" alt="image" src="https://github.com/user-attachments/assets/976daa4f-067c-41b2-a518-78e96cb037ec" />

训练脚本如下：
<img width="443" alt="image" src="https://github.com/user-attachments/assets/931e354e-328e-4e81-8fdb-01813ffdad9d" />

我曾经用这个脚本正确运行过训练程序，但是在重新配置环境后出现了这样的错误，请问是哪里出错了呢，谢谢大家！

**Comment by MarkDeng1** [comment]
我的微调 从HF下载的模型总是报错，说结构不匹配。。
Traceback (most recent call last):
  File "/fred/oz337/zdeng/prompt_stealing_ours/LLaVA/llava/train/train.py", line 1006, in <module>
    train()
  File "/fred/oz337/zdeng/prompt_stealing_ours/LLaVA/llava/train/train.py", line 834, in train
    model = LlavaMptForCausalLM.from_pretrained(
  File "/fred/oz337/zdeng/.conda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3850, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/fred/oz337/zdeng/.conda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4146, in _load_pretrained_model
    raise ValueError(
ValueError: The state dictionary of the model you are trying to load is corrupted. Are you sure it was properly saved?
