### ISSUE TITLE
Unable to run the code. [Question] 

### ISSUE THREAD

**Issue by jaydeep-work** [haotian-liu/LLaVA#196]
### Question

here is the terminal error...

```
(env) root@4acd6379ec91:/workspace/reverse_prompting/LLaVA# torchrun --nnodes=1 --nproc_per_node=1 --master_port=25001     llava/train/train_mem.py     --model_name_or_path /workspace/reverse_prompting/LLaVA/LLaVA-7B-v0     --data_path /workspace/reverse_prompting/LLaVA/small_data/chat.json     --image_folder /workspace/reverse_prompting/LLaVA/small_data/images     --vision_tower openai/clip-vit-large-patch14     --tune_mm_mlp_adapter True     --mm_vision_select_layer -2     --bf16 True     --output_dir /workspace/reverse_prompting/LLaVA/checkpoints/llava-13b-pretrain-no_im_start_end_token     --num_train_epochs 1     --per_device_train_batch_size 16     --per_device_eval_batch_size 4     --gradient_accumulation_steps 1     --evaluation_strategy "no"     --save_strategy "steps"     --save_steps 2400     --save_total_limit 1     --learning_rate 2e-3     --weight_decay 0.     --warmup_ratio 0.03     --lr_scheduler_type "cosine"     --logging_steps 1     --tf32 True     --model_max_length 2048     --gradient_checkpointing True     --lazy_preprocess True     --report_to wandb
You are using a model of type llava to instantiate a model of type llava_mpt. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/workspace/reverse_prompting/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/workspace/reverse_prompting/LLaVA/llava/train/train.py", line 545, in train
    model = LlavaMPTForCausalLM.from_pretrained(
  File "/workspace/reverse_prompting/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2493, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/workspace/reverse_prompting/LLaVA/llava/model/llava_mpt.py", line 182, in __init__
    raise ValueError('MPTForCausalLM only supports tied word embeddings')
ValueError: MPTForCausalLM only supports tied word embeddings
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2050) of binary: /workspace/reverse_prompting/env/bin/python
Traceback (most recent call last):
  File "/workspace/reverse_prompting/env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/workspace/reverse_prompting/env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/workspace/reverse_prompting/env/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/workspace/reverse_prompting/env/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/workspace/reverse_prompting/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/reverse_prompting/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
llava/train/train_mem.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-25_11:18:26
  host      : 4acd6379ec91
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2050)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

Transformer version i'm using
`transformers @ git+https://github.com/huggingface/transformers.git@cae78c46d658a8e496a815c2ee49b9b178fb9c9a`

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

```
nvidia-smi
Thu May 25 11:23:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100 80G...  Off  | 00000000:05:00.0 Off |                    0 |
| N/A   49C    P0    71W / 300W |      0MiB / 81920MiB |     21%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by haotian-liu** [comment]
Hmm, it seems that `mpt` in /workspace/reverse_pro**mpt**ing/LLaVA/LLaVA-7B-v0 makes the code think that this is a LLaVA-MPT model.  Currently, you may temporarily change the name of the folder, or you can force the model not to load as a LLaVA-MPT model.

I will push a fix to these naming issues later this month, thanks.
