### ISSUE TITLE
[Usage] ImportError: cannot import name 'mkdir_exists_ok' from 'wandb.sdk.lib.filesystem' (/usr/local/lib/python3.9/dist-packages/wandb/sdk/lib/filesystem.py)

### ISSUE THREAD

**Issue by LetsGoFir** [haotian-liu/LLaVA#223]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:

Command:
```
torchrun --nnodes=1 --nproc_per_node=4 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path /path/llama-vicuna-13b \
    --data_path /path/LLaVA-CC3M-Pretrain-595K/chat.json \
    --image_folder /path/LLaVA-CC3M-Pretrain-595K/images \
    --vision_tower openai/clip-vit-large-patch14 \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end \
    --bf16 True \
    --output_dir /path/llava_checkpoints \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2400 \
    --save_total_limit 1 \
    --learning_rate 2e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to none
```

Log: 
```
Traceback (most recent call last):
  File "/opt/tiger/LLaVA/llava/train/train_mem.py", line 6, in <module>
    from accelerate import __version__ as accelerate_version
  File "/usr/local/lib/python3.9/dist-packages/accelerate/__init__.py", line 3, in <module>
    from llava.train.llama_flash_attn_monkey_patch import replace_llama_attn_with_flash_attn
  File "/opt/tiger/LLaVA/llava/__init__.py", line 1, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.9/dist-packages/accelerate/accelerator.py", line 39, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/opt/tiger/LLaVA/llava/model/__init__.py", line 1, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
      File "/usr/local/lib/python3.9/dist-packages/accelerate/tracking.py", line 49, in <module>
from .llava import LlavaLlamaForCausalLM, LlavaConfig
  File "/opt/tiger/LLaVA/llava/model/llava.py", line 23, in <module>
    import wandb    
from transformers import AutoConfig, AutoModelForCausalLM, \  File "/usr/local/lib/python3.9/dist-packages/wandb/__init__.py", line 34, in <module>

  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
    from wandb import sdk as wandb_sdk  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/import_utils.py", line 1137, in __getattr__

  File "/usr/local/lib/python3.9/dist-packages/wandb/sdk/__init__.py", line 7, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/wandb/sdk/wandb_artifacts.py", line 31, in <module>
    import wandb.data_types as data_types
  File "/usr/local/lib/python3.9/dist-packages/wandb/data_types.py", line 47, in <module>
    from .sdk.data_types.saved_model import _SavedModel
  File "/usr/local/lib/python3.9/dist-packages/wandb/sdk/data_types/saved_model.py", line 19, in <module>
    from wandb.sdk.interface.artifacts import b64_string_to_hex, md5_files_b64
  File "/usr/local/lib/python3.9/dist-packages/wandb/sdk/interface/artifacts/__init__.py", line 7, in <module>
    from wandb.sdk.interface.artifacts.artifact_cache import (
  File "/usr/local/lib/python3.9/dist-packages/wandb/sdk/interface/artifacts/artifact_cache.py", line 9, in <module>
    value = getattr(module, name)
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/import_utils.py", line 1136, in __getattr__
    from wandb.sdk.lib.filesystem import mkdir_exists_ok
ImportError: cannot import name 'mkdir_exists_ok' from 'wandb.sdk.lib.filesystem' (/usr/local/lib/python3.9/dist-packages/wandb/sdk/lib/filesystem.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/tiger/LLaVA/llava/train/train_mem.py", line 6, in <module>
    from llava.train.llama_flash_attn_monkey_patch import replace_llama_attn_with_flash_attn
  File "/opt/tiger/LLaVA/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/opt/tiger/LLaVA/llava/model/__init__.py", line 1, in <module>
    from .llava import LlavaLlamaForCausalLM, LlavaConfig
  File "/opt/tiger/LLaVA/llava/model/llava.py", line 23, in <module>
    from transformers import AutoConfig, AutoModelForCausalLM, \
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/import_utils.py", line 1148, in _get_module
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/import_utils.py", line 1137, in __getattr__
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
cannot import name 'mkdir_exists_ok' from 'wandb.sdk.lib.filesystem' (/usr/local/lib/python3.9/dist-packages/wandb/sdk/lib/filesystem.py)
    value = getattr(module, name)
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/import_utils.py", line 1136, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/import_utils.py", line 1148, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
```

**Comment by LetsGoFir** [comment]
reinstall fix it
