### ISSUE TITLE
Training the MPT model

### ISSUE THREAD

**Issue by taesiri** [haotian-liu/LLaVA#240]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:

First of all, thanks for this amazing project. I am trying to train the MPT variant of the LLaVA model but I encounter some issues. Using the provided training script, I am getting ``LlavaMPTModel.initialize_vision_modules() got an unexpected keyword argument 'fsdp'`` error message. According to [this line](https://github.com/haotian-liu/LLaVA/blob/fee35939829370eef8371a553c57c3b3b4bdeed9/llava/model/llava_mpt.py#L58) the `initialize_vision_modules` is not expecting any `fsdp` arguments. 

I tried to manually remove this argument, but in that case, I am getting an error regarding the absence of ``get_vision_tower()`` in the `LlavaMPTForCausalLM` class: ``AttributeError: 'LlavaMPTForCausalLM' object has no attribute 'get_vision_tower'``

Command:

Using the training script from [here](https://github.com/haotian-liu/LLaVA/blob/main/scripts/train_lightning_mpt.sh), modified according to number of GPUs

```
# Pretraining 
torchrun --nnodes=1 --nproc_per_node=1 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path mosaicml/mpt-7b-chat \
    --version v1 \
    --data_path /path/to/blip_laion_cc_sbu_558k.json \
    --image_folder /path/to/blip_laion_cc_sbu_558k \
    --vision_tower openai/clip-vit-large-patch14 \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end \
    --bf16 True \
    --output_dir ./checkpoints/llava-lightning-mpt-7b-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2400 \
    --save_total_limit 1 \
    --learning_rate 2e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb```

```

Log: 

```


Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.51s/it]
Traceback (most recent call last):
  File "/home/jupyter-mrtaesiri/SFT/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/jupyter-mrtaesiri/SFT/LLaVA/llava/train/train.py", line 739, in train
    model_vision_dict = model.get_model().initialize_vision_modules(
TypeError: LlavaMPTModel.initialize_vision_modules() got an unexpected keyword argument 'fsdp'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 305131) of binary: /home/jupyter-mrtaesiri/miniconda3/envs/llava/bin/python
Traceback (most recent call last):
  File "/home/jupyter-mrtaesiri/miniconda3/envs/llava/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jupyter-mrtaesiri/miniconda3/envs/llava/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/jupyter-mrtaesiri/miniconda3/envs/llava/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/jupyter-mrtaesiri/miniconda3/envs/llava/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/jupyter-mrtaesiri/miniconda3/envs/llava/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jupyter-mrtaesiri/miniconda3/envs/llava/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

```

**Comment by taesiri** [comment]
I should also add that I already trained the LLaMA-based model without facing this issue.

**Comment by findalexli** [comment]
I am facing the same issue. Please help!

**Comment by kahnchana** [comment]
Copying the necessary function and lines from `llava.py` to `llava_mpt.py` fixes this issue for me (quick fix). 

![image](https://github.com/haotian-liu/LLaVA/assets/17735127/e1ef7601-f5b5-4b63-8f6e-36db29517576)
![image](https://github.com/haotian-liu/LLaVA/assets/17735127/9da754b5-8538-4f7e-971a-b512441a59cb)

**Comment by taesiri** [comment]
@kahnchana Could you make a pull request or share your fork?

**Comment by haotian-liu** [comment]
Apologies for the confusion. The latest code base has fixed the related issues regarding the MPT model training. Please try checking out the latest code base, thanks!
