### ISSUE TITLE
[Usage] apply_delta.py  error

### ISSUE THREAD

**Issue by mijunhua** [haotian-liu/LLaVA#246]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

Command:
```
python3 -m llava.model.apply_delta \
    --base /home/projects/LLaVA/weights/llama-7b-hf \
    --target /home/projects/LLaVA/weights/LLaVA-7B-v0 \
    --delta /home/projects/LLaVA/weights/LLaVA-7b-delta-v0
```

Log: 
```
Loading base model
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:09<00:00,  3.53it/s]
Loading delta
You are using a model of type llama to instantiate a model of type llava. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/home/projects/LLaVA/transformers/src/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/xxy/miniconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/xxy/miniconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxy/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxy/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxy/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/xxy/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/xxy/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/xxy/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/xxy/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/xxy/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/xxy/docker/projects/LLaVA/llava/model/apply_delta.py", line 53, in <module>
    apply_delta(args.base_model_path, args.target_model_path, args.delta_path)
  File "/home/xxy/docker/projects/LLaVA/llava/model/apply_delta.py", line 19, in apply_delta
    delta = LlavaLlamaForCausalLM.from_pretrained(delta_path, torch_dtype=torch.float16, low_cpu_mem_usage=True)
  File "/home/xxy/docker/projects/LLaVA/transformers/src/transformers/modeling_utils.py", line 2493, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/xxy/docker/projects/LLaVA/llava/model/llava.py", line 201, in __init__
    self.model = LlavaLlamaModel(config)
  File "/home/xxy/docker/projects/LLaVA/llava/model/llava.py", line 48, in __init__
    self.vision_tower = [CLIPVisionModel.from_pretrained(config.mm_vision_tower)]
  File "/home/xxy/docker/projects/LLaVA/transformers/src/transformers/modeling_utils.py", line 2170, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/xxy/docker/projects/LLaVA/transformers/src/transformers/models/clip/configuration_clip.py", line 233, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/xxy/docker/projects/LLaVA/transformers/src/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/xxy/docker/projects/LLaVA/transformers/src/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/xxy/docker/projects/LLaVA/transformers/src/transformers/utils/hub.py", line 443, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
If you cannot connect to HF, you may download LLaVA-7b-delta-v0 and CLIP repo locally and change the directory accordingly. Thanks.

**Comment by mijunhua** [comment]
> If you cannot connect to HF, you may download LLaVA-7b-delta-v0 and CLIP repo locally and change the directory accordingly. Thanks.

Thank you for your reply. I have manually downloaded the openai/clip-vit-large-patch14 model repository, but I’m not sure where to place it in the file directory.  Can you give some suggestions?    thanks

**Comment by mijunhua** [comment]
resolved
