### ISSUE TITLE
NameError: name 'document' is not defined

### ISSUE THREAD

**Issue by mijunhua** [haotian-liu/LLaVA#261]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue: NameError: name 'document' is not defined

Command:

python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload

Log: 
Traceback (most recent call last):
  File "/home/tmp/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tmp/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tmp/docker/projects/LLaVA/llava/serve/gradio_web_server.py", line 16, in <module>
    from llava.serve.gradio_patch import Chatbot as grChatbot
  File "/home/tmp/docker/projects/LLaVA/llava/serve/gradio_patch.py", line 17, in <module>
    @document("style")
NameError: name 'document' is not defined

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
Hi, can you try pulling the latest code base and run `pip install -e .` again?  I just updated the Gradio related code and remove the dependency of these. Thanks.
