### ISSUE TITLE
[Usage] Error when trying to run lightening MPT model inference 

### ISSUE THREAD

**Issue by kahnchana** [haotian-liu/LLaVA#267]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:
Error when trying to run lightening MPT model inference. It seems that some of the model weights turn into NaNs when loading. 

Command:
```
python -m llava.eval.run_llava \
    --model-name "liuhaotian/LLaVA-Lightning-MPT-7B-preview" \
    --image-file "llava/serve/examples/extreme_ironing.jpg" \
    --query "What is unusual about this image?"
```

Log: 
```
Traceback (most recent call last):
  File "/data/home/kanchana/miniconda3/envs/llava1/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/home/kanchana/miniconda3/envs/llava1/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/home/kanchana/repo/LLaVA/llava/eval/run_llava.py", line 125, in <module>
    eval_model(args)
  File "/data/home/kanchana/repo/LLaVA/llava/eval/run_llava.py", line 98, in eval_model
    output_ids = model.generate(
  File "/data/home/kanchana/miniconda3/envs/llava1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/kanchana/miniconda3/envs/llava1/lib/python3.10/site-packages/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/data/home/kanchana/miniconda3/envs/llava1/lib/python3.10/site-packages/transformers/generation/utils.py", line 2514, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
Hi, thank you for your interest and apologies for this. We have updated the code base and fixed the related issues regarding MPT inference. Please pull the latest code base and try again. Thanks!
