### ISSUE TITLE
[Usage] Error occurs on WebServer startup: "Exception in ASGI application"

### ISSUE THREAD

**Issue by kznrluk** [haotian-liu/LLaVA#286]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:

In my environment (Arch Linux and Windows 11), when I start the Web server and access it from the browser, I encounter the following error. As a result, the chat window doesn't display, and I cannot use it properly.

To address this issue, I manually installed `gradio_client` based on information found online, and now it works fine. Perhaps the definition in `pyproject.toml` might be incomplete.

```
pip install gradio_client==0.2.7
```

I also tried both the latest commit `6cea223` and the commit before Release v1.0.0 `7ace501`, but encountered the same error.

Command:
```
python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload --port 7862
```
Log: 
```
python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload --port 7862
[2023-07-21 13:29:47,707] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-07-21 13:29:48 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=7862, controller_url='http://localhost:10000', concurrency_count=8, model_list_mode='reload', share=False, moderate=False, embed=False)
2023-07-21 13:29:48 | INFO | gradio_web_server | Models: ['LLaVa-7B-v0']
2023-07-21 13:29:48 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=7862, controller_url='http://localhost:10000', concurrency_count=8, model_list_mode='reload', share=False, moderate=False, embed=False)
channel 3: open failed: connect failed: Connection refused
2023-07-21 13:29:50 | INFO | stdout | Running on local URL:  http://0.0.0.0:7862
2023-07-21 13:29:50 | INFO | stdout |
2023-07-21 13:29:50 | INFO | stdout | To create a public link, set `share=True` in `launch()`.
2023-07-21 13:29:50 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-07-21 13:29:50 | ERROR | stderr | Traceback (most recent call last):
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2023-07-21 13:29:50 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     raise exc
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     await self.app(scope, receive, send)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     raise exc
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     raise e
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     await self.app(scope, receive, send)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-07-21 13:29:50 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-07-21 13:29:50 | ERROR | stderr |     await self.app(scope, receive, send)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-07-21 13:29:50 | ERROR | stderr |     response = await func(request)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
2023-07-21 13:29:50 | ERROR | stderr |     raw_response = await run_endpoint_function(
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
2023-07-21 13:29:50 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2023-07-21 13:29:50 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
2023-07-21 13:29:50 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-07-21 13:29:50 | ERROR | stderr |     return await future
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-07-21 13:29:50 | ERROR | stderr |     result = context.run(func, *args)
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/gradio/routes.py", line 289, in api_info
2023-07-21 13:29:50 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2023-07-21 13:29:50 | ERROR | stderr |   File "/home/kznrluk/.conda/envs/llava/lib/python3.10/site-packages/gradio/blocks.py", line 518, in get_api_info
2023-07-21 13:29:50 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2023-07-21 13:29:50 | ERROR | stderr | KeyError: 'dataset'
```

**Comment by kznrluk** [comment]
After re-cloning the repository and recreating the conda environment, I added `gradio_client==0.2.7` to `pyproject.toml`. Following the instructions in README.md, everything now starts up without any issues. I have submitted a pull request, so please review it at your convenience.

https://github.com/haotian-liu/LLaVA/pull/287

**Comment by haotian-liu** [comment]
Thanks for your feedback! I'll close this issue for now, and we can discuss in the thread within your PR. Thanks!
