### ISSUE TITLE
Can you enable low_cpu_mem_usage mode

### ISSUE THREAD

**Issue by YerongLi** [haotian-liu/LLaVA#289]
I am getting error `ValueError: Unexpected embed_tokens_weight shape. Pretrained: torch.Size([32004, 4096]). `
```
I am getting this error without deepspeed:
```
 This IS NOT expected if you are initializing CLIPVisionModel from the checkpoint of a model that you expect to be exactly identical (initializing a[74/1988]
equenceClassification model from a BertForSequenceClassification model).                                                                                      
Traceback (most recent call last):                                                                                                                            
  File "/scratch/yerong/LLaVA/llava/train/train_mem.py", line 13, in <module>                                                                                 
    train()                                                                                                                                                   
  File "/scratch/yerong/LLaVA/llava/train/train.py", line 771, in train
    model.initialize_vision_tokenizer(mm_use_im_start_end=model_args.mm_use_im_start_end, tokenizer=tokenizer, device=training_args.device,
  File "/scratch/yerong/LLaVA/llava/model/llava.py", line 343, in initialize_vision_tokenizer
    raise ValueError(f"Unexpected embed_tokens_weight shape. Pretrained: {embed_tokens_weight.shape}. Current: {input_embeddings.shape}. Numer of new tokens: 
{num_new_tokens}.")
ValueError: Unexpected embed_tokens_weight shape. Pretrained: torch.Size([32004, 4096]). Current: torch.Size([32003, 4096]). Numer of new tokens: 2.

```
The command I am using is this:
```
python llava/train/train_mem.py \
    --lora_enable True \
    --model_name_or_path checkpoints/vicuna-7b-v1.1 \
    --version $PROMPT_VERSION \
    --data_path ./playground/data/llava_instruct_150k.json \
    --image_folder /scratch/yerong/Multimodal-GPT/data/coco/train2017 \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter ./checkpoints/mm_projector/llava-7b-pretrain.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir ./checkpoints/deepspeed_llava-$MODEL_VERSION-$WEIGHT_VERSION-finetune_lora \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --dataloader_num_workers 4 \
    --report_to wandb
```

**Comment by YerongLi** [comment]
This is caused by this:
- Extract projector features from the pretrained model from the feature alignment stage. 
```
python scripts/extract_mm_projector.py \
  --model_name_or_path ./checkpoints/llava-13b-pretrain \
  --output ./checkpoints/mm_projector/llava-13b-pretrain.bin
```
With https://huggingface.co/liuhaotian/LLaVA-Pretrained-Projectors/blob/main/LLaVA-7b-pretrain-projector-v0-CC3M-595K-original_caption.bin
there is no error.
