### ISSUE TITLE
OOM on V100 GPU

### ISSUE THREAD

**Issue by YerongLi** [haotian-liu/LLaVA#290]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:
V100 GPU got error without **flash_attn**
Command:
```
#!/bin/bash

WEIGHT_VERSION=v1-1
PROMPT_VERSION=v1
MODEL_VERSION="7b"

python llava/train/train.py \
    --lora_enable True \
    --model_name_or_path checkpoints/vicuna-7b-v1.1 \
    --version $PROMPT_VERSION \
    --data_path ./playground/data/llava_instruct_150k.json \
    --image_folder /scratch/yerong/Multimodal-GPT/data/coco/train2017 \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter ./checkpoints/mm_projector/LLaVA-7b-pretrain-projector-v0-CC3M-595K-original_caption.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 False \
    --output_dir ./checkpoints/deepspeed_llava-$MODEL_VERSION-$WEIGHT_VERSION-finetune_lora \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --dataloader_num_workers 4 \
    --report_to wandb

```
**LOG**
```
WARNING:root:Formatting inputs...Skip in lazy mode                                                                                                     [0/320]
/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes
 in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that exce
ssive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
wandb: Currently logged in as: yerong. Use `wandb login --relogin` to force relogin                                   
wandb: Tracking run with wandb version 0.15.5
wandb: Run data is saved locally in /scratch/yerong/LLaVA/wandb/run-20230721_031057-pupvktt6                                                                  
wandb: Run `wandb offline` to turn off syncing.                                                                                                               
wandb: Syncing run good-serenity-7                                             
wandb: _ View project at https://wandb.ai/yerong/huggingface                                                                                                  
wandb:  View run at https://wandb.ai/yerong/huggingface/runs/pupvktt6                                                                                         
  0%|                                                                                                                              | 0/473136 [00:00<?, ?it/s]
/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes
 in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that exce
ssive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/scratch/yerong/LLaVA/llava/train/train.py", line 837, in <module>
    train()
  File "/scratch/yerong/LLaVA/llava/train/train.py", line 817, in train
    trainer.train()
  File "/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1978, in _inner_training_loop
    self.optimizer.step()
  File "/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/torch/optim/adamw.py", line 160, in step
    self._init_group(
  File "/scratch/yerong/.conda/envs/llava/lib/python3.10/site-packages/torch/optim/adamw.py", line 114, in _init_group
    state["exp_avg"] = torch.zeros_like(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 502.00 MiB (GPU 0; 31.75 GiB total capacity; 30.16 GiB already allocated; 319.69 MiB free; 
30.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for
 Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
Unfortunately V100 does not have flash-attn support yet and we do not have control over that. Two possibilities:

1. Use [cpu offloading](https://github.com/haotian-liu/LLaVA/blob/main/scripts/zero3_offload.json).
2. Use [QLora](https://github.com/haotian-liu/LLaVA/blob/main/scripts/finetune_qlora.sh)

You can try to see which one works, and it would be great if you can send the feedback here (I do not have access to V100s currently), so that others from community who owns V100 GPUs can have a sense of what would work.

Thanks!

**Comment by wileewang** [comment]
Hi, do you solve the OOM problem? I am also trying to fine-tune llava on v100 gpus.

**Comment by guanlaoda** [comment]
https://github.com/haotian-liu/LLaVA/pull/411 with xformers on V100
