### ISSUE TITLE
[Question] ModuleNotFoundError "einops"

### ISSUE THREAD

**Issue by kittyLunar** [haotian-liu/LLaVA#308]
### Question

Just followed the steps in README.md 
when I trying to train my data to llava model.
I got few error messages
which is all about "einops" module

ModuleNotFoundError: No module named 'einops'

however, I already installed the module 'einops' in my conda environment
`pip list | grep einops`
einops                   0.6.1

`conda list | grep einops`
einops                    0.6.1                    pypi_0    pypi

when I install einops module through conda-forge channel, it shows same error.

what did I miss?
or do I have to set PYTHONPATH to some specific path?

here is one of the error messages I've got.

Traceback (most recent call last):
  File "llava/train/train_mem.py", line 6, in <module>
    from llava.train.llama_flash_attn_monkey_patch import replace_llama_attn_with_flash_attn
  File "/home/test/llava/\_\_init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/home/test/llava/model/\_\_init__.py", line 2, in <module>
    from .llava_mpt import LlavaMPTForCausalLM, LlavaMPTConfig
  File "/home/test/llava/model/llava_mpt.py", line 31, in <module>
    from .mpt.modeling_mpt import MPTConfig, MPTForCausalLM, MPTModel
  File "/home/test/llava/model/mpt/modeling_mpt.py", line 13, in <module>
    from .attention import attn_bias_shape, build_attn_bias
  File "/home/test/llava/model/mpt/attention.py", line 7, in <module>
    from einops import rearrange
ModuleNotFoundError: No module named 'einops'

**Comment by haotian-liu** [comment]
This is strange, as `einops` is definitely included in [`pyproject.toml`](https://github.com/haotian-liu/LLaVA/blob/main/pyproject.toml), and you also see it is installed.

Just to make sure the env is installed correctly, can you try running the inference code and see if it can be loaded correctly? And please also try run this **not in the repository directory** so that it must load llava from registered environment, just to test the env is installed correctly.

https://github.com/haotian-liu/LLaVA#cli-inference

Thanks.

**Comment by kittyLunar** [comment]
CLI inference with [https://github.com/haotian-liu/LLaVA#cli-inference](url) show an error message 
`ImportError: cannot import name 'TextStreamer' from 'transformers'`

however, I did CLI inference with 
`python -m llava.eval.run_llava` it works well  (not `python -m llava.serve.cli`)

I think something installed wrong. however, I could not figure out what are wrong.
cuz I perfectly followed all steps which are written in Readme.md

**Comment by haotian-liu** [comment]
Hi @kittyLunar 

Can you try to see what your `transformers` version is? Thanks.

**Comment by kittyLunar** [comment]
@haotian-liu 
my transformers version is like below
`pip list | grep transformers`
`transformers             4.28.0.dev0`
`conda list | grep transformers`
`transformers              4.28.0.dev0              pypi_0    pypi`

**Comment by haotian-liu** [comment]
Hi, this seems that the installation is not fully matching the latest code base. As our latest code requires [`transformers==4.31.0`](https://github.com/haotian-liu/LLaVA/blob/main/pyproject.toml#L22).

Please try update the packages to the latest code base, following the instructions [here](https://github.com/haotian-liu/LLaVA/tree/main#upgrade-to-latest-code-base). You may also try a clean install.

**Comment by kittyLunar** [comment]
Thanks, I installed transformers 4.31.0 and tried clean install
after that, the CLI inference works fine.
however, in case of training, it shows same error. "einops" module not found.

I have no idea what should I check for that module. 
I think that I have to figure out in very basic things.. like how did the python find the dependency of installation module or something like that.. It will be really tough job I think.

If you have any guide, or suggestions for that "einops" module not found error.
please let me know. 

Thanks.

**Comment by haotian-liu** [comment]
@kittyLunar 

Hi, could you make sure that you activate your conda environment when you try to do the training? You can check by using `which python` and see if it is using the python from your conda environment.

If it is showing the correct one, you will probably see something like `/path/to/conda/envs/llava/bin/python`, use this path as a reference to navigate to `/path/to/conda/envs/llava/lib/python3.10/site-packages`, which is the place of all your packages are installed at.

Try to see if einops is in there, e.g. `ls einops*`.
