### ISSUE TITLE
[Question] 'list' object is not callable

### ISSUE THREAD

**Issue by FuxiaoLiu** [haotian-liu/LLaVA#322]
### Question

May I ask whether anyone meet this error :

TypeError: 'list' object is not callable.

This is from /path/to/llava/model/llava_arch.py, line 82.

image_features = self.get_model().vision_tower(images).

**Comment by dydxdt** [comment]
self.get_model().vision_tower()(images). works

**Comment by haotian-liu** [comment]
@FuxiaoLiu 

This should have been fixed by PR #299, which was already merged last week. Can you please try the latest code base? Thanks.

**Comment by SteveTaoTao** [comment]
@FuxiaoLiu 

still  has something  wrong？

torchrun --nnodes=1 --nproc_per_node=1 --master_port=25001     llava/train/train_mem.py     --model_name_or_path /media/weight/LLaVA-7B-v0     --version v0     --data_path /media/train_data/res.json     --image_folder /media/train_data/images/     --vision_tower openai/clip-vit-large-patch14     --tune_mm_mlp_adapter True     --mm_vision_select_layer -2     --mm_use_im_start_end True    --bf16 True     --output_dir /media/train_out/llava-7b-finetune     --num_train_epochs 100     --per_device_train_batch_size 16     --per_device_eval_batch_size 4     --gradient_accumulation_steps 8     --evaluation_strategy "no"     --save_strategy "steps"     --save_steps 5     --save_total_limit 1     --learning_rate 2e-5     --weight_decay 0.     --warmup_ratio 0.03     --lr_scheduler_type "cosine"     --logging_steps 1     --tf32 True     --fsdp "full_shard auto_wrap"     --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer'     --model_max_length 2048     --gradient_checkpointing True     --dataloader_num_workers 4     --lazy_preprocess True     --report_to wandb



Traceback (most recent call last):
  File "/home/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/LLaVA/llava/train/train.py", line 853, in train
    model.get_model().initialize_vision_modules(
  File "/home/LLaVA/llava/model/llava_arch.py", line 52, in initialize_vision_modules
    self.vision_tower = [vision_tower]
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1653, in __setattr__
    raise TypeError("cannot assign '{}' as child module '{}' "
TypeError: cannot assign 'list' as child module 'vision_tower' (torch.nn.Module or None expected)






pytorch 2.0.1
