### ISSUE TITLE
[Usage] CLI Error

### ISSUE THREAD

**Issue by sameeravithana** [haotian-liu/LLaVA#338]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:

Command:
```
python -m llava.serve.cli \
    --model-path liuhaotian/LLaVA-Lightning-MPT-7B-preview \
    --image-file "X.png" 
```

Log: 
```
Traceback (most recent call last):
  File "..lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "..lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/qfs/projects/steel_thread/hora620/DevHub/scientific-instruction-tuning/LLaVA-2/LLaVA-3/LLaVA/llava/serve/cli.py", line 119, in <module>
    main(args)
  File "/qfs/projects/steel_thread/hora620/DevHub/scientific-instruction-tuning/LLaVA-2/LLaVA-3/LLaVA/llava/serve/cli.py", line 89, in main
    output_ids = model.generate(
  File "..lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "..lib/python3.9/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "..lib/python3.9/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "..lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "..lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "LLaVA/llava/model/language_model/llava_mpt.py", line 78, in forward
    logits = F.linear(outputs.last_hidden_state, self.transformer.wte.weight)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:6 and cuda:0! (when checking argument for argument mat2 in method wrapper_mm)
```

**Comment by sameeravithana** [comment]
No issue when used, ```--model-path liuhaotian/llava-llama-2-13b-chat-lightning-preview```

**Comment by haotian-liu** [comment]
Thanks for bringing this up. It seems that there is an issue with MPT models with multiple GPU inference. Just added a temporary fix in https://github.com/haotian-liu/LLaVA/commit/fc1006268f312c051bf51d2c1c23280b1b4f2f7d.

**Comment by Lizw14** [comment]
Follow up on this - I met the similar issues with MPT. 

Now the same device issue is solved, but another issue happens: I finetuned MPT-base LLaVA model with LoRA. But during inference, it seems that current `load_pretrained_model` in [builder.py](https://github.com/haotian-liu/LLaVA/blob/main/llava/model/builder.py) does not support loading MPT with LoRA.

Would be great if this could be looked into. Thanks!
