### ISSUE TITLE
questions regarding dropping position_ids in the model.prepare_inputs_for_generation

### ISSUE THREAD

**Issue by bastia0321** [haotian-liu/LLaVA#347]
Hello Haotian:

really appreciate that you shared this awesome work. I have a noob question regarding

https://github.com/haotian-liu/LLaVA/blob/4f801cd99fe2006e95d9946a36710ce125075484/llava/model/language_model/llava_llama.py#L117

would like to know why you dropped position_ids here to override the original method from llama class? Thanks.

**Comment by haotian-liu** [comment]
Hi @bastia0321 

Thank you for bringing this to our attention, this is a great point! I modified this function from the transformers code base, and the code base at that point does not have position_ids yet.

I will need to double check this and fix this soon. Thanks!

**Comment by Darren-greenhand** [comment]
Hi，thx for your excellent work!!
I wonder have you solved the problem?
this may caused the error below:
```shell
Traceback (most recent call last):
  File "/tf/LLaVA2/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/tf/project/LLaVA/llava/train/train.py", line 909, in train
    trainer.train()
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/tf/project/LLaVA/llava/model/language_model/llava_llama.py", line 78, in forward
    outputs = self.model(
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 685, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 681, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/tf/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'position_ids'
```
