### ISSUE TITLE
why LLaVA need load CLIP model first, and how to load openai/clip-vit-large-patch14-336

### ISSUE THREAD

**Issue by gnimyang** [haotian-liu/LLaVA#350]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

when I running 
> `llava.serve.model_worker` with `liuhaotian/llava-v1-0719-336px-lora-merge-vicuna-13b-v1.3` model
I meet a problem that I need download CLIP model from internet, but I offline (have to)
Do you have any method I can load this CLIP model offline, better to load it into cache(/public/home/usr/.cache/huggingface/hub/), which convenient for program reload it.

detailed model is openai/clip-vit-large-patch14-336

the error feed back is
`
2023-08-04 21:17:15 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, worker_address='http://localhost:40000', controller_address='http://localhost:10000', model_path='./checkpoints/LLaVA-vicuna-13B-v1.3', model_base=None, model_name=None, multi_modal=False, limit_model_concurrency=5, stream_interval=1, no_register=False, load_8bit=False, load_4bit=False)
2023-08-04 21:17:15 | INFO | model_worker | Loading the model LLaVA-vicuna-13B-v1.3 on worker e61d07 ...
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
2023-08-04 21:17:15 | ERROR | stderr | Traceback (most recent call last):
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
2023-08-04 21:17:15 | ERROR | stderr |     resolved_file = hf_hub_download(
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2023-08-04 21:17:15 | ERROR | stderr |     return fn(*args, **kwargs)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
2023-08-04 21:17:15 | ERROR | stderr |     raise LocalEntryNotFoundError(
2023-08-04 21:17:15 | ERROR | stderr | huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.
2023-08-04 21:17:15 | ERROR | stderr | 
2023-08-04 21:17:15 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-08-04 21:17:15 | ERROR | stderr | 
2023-08-04 21:17:15 | ERROR | stderr | Traceback (most recent call last):
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-08-04 21:17:15 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
2023-08-04 21:17:15 | ERROR | stderr |     exec(code, run_globals)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/serve/model_worker.py", line 273, in <module>
2023-08-04 21:17:15 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/serve/model_worker.py", line 64, in __init__
2023-08-04 21:17:15 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/model/builder.py", line 100, in load_pretrained_model
2023-08-04 21:17:15 | ERROR | stderr |     model = LlavaLlamaForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
2023-08-04 21:17:15 | ERROR | stderr |     model = cls(config, *model_args, **model_kwargs)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/model/language_model/llava_llama.py", line 46, in __init__
2023-08-04 21:17:15 | ERROR | stderr |     self.model = LlavaLlamaModel(config)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/model/language_model/llava_llama.py", line 38, in __init__
2023-08-04 21:17:15 | ERROR | stderr |     super(LlavaLlamaModel, self).__init__(config)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/model/llava_arch.py", line 32, in __init__
2023-08-04 21:17:15 | ERROR | stderr |     self.vision_tower = build_vision_tower(config, delay_load=True)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/model/multimodal_encoder/builder.py", line 7, in build_vision_tower
2023-08-04 21:17:15 | ERROR | stderr |     return CLIPVisionTower(vision_tower, args=vision_tower_cfg, **kwargs)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/model/multimodal_encoder/clip_encoder.py", line 20, in __init__
2023-08-04 21:17:15 | ERROR | stderr |     self.cfg_only = CLIPVisionConfig.from_pretrained(self.vision_tower_name)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 239, in from_pretrained
2023-08-04 21:17:15 | ERROR | stderr |     config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
2023-08-04 21:17:15 | ERROR | stderr |     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
2023-08-04 21:17:15 | ERROR | stderr |     resolved_config_file = cached_file(
2023-08-04 21:17:15 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/utils/hub.py", line 452, in cached_file
2023-08-04 21:17:15 | ERROR | stderr |     raise EnvironmentError(
2023-08-04 21:17:15 | ERROR | stderr | OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14-336 is not the path to a directory containing a file named config.json.
2023-08-04 21:17:15 | ERROR | stderr | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

`

**Comment by haotian-liu** [comment]
Discussion here is highly overlapped with #348, let's condensing the discussion there.
