### ISSUE TITLE
AttributeError: 'LlamaConfig' object has no attribute 'mm_vision_tower'

### ISSUE THREAD

**Issue by haorunze** [haotian-liu/LLaVA#37]
log：

(llava) D:\LLaVA>python -m llava.serve.model_worker --controller http://localhost:10000 --port 40000 --worker http://loc
alhost:40000 --model-path ./checkpoints/LLaVA-13B-v0 --multi-modal
2023-04-22 11:15:42 | INFO | model_worker | args: Namespace(host='localhost', port=40000, worker_address='http://localho
st:40000', controller_address='http://localhost:10000', model_path='./checkpoints/LLaVA-13B-v0', model_name=None, multi_
modal=True, keep_aspect_ratio=False, num_gpus=1, limit_model_concurrency=5, stream_interval=2, no_register=False)
2023-04-22 11:15:42 | INFO | model_worker | Loading the model LLaVA-13B-v0 on worker 56bbc2 ...
Loading checkpoint shards:   0%|                                                                 | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:  33%|███████████████████                                      | 1/3 [00:02
<00:05,  2.57s/it]
Loading checkpoint shards:  67%|██████████████████████████████████████
       | 2/3 [00:05<00:02,  2.56s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████
█████████████| 3/3 [00:06<00:00,  2.17s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████
█████████████| 3/3 [00:06<00:00,  2.28s/it]
2023-04-22 11:15:49 | ERROR | stderr |
2023-04-22 11:15:49 | ERROR | stderr | Traceback (most recent call last):
2023-04-22 11:15:49 | ERROR | stderr |   File "C:\Users\xht\anaconda3\envs\llava\lib\runpy.py", line 196, in _run_module
_as_main
2023-04-22 11:15:49 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-04-22 11:15:49 | ERROR | stderr |   File "C:\Users\xht\anaconda3\envs\llava\lib\runpy.py", line 86, in _run_code
2023-04-22 11:15:49 | ERROR | stderr |     exec(code, run_globals)
2023-04-22 11:15:49 | ERROR | stderr |   File "D:\LLaVA\llava\serve\model_worker.py", line 361, in <module>
2023-04-22 11:15:49 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2023-04-22 11:15:49 | ERROR | stderr |   File "D:\LLaVA\llava\serve\model_worker.py", line 118, in __init__
2023-04-22 11:15:49 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_mod
el(
2023-04-22 11:15:49 | ERROR | stderr |   File "D:\LLaVA\llava\serve\model_worker.py", line 65, in load_model
2023-04-22 11:15:49 | ERROR | stderr |     image_processor = CLIPImageProcessor.from_pretrained(model.config.mm_vision_t
ower, torch_dtype=torch.float16)
2023-04-22 11:15:49 | ERROR | stderr |   File "D:\LLaVA\transformers\src\transformers\configuration_utils.py", line 260,
 in __getattribute__
2023-04-22 11:15:49 | ERROR | stderr |     return super().__getattribute__(key)
2023-04-22 11:15:49 | ERROR | stderr | AttributeError: 'LlamaConfig' object has no attribute 'mm_vision_tower'

**Comment by haotian-liu** [comment]
Hi, thank you for the interest in our work.

Can you try with the updated instructions: first create a new Conda environment, and then do the install? This has worked for others in #15,#23. Thanks!

https://github.com/haotian-liu/LLaVA#install

**Comment by haorunze** [comment]
> 
Thank you for reply
I have tried these commands from https://github.com/haotian-liu/LLaVA/issues/15:
pip install git+https://github.com/haotian-liu/transformers_llava.git@26356f0d07bacfb3857dafc7f8a519304b4c0572
git clone https://github.com/haotian-liu/transformers_llava.git transformers
pip install -e ./transformers

It doesn't work.
Do I need other operation?

first create a new Conda environment, and then do the install? What is that mean?Do I need reinstall LLaVa ？

**Comment by haotian-liu** [comment]
I think I misread the error log.  `AttributeError: 'LlamaConfig' object has no attribute 'mm_vision_tower'`. This suggest that the model config may not be correct.

Can you check the `config.json` under `./checkpoints/LLaVA-13B-v0`, and see if you see `"mm_vision_tower": "openai/clip-vit-large-patch14"`?  If not, there may be something wrong happened during the weight conversion process.  Please try follow the instructions here and do the weight conversion: https://github.com/haotian-liu/LLaVA#llava-weights

> first create a new Conda environment, and then do the install? What is that mean?Do I need reinstall LLaVa ？
This is to try avoid any potential issues on the incompatibility with the package versions, so I would suggest do these four commands, to ensure a clean install.

```
conda create -n llava python=3.10 -y
conda activate llava
pip install --upgrade pip  # enable PEP 660 support
pip install -e .
```

**Comment by haotian-liu** [comment]
Hi, I am closing this issue, due to the inactivity.  Hope your problem has been resolved.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!

**Comment by prashant-dn** [comment]
In my case, the 'flash attention' lib mismatched with transformers. This is how I fixed it.

Use container `docker pull huggingface/transformers-pytorch-gpu:latest` with local CUDA 12.1+.

Inside, just install 'flash attention', if needed, using `pip install flash-attn --no-build-isolation`.

Works like a charm!
