### ISSUE TITLE
[Usage] CUDNN_STATUS_NOT_INITIALIZED when running worker from demo

### ISSUE THREAD

**Issue by ohharsen** [haotian-liu/LLaVA#392]
### Describe the issue

Issue:
I try following the instructions for demo but running into ad cuDNN issue.
Command:
```
python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path ./checkpoints/llava-llama-2-13b-chat-lightning-preview
```

Log: 
```
2023-08-25 08:59:20 | ERROR | stderr | Traceback (most recent call last):
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2023-08-25 08:59:20 | ERROR | stderr |     self.run()
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/threading.py", line 953, in run
2023-08-25 08:59:20 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2023-08-25 08:59:20 | ERROR | stderr |     return func(*args, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
2023-08-25 08:59:20 | ERROR | stderr |     return self.sample(
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
2023-08-25 08:59:20 | ERROR | stderr |     outputs = self(
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
2023-08-25 08:59:20 | ERROR | stderr |     return forward_call(*input, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-08-25 08:59:20 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/home/ec2-user/server/llava/model/language_model/llava_llama.py", line 75, in forward
2023-08-25 08:59:20 | ERROR | stderr |     input_ids, attention_mask, past_key_values, inputs_embeds, labels = self.prepare_inputs_labels_for_multimodal(input_ids, attention_mask, past_key_values, labels, images)
2023-08-25 08:59:20 | ERROR | stderr |   File "/home/ec2-user/server/llava/model/llava_arch.py", line 102, in prepare_inputs_labels_for_multimodal
2023-08-25 08:59:20 | ERROR | stderr |     image_features = self.encode_images(images)
2023-08-25 08:59:20 | ERROR | stderr |   File "/home/ec2-user/server/llava/model/llava_arch.py", line 82, in encode_images
2023-08-25 08:59:20 | ERROR | stderr |     image_features = self.get_model().get_vision_tower()(images)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
2023-08-25 08:59:20 | ERROR | stderr |     return forward_call(*input, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-08-25 08:59:20 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
2023-08-25 08:59:20 | ERROR | stderr |     return func(*args, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/home/ec2-user/server/llava/model/multimodal_encoder/clip_encoder.py", line 48, in forward
2023-08-25 08:59:20 | ERROR | stderr |     image_forward_outs = self.vision_tower(images.to(device=self.device, dtype=self.dtype), output_hidden_states=True)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
2023-08-25 08:59:20 | ERROR | stderr |     return forward_call(*input, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 941, in forward
2023-08-25 08:59:20 | ERROR | stderr |     return self.vision_model(
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
2023-08-25 08:59:20 | ERROR | stderr |     return forward_call(*input, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 866, in forward
2023-08-25 08:59:20 | ERROR | stderr |     hidden_states = self.embeddings(pixel_values)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
2023-08-25 08:59:20 | ERROR | stderr |     return forward_call(*input, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 195, in forward
2023-08-25 08:59:20 | ERROR | stderr |     patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, width, grid, grid]
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
2023-08-25 08:59:20 | ERROR | stderr |     return forward_call(*input, **kwargs)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
2023-08-25 08:59:20 | ERROR | stderr |     return self._conv_forward(input, self.weight, self.bias)
2023-08-25 08:59:20 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
2023-08-25 08:59:20 | ERROR | stderr |     return F.conv2d(input, weight, bias, self.stride,
2023-08-25 08:59:20 | ERROR | stderr | RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

The versions for packages for context:
```
torch                     1.13.1+cu117
torchaudio                0.13.1+cu117
torchvision               0.14.1+cu117
transformers              4.31.0
```

I have tried the solution https://github.com/haotian-liu/LLaVA/issues/123#issuecomment-1539434115 but it was of no help

Any idea what this might be caused by?

**Comment by ohharsen** [comment]
For anyone who will run into this situation in the future, this was merely a OOM issue as explainer [here](https://stackoverflow.com/a/69808279). Creating a mock convolution before inference helped to at least get the actual OOM error instead of the CUDNN_STATUS_NOT_INITIALIZED.
