### ISSUE TITLE
[Question] Missing key(s) in state_dict: "lora_A.default.weight", "lora_B.default.weight".

### ISSUE THREAD

**Issue by xmy0916** [haotian-liu/LLaVA#420]
### Question

when i am running finetune_lora.sh with llama2, i got this error.
```python
File "/opt/tiger/workspace/llava-video/llava/model/llava_arch.py", line 69, in initialize_vision_modules
    self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
  File "/home/tiger/.conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Linear:
        Missing key(s) in state_dict: "lora_A.default.weight", "lora_B.default.weight".
```
maybe a bug? 
solution:
self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'), strict=False)?

**Comment by 1106301825** [comment]
Do you solve this problem? @xmy0916

**Comment by xmy0916** [comment]
@1106301825 I have given the solution on the above comment.
solution:
self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'), strict=False)

**Comment by basteran** [comment]
@xmy0916 I don't think yours is a viable solution, as I get this error:

```
Traceback (most recent call last):
  File "/home/c.hromei/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/c.hromei/LLaVA/llava/train/train.py", line 853, in train
    model.get_model().initialize_vision_modules(
  File "/home/c.hromei/LLaVA/llava/model/llava_arch.py", line 69, in initialize_vision_modules
    self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'), strict=False)
  File "/home/c.hromei/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Linear:
        size mismatch for weight: copying a param with shape torch.Size([5120, 1024]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([0]).
```

**Comment by xmy0916** [comment]
@basteran i guess you run the script "finetine_qlora.sh" with llama 2? I have got the same error as you, i just skip loading params for this layer and it seems training with no problem. By the way i have try "finetune_lora.sh" and "finetune_qlora.sh" but the performance seems not so good on my dataset.

**Comment by basteran** [comment]
@xmy0916 Yes, I run the script "finetune_lora.sh" using the Vicuna LLM. I can't figure out what's the point of those params and how to skip them eventually.

**Comment by xmy0916** [comment]
@basteran you can check out the params' name in the adapter_model.bin and model, modify the name of checkpoint state_dict from 'XXXX.lora_A.weight' to 'XXXX.lora_A.default.weight' maybe can help.

**Comment by xmy0916** [comment]
@basteran Sorry, I didn’t read your error carefully. You have a shape mismatch, which makes it impossible to load parameters. I feel that the code published by the author may be inconsistent with the parameters. You can try to delete this layer of parameters from ckpt, but it will definitely affect lora's performance.
