### ISSUE TITLE
[Discussion] 繁琐

### ISSUE THREAD

**Issue by wanghao-007** [haotian-liu/LLaVA#460]
### Discussion

有一说一，我觉得这个web端完全没有必要这么麻烦，要启动一个对话界面需要启动三个脚本程序，这完全是不可理喻的，建议改进一下，只启动一个。

**Comment by nj159** [comment]
请问一下，在启动第三个脚本程序时，python3 -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path ./checkpoints/LLaVA-13B-v0 中的./checkpoints/LLaVA-13B-v0是自己在本地下载LLaVA-13B-v0模型后的路径嘛？
我前两个启动之后，第三个的错误如下：
2023-10-06 05:49:13 | ERROR | stderr | Traceback (most recent call last):
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-10-06 05:49:13 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
2023-10-06 05:49:13 | ERROR | stderr |     exec(code, run_globals)
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/data/private/LLaVA/llava/serve/model_worker.py", line 273, in <module>
2023-10-06 05:49:13 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/data/private/LLaVA/llava/serve/model_worker.py", line 64, in __init__
2023-10-06 05:49:13 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/data/private/LLaVA/llava/model/builder.py", line 102, in load_pretrained_model
2023-10-06 05:49:13 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained
2023-10-06 05:49:13 | ERROR | stderr |     tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 496, in get_tokenizer_config
2023-10-06 05:49:13 | ERROR | stderr |     resolved_config_file = cached_file(
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
2023-10-06 05:49:13 | ERROR | stderr |     resolved_file = hf_hub_download(
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
2023-10-06 05:49:13 | ERROR | stderr |     validate_repo_id(arg_value)
2023-10-06 05:49:13 | ERROR | stderr |   File "/opt/conda/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
2023-10-06 05:49:13 | ERROR | stderr |     raise HFValidationError(
2023-10-06 05:49:13 | ERROR | stderr | huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './checkpoints/LLaVA-13B-v0'. Use `repo_type` argument if needed.

**Comment by wanghao-007** [comment]
> 请问一下，在启动第三个脚本程序时，python3 -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path ./checkpoints/LLaVA-13B-v0 中的./checkpoints/LLaVA-13B-v0是自己在本地下载LLaVA-13B-v0模型后的路径嘛？ 我前两个启动之后，第三个的错误如下： 2023-10-06 05:49:13 | ERROR | stderr | Traceback (most recent call last): 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/conda/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main 2023-10-06 05:49:13 | ERROR | stderr | return _run_code(code, main_globals, None, 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/conda/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code 2023-10-06 05:49:13 | ERROR | stderr | exec(code, run_globals) 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/data/private/LLaVA/llava/serve/model_worker.py", line 273, in 2023-10-06 05:49:13 | ERROR | stderr | worker = ModelWorker(args.controller_address, 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/data/private/LLaVA/llava/serve/model_worker.py", line 64, in **init** 2023-10-06 05:49:13 | ERROR | stderr | self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model( 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/data/private/LLaVA/llava/model/builder.py", line 102, in load_pretrained_model 2023-10-06 05:49:13 | ERROR | stderr | tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False) 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained 2023-10-06 05:49:13 | ERROR | stderr | tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs) 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 496, in get_tokenizer_config 2023-10-06 05:49:13 | ERROR | stderr | resolved_config_file = cached_file( 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file 2023-10-06 05:49:13 | ERROR | stderr | resolved_file = hf_hub_download( 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/conda/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn 2023-10-06 05:49:13 | ERROR | stderr | validate_repo_id(arg_value) 2023-10-06 05:49:13 | ERROR | stderr | File "/opt/conda/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id 2023-10-06 05:49:13 | ERROR | stderr | raise HFValidationError( 2023-10-06 05:49:13 | ERROR | stderr | huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './checkpoints/LLaVA-13B-v0'. Use `repo_type` argument if needed.

不瞒你说，第三个脚本我也没有运行成功，无法正常使用

**Comment by theblackcat102** [comment]
@wanghao-007  你的 ./checkpoints/LLaVA-13B-v0' 路徑不存在吧？否則就是位子放錯了，這個問題應該是 huggingface `from_pretrained` 找不到該路徑。

我覺得 @haotian-liu  設計的想法是一個中控的服務 (controller) 負責分配資源到不同的 worker 。為了讓實驗能比較好比較， worker 可以是不同的模型。而 user ( 例如 gradio ) 只需要去負責與 controller 對接即可。

嚴格上你應該是只需要第一個 worker 沒有 controller 應該也要能使用。但是我覺得畢竟這是研究向的專案，如果想優化的話，就去 [text-generation-inference](https://github.com/huggingface/text-generation-inference) 專案那邊去吧

**Comment by haotian-liu** [comment]
Thanks for the explanation @theblackcat102 and that's our intention (also the design is largely borrowed from Vicuna/FastChat).

We are also creating a single-endpoint demo, which does not require the user to mess up with these controller/worker/frontend stuff. Our first step is a HF Space demo: https://huggingface.co/spaces/badayvedat/LLaVA

Thanks.

**Comment by wanghao-007** [comment]
> @wanghao-007 你的 ./checkpoints/LLaVA-13B-v0' 路徑不存在吧？否則就是位子放錯了，這個問題應該是 huggingface `from_pretrained` 找不到該路徑。
> 
> 我覺得 @haotian-liu 設計的想法是一個中控的服務 (controller) 負責分配資源到不同的 worker 。為了讓實驗能比較好比較， worker 可以是不同的模型。而 user ( 例如 gradio ) 只需要去負責與 controller 對接即可。
> 
> 嚴格上你應該是只需要第一個 worker 沒有 controller 應該也要能使用。但是我覺得畢竟這是研究向的專案，如果想優化的話，就去 [text-generation-inference](https://github.com/huggingface/text-generation-inference) 專案那邊去吧

是的，运行成功了。

**Comment by zbxx-423** [comment]
你好 我想问一下具体在哪里改这个目录啊     我的报错和你的一样
