### ISSUE TITLE
Unable to inference on the V100 GPU (Driver Version: 470.182.03 / CUDA version 11.1 and 11.4)

### ISSUE THREAD

**Issue by ZetangForward** [haotian-liu/LLaVA#493]
### Describe the issue

Issue:

I find the code below cannot work under the CUDA Version of 11.1 and 11.4, where the torch version is ``torch=2.1.0``.

Command:
```
python -m llava.serve.cli  --model-path /zecheng/svg_model_hub/llava-v1.5-13b --image-file /workspace/zecheng/ns/svg_dataset/output.png
```

Log: 
```
Traceback (most recent call last):
  File "/home/chewu/.conda/envs/llava/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chewu/.conda/envs/llava/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/LLaVA/llava/serve/cli.py", line 119, in <module>
    main(args)
  File "/workspace/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit)
  File "/workspace/LLaVA/llava/model/builder.py", line 140, in load_pretrained_model
    vision_tower.to(device=device, dtype=torch.float16)
  File "/home/chewu/.conda/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/chewu/.conda/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/chewu/.conda/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/chewu/.conda/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/chewu/.conda/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/chewu/.conda/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/chewu/.conda/envs/llava/lib/python3.9/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

```
I hope the author can fix this problem or provide some alternative approaches to run this code on this machine (CUDA version==11.1 or 11.4)

**Comment by haotian-liu** [comment]
This may be due to the recent release of PyTorch 2.1, which requires CUDA 12.1 by default. I temporarily set the torch version to 2.0.1 in https://github.com/haotian-liu/LLaVA/commit/fda0665106c5b13bbb5b1ffb167ce5e32cd7c8d7. Can you pull the latest code and try a fresh install?

**Comment by ZetangForward** [comment]
> This may be due to the recent release of PyTorch 2.1, which requires CUDA 12.1 by default. I temporarily set the torch version to 2.0.1 in [fda0665](https://github.com/haotian-liu/LLaVA/commit/fda0665106c5b13bbb5b1ffb167ce5e32cd7c8d7). Can you pull the latest code and try a fresh install?

Thank you very much. This modification works! Now, this code can be run on my machine!

**Comment by qishisuren123** [comment]
Could you please tell me the versions of your libraries, including torch, torchvision, and flash-attn? I encountered the following error while installing flash-attn.
![ecdc33879a18c433015afc2b557f3307](https://github.com/user-attachments/assets/3b987b4d-5db0-40aa-891d-ff02743a5dd6)
