### ISSUE TITLE
`LlamaTokenizerFast` implementation missing

### ISSUE THREAD

**Issue by satyajitghana** [haotian-liu/LLaVA#5]
```
satyajit@zeus:~/satyajit/llama-dl$ python3 convert_llama_weights_to_hf.py --input_dir . --model_size 13B --output_dir llama_hf
Traceback (most recent call last):
  File "convert_llama_weights_to_hf.py", line 28, in <module>
    from transformers import LlamaTokenizerFast
ImportError: cannot import name 'LlamaTokenizerFast' from 'transformers' (/home/satyajit/satyajit/transformers_llava/src/transformers/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert_llama_weights_to_hf.py", line 30, in <module>
    warnings.warn(e)
TypeError: expected string or bytes-like object
```

**Comment by satyajitghana** [comment]
replace all instances of `LlamaTokenizerFast` with `LlamaTokenizer` fixed the issue

**Comment by satyajitghana** [comment]
I've got it working on CPU !

![image](https://user-images.githubusercontent.com/8092481/232740034-0fb6fc5f-72d7-4b35-9324-be91b922f3bb.png)

**Comment by haotian-liu** [comment]
Thank you for your interest in our work and congratulations on successfully running this!

And also thanks for figuring out this issue!  We'll fix this soon.
