### ISSUE TITLE
[Usage] RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED 

### ISSUE THREAD

**Issue by hjsg1010** [haotian-liu/LLaVA#506]
### Describe the issue

Issue: RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

Command:
```
python -m llava.serve.cli \
    --model-path "/home/LLaVA-main/pretrained/LLaVA-Lightning-MPT-7B-preview" \
    --image-file "/home/LLaVA-main/view.jpg" \
    --load-4bit
```

Log: 
```
[2023-10-10 12:31:07,178] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You are using config.init_device='cpu', but you can also use config.init_device="meta" with Composer + FSDP for fast initialization.
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|████████████████████████████████| 2/2 [00:27<00:00, 13.77s/it]
user: please describe the view 
Traceback (most recent call last):
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/LLaVA-main/llava/serve/cli.py", line 119, in <module>
    main(args)
  File "/home/jovyan/LLaVA-main/llava/serve/cli.py", line 89, in main
    output_ids = model.generate(
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jovyan/LLaVA-main/llava/model/language_model/llava_mpt.py", line 76, in forward
    input_ids, attention_mask, past_key_values, inputs_embeds, labels = self.prepare_inputs_labels_for_multimodal(input_ids, attention_mask, past_key_values, labels, images)
  File "/home/jovyan/LLaVA-main/llava/model/llava_arch.py", line 103, in prepare_inputs_labels_for_multimodal
    image_features = self.encode_images(images)
  File "/home/jovyan/LLaVA-main/llava/model/llava_arch.py", line 83, in encode_images
    image_features = self.get_model().get_vision_tower()(images)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/LLaVA-main/llava/model/multimodal_encoder/clip_encoder.py", line 48, in forward
    image_forward_outs = self.vision_tower(images.to(device=self.device, dtype=self.dtype), output_hidden_states=True)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 941, in forward
    return self.vision_model(
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 866, in forward
    hidden_states = self.embeddings(pixel_values)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 195, in forward
    patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, width, grid, grid]
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/jovyan/.local/share/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

I have torch 2.0.0+cu117, and 4 A100 80Gb gpus.

**Comment by hjsg1010** [comment]
this is how I changed LLaVA-Lightning-MPT-7B-preview model's config
```
{
  "_name_or_path": "llava-mpt-7b-pretrain_blip_558k_new_template_1e-instruct_conv_reason_nooverlap_80k-1epoch",
  "architectures": [
    "LlavaMPTForCausalLM"
  ],
  "attn_config": {
    "alibi": true,
    "alibi_bias_max": 8,
    "attn_impl": "torch",
    "attn_pdrop": 0,
    "attn_type": "multihead_attention",
    "attn_uses_sequence_id": false,
    "clip_qkv": null,
    "prefix_lm": false,
    "qk_ln": false,
    "softmax_scale": null
  },
  "d_model": 4096,
  "emb_pdrop": 0,
  "embedding_fraction": 1.0,
  "expansion_ratio": 4,
  "freeze_mm_mlp_adapter": false,
  "init_config": {
    "emb_init_std": null,
    "emb_init_uniform_lim": null,
    "fan_mode": "fan_in",
    "init_div_is_residual": true,
    "init_gain": 0,
    "init_nonlinearity": "relu",
    "init_std": 0.02,
    "name": "kaiming_normal_",
    "verbose": 0
  },
  "init_device": "cpu",
  "learned_pos_emb": true,
  "logit_scale": null,
  "max_seq_len": 2048,
  "mm_hidden_size": 1024,
  "mm_use_im_start_end": true,
  "mm_vision_select_layer": -2,
  "mm_vision_tower": "/home/jovyan/data-vol-1/model/llava/clip-vit-large-patch14-336",
  "model_type": "llava_mpt",
  "n_heads": 32,
  "n_layers": 32,
  "no_bias": true,
  "norm_type": "low_precision_layernorm",
  "resid_pdrop": 0,
  "sep_image_conv_front": false,
  "tokenizer_name": "/home/jovyan/LLaVA-main/pretrained/gpt-neox-20b-chatml",
  "torch_dtype": "float16",
  "transformers_version": "4.28.0.dev0",
  "tune_mm_mlp_adapter": false,
  "use_cache": true,
  "use_mm_proj": true,
  "verbose": 0,
  "vocab_size": 50282
}

```
I just changed mm_vision_tower and tokenizer_name to my local directories

**Comment by hjsg1010** [comment]
also same error when I tried with "llava-v1.5-7b" model

**Comment by YFCodeDream** [comment]
Hello! I want to know how you solved this problem.

**Comment by Dongjie-Cheng** [comment]
Same here. I want to know how you solved this problem.

**Comment by C0NGTRI123** [comment]
I solve this use load_checkpoint to 4 bit like that:
```
tokenizer, model, image_processor, context_len = load_pretrained_model(
                                                                    model_path=args.model,
                                                                    model_base=None,
                                                                    model_name=model_name,
                                                                    load_4bit=True)
```
I think that error when VRAM GPU not enough to load checkpoint (This is case I debug when I catch this bug)
