### ISSUE TITLE
Can you add venv installer?

### ISSUE THREAD

**Issue by FurkanGozukara** [haotian-liu/LLaVA#521]
### Describe the issue

Conda failing on Windows

I have miniconda and anaconda as well

```
(base) PS C:\Users\King> cd "G:\LLaVA"
(base) PS G:\LLaVA> conda create -n llava python=3.10 -y
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.7.2
  latest version: 23.9.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.9.0



## Package Plan ##

  environment location: C:\Users\King\miniconda3\envs\llava

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       he774522_0         113 KB
    libffi-3.4.4               |       hd77b12b_0         113 KB
    openssl-3.0.11             |       h2bbff1b_2         7.4 MB
    pip-23.2.1                 |  py310haa95532_0         2.8 MB
    python-3.10.13             |       he1021f5_0        15.8 MB
    setuptools-68.0.0          |  py310haa95532_0         934 KB
    tk-8.6.12                  |       h2bbff1b_0         3.1 MB
    vc-14.2                    |       h21ff451_1           8 KB
    vs2015_runtime-14.27.29016 |       h5e58377_2        1007 KB
    wheel-0.41.2               |  py310haa95532_0         127 KB
    xz-5.4.2                   |       h8cc25b3_0         592 KB
    ------------------------------------------------------------
                                           Total:        32.0 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0
  ca-certificates    pkgs/main/win-64::ca-certificates-2023.08.22-haa95532_0
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_0
  openssl            pkgs/main/win-64::openssl-3.0.11-h2bbff1b_2
  pip                pkgs/main/win-64::pip-23.2.1-py310haa95532_0
  python             pkgs/main/win-64::python-3.10.13-he1021f5_0
  setuptools         pkgs/main/win-64::setuptools-68.0.0-py310haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.41.2-h2bbff1b_0
  tk                 pkgs/main/win-64::tk-8.6.12-h2bbff1b_0
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/win-64::wheel-0.41.2-py310haa95532_0
  xz                 pkgs/main/win-64::xz-5.4.2-h8cc25b3_0
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate llava
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS G:\LLaVA> conda activate llava
(llava) PS G:\LLaVA> pip install --upgrade pip  # enable PEP 660 support
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: pip in c:\users\king\miniconda3\envs\llava\lib\site-packages (23.2.1)
(llava) PS G:\LLaVA> pip install -e .
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///G:/LLaVA
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting einops (from llava==1.1.0)
  Obtaining dependency information for einops from https://files.pythonhosted.org/packages/29/0b/2d1c0ebfd092e25935b86509a9a817159212d82aa43d7fb07eca4eeff2c2/einops-0.7.0-py3-none-any.whl.metadata
  Downloading einops-0.7.0-py3-none-any.whl.metadata (13 kB)
Collecting fastapi (from llava==1.1.0)
  Obtaining dependency information for fastapi from https://files.pythonhosted.org/packages/4d/d2/3ad038a2365fefbac19d9a046cab7ce45f4c7bfa81d877cbece9707de9ce/fastapi-0.103.2-py3-none-any.whl.metadata
  Downloading fastapi-0.103.2-py3-none-any.whl.metadata (24 kB)
Collecting gradio==3.35.2 (from llava==1.1.0)
  Obtaining dependency information for gradio==3.35.2 from https://files.pythonhosted.org/packages/50/70/ed0ba0fb5c3b1cb2e481717ad190056a4c9a0ef2f296b871e10375b2ab83/gradio-3.35.2-py3-none-any.whl.metadata
  Downloading gradio-3.35.2-py3-none-any.whl.metadata (15 kB)
Collecting markdown2[all] (from llava==1.1.0)
  Obtaining dependency information for markdown2[all] from https://files.pythonhosted.org/packages/f1/98/61276a753f078dd2f3171c9a69fd3f451d220e806b2b1cdca41b8e368b0f/markdown2-2.4.10-py2.py3-none-any.whl.metadata
  Downloading markdown2-2.4.10-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting numpy (from llava==1.1.0)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/cc/05/ef9fc04adda45d537619ea956bc33489f50a46badc949c4280d8309185ec/numpy-1.26.0-cp310-cp310-win_amd64.whl.metadata
  Downloading numpy-1.26.0-cp310-cp310-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 61.1/61.1 kB 807.0 kB/s eta 0:00:00
Collecting requests (from llava==1.1.0)
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting sentencepiece (from llava==1.1.0)
  Downloading sentencepiece-0.1.99-cp310-cp310-win_amd64.whl (977 kB)
     ---------------------------------------- 977.5/977.5 kB 4.1 MB/s eta 0:00:00
Collecting tokenizers>=0.12.1 (from llava==1.1.0)
  Obtaining dependency information for tokenizers>=0.12.1 from https://files.pythonhosted.org/packages/92/02/15556b80450301d2ef014bc598df4352bfb39631c5fcff758d8e0ac9f065/tokenizers-0.14.1-cp310-none-win_amd64.whl.metadata
  Downloading tokenizers-0.14.1-cp310-none-win_amd64.whl.metadata (6.8 kB)
Collecting torch==2.0.1 (from llava==1.1.0)
  Downloading torch-2.0.1-cp310-cp310-win_amd64.whl (172.3 MB)
     ---------------------------------------- 172.3/172.3 MB 38.6 MB/s eta 0:00:00
Collecting torchvision==0.15.2 (from llava==1.1.0)
  Downloading torchvision-0.15.2-cp310-cp310-win_amd64.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 15.2 MB/s eta 0:00:00
Collecting uvicorn (from llava==1.1.0)
  Obtaining dependency information for uvicorn from https://files.pythonhosted.org/packages/79/96/b0882a1c3f7ef3dd86879e041212ae5b62b4bd352320889231cc735a8e8f/uvicorn-0.23.2-py3-none-any.whl.metadata
  Downloading uvicorn-0.23.2-py3-none-any.whl.metadata (6.2 kB)
Collecting wandb (from llava==1.1.0)
  Obtaining dependency information for wandb from https://files.pythonhosted.org/packages/1c/5e/0362fa88679852c7fd3ac85ee5bd949426c4a51a61379010d4089be6d7ac/wandb-0.15.12-py3-none-any.whl.metadata
  Downloading wandb-0.15.12-py3-none-any.whl.metadata (9.8 kB)
Collecting shortuuid (from llava==1.1.0)
  Downloading shortuuid-1.0.11-py3-none-any.whl (10 kB)
Collecting httpx==0.24.0 (from llava==1.1.0)
  Downloading httpx-0.24.0-py3-none-any.whl (75 kB)
     ---------------------------------------- 75.3/75.3 kB 1.0 MB/s eta 0:00:00
Collecting deepspeed==0.9.5 (from llava==1.1.0)
  Downloading deepspeed-0.9.5.tar.gz (809 kB)
     ---------------------------------------- 809.9/809.9 kB 12.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\King\AppData\Local\Temp\pip-install-zaa916lp\deepspeed_97fb3e87e18e4914b37cfa1e3095162b\setup.py", line 129, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      ←[93m [WARNING] ←[0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(llava) PS G:\LLaVA>
```

**Comment by FurkanGozukara** [comment]
Anaconda fails too. We really need requirements.txt to install as a venv

```
(base) PS C:\Users\King> conda update -n base -c defaults conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) PS C:\Users\King> cd "G:\LLaVA"
(base) PS G:\LLaVA> conda create -n llava python=3.10 -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\King\miniconda3\envs\llava

  added / updated specs:
    - python=3.10


The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0
  ca-certificates    pkgs/main/win-64::ca-certificates-2023.08.22-haa95532_0
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_0
  openssl            pkgs/main/win-64::openssl-3.0.11-h2bbff1b_2
  pip                pkgs/main/win-64::pip-23.2.1-py310haa95532_0
  python             pkgs/main/win-64::python-3.10.13-he1021f5_0
  setuptools         pkgs/main/win-64::setuptools-68.0.0-py310haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.41.2-h2bbff1b_0
  tk                 pkgs/main/win-64::tk-8.6.12-h2bbff1b_0
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/win-64::wheel-0.41.2-py310haa95532_0
  xz                 pkgs/main/win-64::xz-5.4.2-h8cc25b3_0
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate llava
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS G:\LLaVA> conda activate llava
(llava) PS G:\LLaVA> pip install --upgrade pip  # enable PEP 660 support
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: pip in c:\users\king\miniconda3\envs\llava\lib\site-packages (23.2.1)
(llava) PS G:\LLaVA> pip install -e .
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///G:/LLaVA
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting einops (from llava==1.1.0)
  Obtaining dependency information for einops from https://files.pythonhosted.org/packages/29/0b/2d1c0ebfd092e25935b86509a9a817159212d82aa43d7fb07eca4eeff2c2/einops-0.7.0-py3-none-any.whl.metadata
  Downloading einops-0.7.0-py3-none-any.whl.metadata (13 kB)
Collecting fastapi (from llava==1.1.0)
  Obtaining dependency information for fastapi from https://files.pythonhosted.org/packages/4d/d2/3ad038a2365fefbac19d9a046cab7ce45f4c7bfa81d877cbece9707de9ce/fastapi-0.103.2-py3-none-any.whl.metadata
  Downloading fastapi-0.103.2-py3-none-any.whl.metadata (24 kB)
Collecting gradio==3.35.2 (from llava==1.1.0)
  Obtaining dependency information for gradio==3.35.2 from https://files.pythonhosted.org/packages/50/70/ed0ba0fb5c3b1cb2e481717ad190056a4c9a0ef2f296b871e10375b2ab83/gradio-3.35.2-py3-none-any.whl.metadata
  Downloading gradio-3.35.2-py3-none-any.whl.metadata (15 kB)
Collecting markdown2[all] (from llava==1.1.0)
  Obtaining dependency information for markdown2[all] from https://files.pythonhosted.org/packages/f1/98/61276a753f078dd2f3171c9a69fd3f451d220e806b2b1cdca41b8e368b0f/markdown2-2.4.10-py2.py3-none-any.whl.metadata
  Downloading markdown2-2.4.10-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting numpy (from llava==1.1.0)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/cc/05/ef9fc04adda45d537619ea956bc33489f50a46badc949c4280d8309185ec/numpy-1.26.0-cp310-cp310-win_amd64.whl.metadata
  Downloading numpy-1.26.0-cp310-cp310-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 61.1/61.1 kB 807.0 kB/s eta 0:00:00
Collecting requests (from llava==1.1.0)
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting sentencepiece (from llava==1.1.0)
  Downloading sentencepiece-0.1.99-cp310-cp310-win_amd64.whl (977 kB)
     ---------------------------------------- 977.5/977.5 kB 3.9 MB/s eta 0:00:00
Collecting tokenizers>=0.12.1 (from llava==1.1.0)
  Obtaining dependency information for tokenizers>=0.12.1 from https://files.pythonhosted.org/packages/92/02/15556b80450301d2ef014bc598df4352bfb39631c5fcff758d8e0ac9f065/tokenizers-0.14.1-cp310-none-win_amd64.whl.metadata
  Downloading tokenizers-0.14.1-cp310-none-win_amd64.whl.metadata (6.8 kB)
Collecting torch==2.0.1 (from llava==1.1.0)
  Downloading torch-2.0.1-cp310-cp310-win_amd64.whl (172.3 MB)
     ---------------------------------------- 172.3/172.3 MB 59.4 MB/s eta 0:00:00
Collecting torchvision==0.15.2 (from llava==1.1.0)
  Downloading torchvision-0.15.2-cp310-cp310-win_amd64.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 15.2 MB/s eta 0:00:00
Collecting uvicorn (from llava==1.1.0)
  Obtaining dependency information for uvicorn from https://files.pythonhosted.org/packages/79/96/b0882a1c3f7ef3dd86879e041212ae5b62b4bd352320889231cc735a8e8f/uvicorn-0.23.2-py3-none-any.whl.metadata
  Downloading uvicorn-0.23.2-py3-none-any.whl.metadata (6.2 kB)
Collecting wandb (from llava==1.1.0)
  Obtaining dependency information for wandb from https://files.pythonhosted.org/packages/1c/5e/0362fa88679852c7fd3ac85ee5bd949426c4a51a61379010d4089be6d7ac/wandb-0.15.12-py3-none-any.whl.metadata
  Downloading wandb-0.15.12-py3-none-any.whl.metadata (9.8 kB)
Collecting shortuuid (from llava==1.1.0)
  Downloading shortuuid-1.0.11-py3-none-any.whl (10 kB)
Collecting httpx==0.24.0 (from llava==1.1.0)
  Downloading httpx-0.24.0-py3-none-any.whl (75 kB)
     ---------------------------------------- 75.3/75.3 kB 833.9 kB/s eta 0:00:00
Collecting deepspeed==0.9.5 (from llava==1.1.0)
  Downloading deepspeed-0.9.5.tar.gz (809 kB)
     ---------------------------------------- 809.9/809.9 kB 12.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\King\AppData\Local\Temp\pip-install-r5zsmpa0\deepspeed_f6982825619841cd9a70d79d5778b4ca\setup.py", line 129, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      ←[93m [WARNING] ←[0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(llava) PS G:\LLaVA>
```

**Comment by haotian-liu** [comment]
Would be great to have the Windows support for more users from the community to try this, and it is on my list for this week. Currently working on the code release and will try to make this work this week!

**Comment by FurkanGozukara** [comment]
> Would be great to have the Windows support for more users from the community to try this, and it is on my list for this week. Currently working on the code release and will try to make this work this week!

awesome thank you

**Comment by onlinerender** [comment]
> Would be great to have the Windows support for more users from the community to try this, and it is on my list for this week. Currently working on the code release and will try to make this work this week!

Great

**Comment by FurkanGozukara** [comment]
when we can expect working on Windows

**Comment by Kallamamran** [comment]
Second that... Windows please 😃👍

**Comment by haotian-liu** [comment]
Please check the latest doc for Windows. I tested on my Windows 11 PC and it seems to be working for 16-bit inference.

https://github.com/haotian-liu/LLaVA/blob/main/docs/Windows.md

**Comment by FurkanGozukara** [comment]
> Please check the latest doc for Windows. I tested on my Windows 11 PC and it works now for 16-bit inference. Quantization will be supported later.
> 
> https://github.com/haotian-liu/LLaVA/blob/main/docs/Windows.md

[WSL2](https://learn.microsoft.com/en-us/windows/wsl/install) is not windows still unix

please add python venv

**Comment by FurkanGozukara** [comment]
> Please check the latest doc for Windows. I tested on my Windows 11 PC and it works now for 16-bit inference. Quantization will be supported later.
> 
> https://github.com/haotian-liu/LLaVA/blob/main/docs/Windows.md

thank you so much

I got error at last step where we start [Launch a model worker](https://github.com/haotian-liu/LLaVA#launch-a-model-worker)

https://github.com/haotian-liu/LLaVA/issues/668
