### ISSUE TITLE
Is it normal when launching a model worker?

### ISSUE THREAD

**Issue by zxcvbn114514** [haotian-liu/LLaVA#56]
![image](https://user-images.githubusercontent.com/128148517/234188153-c8327001-afb3-42ce-b295-8b50e55d83a8.png)

**Comment by zxcvbn114514** [comment]
It failed at last....
last few lines:
2023-04-25 14:30:18 | ERROR | stderr |     self._send_request(method, url, body, headers, encode_chunked)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\http\client.py", line 1328, in _send_request
2023-04-25 14:30:18 | ERROR | stderr |     self.endheaders(body, encode_chunked=encode_chunked)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\http\client.py", line 1277, in endheaders
2023-04-25 14:30:18 | ERROR | stderr |     self._send_output(message_body, encode_chunked=encode_chunked)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\http\client.py", line 1037, in _send_output
2023-04-25 14:30:18 | ERROR | stderr |     self.send(msg)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\http\client.py", line 975, in send
2023-04-25 14:30:18 | ERROR | stderr |     self.connect()
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\urllib3\connection.py", line 205, in connect
2023-04-25 14:30:18 | ERROR | stderr |     conn = self._new_conn()
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
2023-04-25 14:30:18 | ERROR | stderr |     raise NewConnectionError(
2023-04-25 14:30:18 | ERROR | stderr | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002A68ECEECE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
2023-04-25 14:30:18 | ERROR | stderr |
2023-04-25 14:30:18 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-04-25 14:30:18 | ERROR | stderr |
2023-04-25 14:30:18 | ERROR | stderr | Traceback (most recent call last):
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\requests\adapters.py", line 489, in send
2023-04-25 14:30:18 | ERROR | stderr |     resp = conn.urlopen(
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
2023-04-25 14:30:18 | ERROR | stderr |     retries = retries.increment(
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\urllib3\util\retry.py", line 592, in increment
2023-04-25 14:30:18 | ERROR | stderr |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-04-25 14:30:18 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A68ECEECE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-04-25 14:30:18 | ERROR | stderr |
2023-04-25 14:30:18 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-04-25 14:30:18 | ERROR | stderr |
2023-04-25 14:30:18 | ERROR | stderr | Traceback (most recent call last):
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\runpy.py", line 196, in _run_module_as_main
2023-04-25 14:30:18 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\runpy.py", line 86, in _run_code
2023-04-25 14:30:18 | ERROR | stderr |     exec(code, run_globals)
2023-04-25 14:30:18 | ERROR | stderr |   File "A:\LLaVA\llava\serve\model_worker.py", line 361, in <module>
2023-04-25 14:30:18 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2023-04-25 14:30:18 | ERROR | stderr |   File "A:\LLaVA\llava\serve\model_worker.py", line 122, in __init__
2023-04-25 14:30:18 | ERROR | stderr |     self.register_to_controller()
2023-04-25 14:30:18 | ERROR | stderr |   File "A:\LLaVA\llava\serve\model_worker.py", line 136, in register_to_controller
2023-04-25 14:30:18 | ERROR | stderr |     r = requests.post(url, json=data)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\requests\api.py", line 115, in post
2023-04-25 14:30:18 | ERROR | stderr |     return request("post", url, data=data, json=json, **kwargs)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\requests\api.py", line 59, in request
2023-04-25 14:30:18 | ERROR | stderr |     return session.request(method=method, url=url, **kwargs)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\requests\sessions.py", line 587, in request
2023-04-25 14:30:18 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\requests\sessions.py", line 701, in send
2023-04-25 14:30:18 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2023-04-25 14:30:18 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\llava\lib\site-packages\requests\adapters.py", line 565, in send
2023-04-25 14:30:18 | ERROR | stderr |     raise ConnectionError(e, request=request)
2023-04-25 14:30:18 | ERROR | stderr | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A68ECEECE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by haotian-liu** [comment]
Hi, it seems a similar issue to this one: https://github.com/lm-sys/FastChat/issues/186

Have you launched the controller first before running the model worker?

> You must follow the three steps:
> 
> 
> 
> launch a controller
> launch a worker and connect to the controller
> launch Gradio webserver and connect to the controller.
> You cannot launch a server alone.

**Comment by haotian-liu** [comment]
Closing the issue due to inactivity, please feel free to re-open if you meet any other issues, thanks.
