### ISSUE TITLE
Unable to run on 1x 4090 or 2x 4090s

### ISSUE THREAD

**Issue by lonestriker** [haotian-liu/LLaVA#60]
I'm getting different errors when trying to run on either a single or double 4090s.

With 1x 4090  (--num-gpus=1):
```
2023-04-25 21:25:18 | ERROR | stderr | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 136.00 MiB (GPU 0; 23.65 GiB total capacity; 23.11 GiB already allocated; 76.19 MiB free; 23.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

With 2x 4090s (--num-gpus=2)
```
2023-04-25 21:27:37 | ERROR | stderr | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

I'm not running any other applications at the moment and nvidia-smi shows the following:
```
Tue Apr 25 21:28:27 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090         On | 00000000:01:00.0 Off |                  Off |
|  0%   47C    P5               39W / 450W|     22MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090         On | 00000000:08:00.0 Off |                  Off |
|  0%   37C    P5               47W / 480W|      6MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1236      G   /usr/lib/xorg/Xorg                            9MiB |
|    0   N/A  N/A      1486      G   /usr/bin/gnome-shell                         10MiB |
|    1   N/A  N/A      1236      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+
```

Any advice?

Thanks!

**Comment by haotian-liu** [comment]
Hi thank you for the interest in our work!  The currect FP16 version is expected to OOM on a single RTX 4090.  The 8-bit quantization in WIP, and will release this week.  Regarding running on two-gpus.

Would you mind: 

(1) sharing the error message before this one, so that I can see which line of code is causing the issue;
(2) sharing the command on running with multiple gpus;
(2) meanwhile, trying to see if the `transformers` version is correct as there is a fix 5 days ago on multiple gpu: `pip install git+https://github.com/haotian-liu/transformers_llava.git@988b6abb3b7da9a5cbb5051e994706f7f88c2565`

Thanks.

**Comment by lonestriker** [comment]
Thanks for the quick reply!  

I updated transformers before running the tests.  I just reran the installation again and tested again, same results.
```
$ pip install git+https://github.com/haotian-liu/transformers_llava.git@988b6abb3b7da9a5cbb5051e994706f7f88c2565
Collecting git+https://github.com/haotian-liu/transformers_llava.git@988b6abb3b7da9a5cbb5051e994706f7f88c2565
  Cloning https://github.com/haotian-liu/transformers_llava.git (to revision 988b6abb3b7da9a5cbb5051e994706f7f88c2565) to /tmp/pip-req-build-xv11al22
  Running command git clone --filter=blob:none --quiet https://github.com/haotian-liu/transformers_llava.git /tmp/pip-req-build-xv11al22
  Running command git rev-parse -q --verify 'sha^988b6abb3b7da9a5cbb5051e994706f7f88c2565'
  Running command git fetch -q https://github.com/haotian-liu/transformers_llava.git 988b6abb3b7da9a5cbb5051e994706f7f88c2565
  Resolved https://github.com/haotian-liu/transformers_llava.git to commit 988b6abb3b7da9a5cbb5051e994706f7f88c2565
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (3.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (0.13.4)
Requirement already satisfied: numpy>=1.17 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (1.24.2)
Requirement already satisfied: packaging>=20.0 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (2023.3.23)
Requirement already satisfied: requests in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (2.28.2)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (0.12.1)
Requirement already satisfied: tqdm>=4.27 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from transformers==4.28.0.dev0) (4.65.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.11.0->transformers==4.28.0.dev0) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from requests->transformers==4.28.0.dev0) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from requests->transformers==4.28.0.dev0) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from requests->transformers==4.28.0.dev0) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages (from requests->transformers==4.28.0.dev0) (2022.12.7)
```

Here's my command:
```
python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path /home/ubuntu/models/LLaVA-13B-v0 --multi-modal --num-gpus 2
```

Here's the full stack:

```
2023-04-25 21:27:36 | INFO | stdout | INFO:     127.0.0.1:39364 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-04-25 21:27:37 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-04-25 21:27:37 | ERROR | stderr | Traceback (most recent call last):
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/uvicorn/protocols/http/
h11_impl.py", line 429, in run_asgi
2023-04-25 21:27:37 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/uvicorn/middleware/prox
y_headers.py", line 78, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/fastapi/applications.py
", line 276, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/applications.
py", line 122, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/er
rors.py", line 184, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     raise exc
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/er
rors.py", line 162, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/ex
ceptions.py", line 79, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     raise exc
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/ex
ceptions.py", line 68, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyn
cexitstack.py", line 21, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     raise e
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyn
cexitstack.py", line 18, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     await self.app(scope, receive, send)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py",
line 718, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py",
line 276, in handle
2023-04-25 21:27:37 | ERROR | stderr |     await self.app(scope, receive, send)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py",
line 69, in app
2023-04-25 21:27:37 | ERROR | stderr |     await response(scope, receive, send)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py"
, line 270, in __call__
2023-04-25 21:27:37 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asynci
o.py", line 662, in __aexit__
2023-04-25 21:27:37 | ERROR | stderr |     raise exceptions[0]
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py"
, line 273, in wrap
2023-04-25 21:27:37 | ERROR | stderr |     await func()
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py"
, line 262, in stream_response
2023-04-25 21:27:37 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/concurrency.p
y", line 63, in iterate_in_threadpool
2023-04-25 21:27:37 | ERROR | stderr |     yield await anyio.to_thread.run_sync(_next, iterator)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/anyio/to_thread.py", li
ne 31, in run_sync
2023-04-25 21:27:37 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asynci
o.py", line 937, in run_sync_in_worker_thread
2023-04-25 21:27:37 | ERROR | stderr |     return await future
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asynci
o.py", line 867, in run
2023-04-25 21:27:37 | ERROR | stderr |     result = context.run(func, *args)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/starlette/concurrency.p
y", line 53, in _next
2023-04-25 21:27:37 | ERROR | stderr |     return next(iterator)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/git/LLaVA/llava/serve/model_worker.py", line 294, in generate_stream_gate
2023-04-25 21:27:37 | ERROR | stderr |     for x in self.generate_stream(params):
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib
.py", line 35, in generator_context
2023-04-25 21:27:37 | ERROR | stderr |     response = gen.send(None)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/git/LLaVA/llava/serve/model_worker.py", line 232, in generate_stream
2023-04-25 21:27:37 | ERROR | stderr |     out = model(
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-04-25 21:27:37 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-04-25 21:27:37 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 844, in forward
2023-04-25 21:27:37 | ERROR | stderr |     outputs = self.model(
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-04-25 21:27:37 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-04-25 21:27:37 | ERROR | stderr |   File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 631, in forward
2023-04-25 21:27:37 | ERROR | stderr |     cur_new_input_embeds = torch.cat((cur_input_embeds[:image_start_token_pos+1], cur_image_features, cur_input_embeds[image_start_token_pos + num_patches + 1:]), dim=0)
2023-04-25 21:27:37 | ERROR | stderr | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

**Comment by haotian-liu** [comment]
Hmm this is strange.  Your command and installation both look good to me.

Would you mind go to L627-631 in `/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py` to see if you see `cur_image_features = ...to(cur_input_embeds.device)`?

The reference code is [here](https://github.com/haotian-liu/transformers_llava/blob/988b6abb3b7da9a5cbb5051e994706f7f88c2565/src/transformers/models/llama/modeling_llama.py#L627-L631).

If this is the case, then I may need to look into huggingface doc on what is happening with GPU slicing (and unfortunately I am not reproducing this on my local server)

**Comment by lonestriker** [comment]
Thanks for the pointer, fixed now!

Notes:

Mine did not match your version:

```
                        cur_image_features = image_features[cur_image_idx]
                        num_patches = cur_image_features.shape[0]
                        if cur_input_ids[image_start_token_pos + num_patches + 1] != vision_tower.config.im_end_token:
                            raise ValueError("Seems that the image is cut.")
                        cur_new_input_embeds = torch.cat((cur_input_embeds[:image_start_token_pos+1], cur_image_features, cur_input_embeds[image_start_token_pos + num_patches + 1:]), dim=0)
```

I had to manually uninstall transformers and re-install your version again and now it matches and works!

So, moral of the story for me is to make sure to `pip uninstall transformers` and install again.

Thanks again.

**Comment by haotian-liu** [comment]
Oh cool!  I was always thinking `pip install` with a package associated with commit hash would ensure a clean install.  I will update the instructions in README as well.

If your problem has been solved, would you mind closing this issue?  Thanks.
