### ISSUE TITLE
[Usage] How to submit the results to the evaluation server?

### ISSUE THREAD

**Issue by CRH400AF-A** [haotian-liu/LLaVA#604]
### Describe the issue

Issue:

Thanks for your great work.
I want to evaluate the model on VQAv2 dataset, and I followed the [Evaluation.md]((https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md)) .After I ran the `CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 bash scripts/v1_5/eval/vqav2.sh`, I got some json files, like 8_0.json/8_1.json.  However, I don't know what I should do next.  You said in the [Evaluation.md]((https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md)) that, "Submit the results to the evaluation server: ./playground/data/eval/vqav2/answers_upload." But where to submit? How can I get the eval results?

**Comment by CRH400AF-A** [comment]
I have known the server and submitted my results to EvalAI.
The result is 
```
[
    {
        "test-dev": {
            "yes/no": 93.33,
            "number": 62.22,
            "other": 72.62,
            "overall": 79.97
        }
    },
    {
        "test-standard": {
            "yes/no": 0,
            "number": 0.02,
            "other": 0.04,
            "overall": 0.02
        }
    }
]
```
The test-dev result closely aligns with the data reported in the paper, around 80.0. However, the test-standard result is surprisingly low, almost approaching zero.

**Comment by gapjialin** [comment]
> Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.

Hi, I meet the same question. I don't know what I should do next. You said in the Evaluation.md that, "Submit the results to the evaluation server: ./playground/data/eval/vqav2/answers_upload." But where to submit? How can I get the eval results? Where is the server?

**Comment by CRH400AF-A** [comment]
> > Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.
> 
> Hi, I meet the same question. I don't know what I should do next. You said in the Evaluation.md that, "Submit the results to the evaluation server: ./playground/data/eval/vqav2/answers_upload." But where to submit? How can I get the eval results? Where is the server?

You mean the evaluation server? I just follow the Evaluation.md. The server is https://eval.ai/web/challenges/challenge-page/830/my-submission.

**Comment by gapjialin** [comment]
> > > Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.
> > 
> > 
> > Hi, I meet the same question. I don't know what I should do next. You said in the Evaluation.md that, "Submit the results to the evaluation server: ./playground/data/eval/vqav2/answers_upload." But where to submit? How can I get the eval results? Where is the server?
> 
> You mean the evaluation server? I just follow the Evaluation.md. The server is https://eval.ai/web/challenges/challenge-page/830/my-submission.
How should I continue at this point?
<img width="1004" alt="1702447590900" src="https://github.com/haotian-liu/LLaVA/assets/107861107/7dbbe142-0d00-4c45-9852-65265031962b">

**Comment by gapjialin** [comment]
> > > Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.
> > 
> > 
> > Hi, I meet the same question. I don't know what I should do next. You said in the Evaluation.md that, "Submit the results to the evaluation server: ./playground/data/eval/vqav2/answers_upload." But where to submit? How can I get the eval results? Where is the server?
> 
> You mean the evaluation server? I just follow the Evaluation.md. The server is https://eval.ai/web/challenges/challenge-page/830/my-submission.

I didn't see any place to upload files.

**Comment by gapjialin** [comment]
Thank you, I have resolved the issue. A good person lives a peaceful life.

**Comment by gapjialin** [comment]
> > > Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.
> > 
> > 
> > Hi, I meet the same question. I don't know what I should do next. You said in the Evaluation.md that, "Submit the results to the evaluation server: ./playground/data/eval/vqav2/answers_upload." But where to submit? How can I get the eval results? Where is the server?
> 
> You mean the evaluation server? I just follow the Evaluation.md. The server is https://eval.ai/web/challenges/challenge-page/830/my-submission.

Thank you, I have resolved the issue. A good person lives a peaceful life.

**Comment by SCZwangxiao** [comment]
> I have known the server and submitted my results to EvalAI. The result is
> 
> ```
> [
>     {
>         "test-dev": {
>             "yes/no": 93.33,
>             "number": 62.22,
>             "other": 72.62,
>             "overall": 79.97
>         }
>     },
>     {
>         "test-standard": {
>             "yes/no": 0,
>             "number": 0.02,
>             "other": 0.04,
>             "overall": 0.02
>         }
>     }
> ]
> ```
> 
> The test-dev result closely aligns with the data reported in the paper, around 80.0. However, the test-standard result is surprisingly low, almost approaching zero.

I tried to reproduce the results, and followed the submission README, but the scores are very low (~0.1). I think the scores should be much higher, because I manually checked 100 answers, and I found most of the ansers are correctly. Do you have any ides?

**Comment by SCZwangxiao** [comment]
> > I have known the server and submitted my results to EvalAI. The result is
> > ```
> > [
> >     {
> >         "test-dev": {
> >             "yes/no": 93.33,
> >             "number": 62.22,
> >             "other": 72.62,
> >             "overall": 79.97
> >         }
> >     },
> >     {
> >         "test-standard": {
> >             "yes/no": 0,
> >             "number": 0.02,
> >             "other": 0.04,
> >             "overall": 0.02
> >         }
> >     }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The test-dev result closely aligns with the data reported in the paper, around 80.0. However, the test-standard result is surprisingly low, almost approaching zero.
> 
> I tried to reproduce the results, and followed the submission README, but the scores are very low (~0.1). I think the scores should be much higher, because I manually checked 100 answers, and I found most of the ansers are correctly. Do you have any ides?

Solved. Add prompt to format answer into single word.

**Comment by LuFan31** [comment]
> Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.

Hi,  I have tried to upload llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server, but

**Comment by LuFan31** [comment]
> Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.

Hi, I have tried to upload llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server, but the submitted files are both Failed, and occured error: _Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 538, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 202, in evaluate
    prepare_objects(annFile, resFile, phase_codename)
  File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 109, in prepare_objects
    vqaRes = vqa.loadRes(res, resFile)
  File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/vqa.py", line 166, in loadRes
    anns    = json.load(open(resFile))
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 217)_   Maybe  i can obtain some help from u.

**Comment by CRH400AF-A** [comment]
> > Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.
> 
> Hi, I have tried to upload llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server, but the submitted files are both Failed, and occured error: _Traceback (most recent call last): File "/code/scripts/workers/submission_worker.py", line 538, in run_submission submission_metadata=submission_serializer.data, File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 202, in evaluate prepare_objects(annFile, resFile, phase_codename) File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 109, in prepare_objects vqaRes = vqa.loadRes(res, resFile) File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/vqa.py", line 166, in loadRes anns = json.load(open(resFile)) File "/usr/local/lib/python3.7/json/**init**.py", line 296, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "/usr/local/lib/python3.7/json/**init**.py", line 348, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 217)_ Maybe i can obtain some help from u.

Hi, I haven't been involved in similar work for a long time, but I still remember some details that may help you.
You said that you submitted the llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server. I remember  they are not the files that should be submiited.  You can check the ./scripts/v1_5/eval/vqav2.sh, and the last command tells you which file to submit.

**Comment by LuFan31** [comment]
> > > Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.
> > 
> > 
> > Hi, I have tried to upload llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server, but the submitted files are both Failed, and occured error: _Traceback (most recent call last): File "/code/scripts/workers/submission_worker.py", line 538, in run_submission submission_metadata=submission_serializer.data, File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 202, in evaluate prepare_objects(annFile, resFile, phase_codename) File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 109, in prepare_objects vqaRes = vqa.loadRes(res, resFile) File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/vqa.py", line 166, in loadRes anns = json.load(open(resFile)) File "/usr/local/lib/python3.7/json/**init**.py", line 296, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "/usr/local/lib/python3.7/json/**init**.py", line 348, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 217)_ Maybe i can obtain some help from u.
> 
> Hi, I haven't been involved in similar work for a long time, but I still remember some details that may help you. You said that you submitted the llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server. I remember they are not the files that should be submiited. You can check the ./scripts/v1_5/eval/vqav2.sh, and the last command tells you which file to submit.

Thank you for your prompt reply. I have already uploaded the file mentioned in ./scripts/v1_5/eval/vqav2.sh, which is in the ./playground/data/eval/vqav2/answers_upload and is just the file you mentioned at the begining of this issue. But I encountered the same problem as you https://github.com/haotian-liu/LLaVA/issues/604#issuecomment-1768524331, the metric of test_standard is almost 0. Could you provide any tips please.

**Comment by CRH400AF-A** [comment]
> > > > Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.
> > > 
> > > 
> > > Hi, I have tried to upload llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server, but the submitted files are both Failed, and occured error: _Traceback (most recent call last): File "/code/scripts/workers/submission_worker.py", line 538, in run_submission submission_metadata=submission_serializer.data, File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 202, in evaluate prepare_objects(annFile, resFile, phase_codename) File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 109, in prepare_objects vqaRes = vqa.loadRes(res, resFile) File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/vqa.py", line 166, in loadRes anns = json.load(open(resFile)) File "/usr/local/lib/python3.7/json/**init**.py", line 296, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "/usr/local/lib/python3.7/json/**init**.py", line 348, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 217)_ Maybe i can obtain some help from u.
> > 
> > 
> > Hi, I haven't been involved in similar work for a long time, but I still remember some details that may help you. You said that you submitted the llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server. I remember they are not the files that should be submiited. You can check the ./scripts/v1_5/eval/vqav2.sh, and the last command tells you which file to submit.
> 
> Thank you for your prompt reply. I have already uploaded the file mentioned in ./scripts/v1_5/eval/vqav2.sh, which is in the ./playground/data/eval/vqav2/answers_upload and is just the file you mentioned at the begining of this issue. But I encountered the same problem as you [#604 (comment)](https://github.com/haotian-liu/LLaVA/issues/604#issuecomment-1768524331), the metric of test_standard is almost 0. Could you provide any tips please.

As I mentioned [earlier](https://github.com/haotian-liu/LLaVA/issues/604#issuecomment-1768539776), selecting the wrong split file can result in a low score on test_standard.  In ./scripts/v1_5/eval/vqav2.sh, Line 9, you need to specify the split file. If you use the default file 'llava_vqav2_mscoco_test-dev2015', you will get a good score on test-dev but a bad one on test-std, because it's 'test-dev2015'!

**Comment by LuFan31** [comment]
> > > > > Ah, I think I find the reason. The file is different for test-standard! It's my fault. I will close the issue after I eval it on the llava_vqav2_mscoco_test2015.jsonl.
> > > > 
> > > > 
> > > > Hi, I have tried to upload llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server, but the submitted files are both Failed, and occured error: _Traceback (most recent call last): File "/code/scripts/workers/submission_worker.py", line 538, in run_submission submission_metadata=submission_serializer.data, File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 202, in evaluate prepare_objects(annFile, resFile, phase_codename) File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/main.py", line 109, in prepare_objects vqaRes = vqa.loadRes(res, resFile) File "/tmp/tmpu4q4g4fd/compute/challenge_data/challenge_830/vqa.py", line 166, in loadRes anns = json.load(open(resFile)) File "/usr/local/lib/python3.7/json/**init**.py", line 296, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "/usr/local/lib/python3.7/json/**init**.py", line 348, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 217)_ Maybe i can obtain some help from u.
> > > 
> > > 
> > > Hi, I haven't been involved in similar work for a long time, but I still remember some details that may help you. You said that you submitted the llava_vqav2_mscoco_test2015.jsonl and llava_vqav2_mscoco_test-dev2015.jsonl to the Server. I remember they are not the files that should be submiited. You can check the ./scripts/v1_5/eval/vqav2.sh, and the last command tells you which file to submit.
> > 
> > 
> > Thank you for your prompt reply. I have already uploaded the file mentioned in ./scripts/v1_5/eval/vqav2.sh, which is in the ./playground/data/eval/vqav2/answers_upload and is just the file you mentioned at the begining of this issue. But I encountered the same problem as you [#604 (comment)](https://github.com/haotian-liu/LLaVA/issues/604#issuecomment-1768524331), the metric of test_standard is almost 0. Could you provide any tips please.
> 
> As I mentioned [earlier](https://github.com/haotian-liu/LLaVA/issues/604#issuecomment-1768539776), selecting the wrong split file can result in a low score on test_standard. In ./scripts/v1_5/eval/vqav2.sh, Line 9, you need to specify the split file. If you use the default file 'llava_vqav2_mscoco_test-dev2015', you will get a good score on test-dev but a bad one on test-std, because it's 'test-dev2015'!

Thank you for your help! I have obtained the desired result.

**Comment by wxl1206** [comment]
> I have known the server and submitted my results to EvalAI. The result is
> 
> ```
> [
>     {
>         "test-dev": {
>             "yes/no": 93.33,
>             "number": 62.22,
>             "other": 72.62,
>             "overall": 79.97
>         }
>     },
>     {
>         "test-standard": {
>             "yes/no": 0,
>             "number": 0.02,
>             "other": 0.04,
>             "overall": 0.02
>         }
>     }
> ]
> ```
> 
> The test-dev result closely aligns with the data reported in the paper, around 80.0. However, the test-standard result is surprisingly low, almost approaching zero.

Hi!I am currently doing the same work. But when I submitted the anwser_upload file to the test-standard phase, I got the following result：

<img width="1341" height="39" alt="Image" src="https://github.com/user-attachments/assets/3a762b4c-ef31-455e-a1e4-6bc45fc1e147" />

Even the results on test-dev are quite low.

I am using the llava-v1.5-13b model, which has not been fine-tuned. In VQAv2, I used the question file downloaded from the official site: test-dev2015.jsonl. In convert_vqav2_for_submission.py, I used test2015.jsonl as the test split. This results in many empty answers, but why are the results for test-dev also so low? I hope to get your help.
