### ISSUE TITLE
[Usage] Missing and unexpected keys in our mm_projector.state_dict

### ISSUE THREAD

**Issue by StrangeTcy** [haotian-liu/LLaVA#608]
### Describe the issue

1.  We used a training script offered by [LLaVAR](https://github.com/SALT-NLP/LLaVAR/tree/main#training-script) to finetune our custom LLaVA:
```
#!/usr/bin/bash
torchrun --nnodes=1 --nproc_per_node=2 --master_port=25001 \
   /root/raw_data_for_llava/LLaVAR/LLaVA/llava/train/train_mem.py \
    --model_name_or_path meta-llama/Llama-2-7b-hf \
    --data_path all_the_data/chat_llavar.json \
    --image_folder all_the_data/pretrain_images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end \
    --bf16 True \
    --output_dir llava_R_output \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 4000 \
    --save_total_limit 1 \
    --learning_rate 2e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 1024 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --image_aspect_ratio 'pad' \
    --report_to wandb
```
-- as you can see, this is a wrapper around `train_mem.py` and ultimately `train.py`
2. After the training run we got a `mm_projector.bin` file, which was 517 MBs long
3. Then we tried to use it in a finetuning script you've provided for llava-1.5, slightly adapted for our usecase:
```
#!/bin/bash
#/root/raw_data_for_llava/LLaVAR/llava_R_output/mm_projector.bin
# mm_projector.bin


deepspeed ./LLaVA/llava/train/train_mem.py \
    --deepspeed ./LLaVA/scripts/zero3.json \
    --model_name_or_path meta-llama/Llama-2-7b-hf \
    --version v1 \
    --data_path /root/combined_data_for_llava/combined_conv.json \
    --image_folder /root/combined_data_for_llava/ \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /root/raw_data_for_llava/LLaVAR/llava_R_output/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end \
    --mm_use_im_patch_token \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./further_finetuning \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```
and ran into errors:
```
Traceback (most recent call last):
  File "/root/raw_data_for_llava/LLaVAR/./LLaVA/llava/train/train_mem.py", line 15, in <module>
    train()
  File "/root/raw_data_for_llava/LLaVAR/LLaVA/llava/train/train.py", line 872, in train
    model.get_model().initialize_vision_modules(
  File "/root/raw_data_for_llava/LLaVAR/LLaVA/llava/model/llava_arch.py", line 79, in initialize_vision_modules
    self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2054, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sequential:
        Missing key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias". 
        Unexpected key(s) in state_dict: "weight", "bias". 

```

Some examination of the state_dict we have in the `mm_projector.bin` file and the workings of `torch.nn.modules.module.load_state_dict` have shown that while the state_dict only contains `weight` and `bias`,  `module._modules.items()` has 0, 1 and 2 which are Linear, GELU and Linear, respectively.

I'm not sure whether this is a saving the projector issue or an issue with loading it back in again, but there you go.

**Comment by haotian-liu** [comment]
When you did pretraining, it seems that you did not specify "--mm_projector_type mlp2x_gelu", so that it was trained with linear layer. Thus there is a descrepency when you try to load it and specify `--mm_projector_type mlp2x_gelu` in finetuning.
