### ISSUE TITLE
[Usage] 

### ISSUE THREAD

**Issue by dinchu** [haotian-liu/LLaVA#636]
### Describe the issue

Issue:
The installation works without errors, but every time i try to execute any of the servers, worker or controller i get  No module named 'idna'. happens on ubuntu 22 with 2 L4 gpus. Did a check and idna is installed in version 
Command:
```
python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1.5-13b
```

Log: 
```
Traceback (most recent call last):
  File "/home/pdelgado_harlemnext_com/anaconda3/envs/llava/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/pdelgado_harlemnext_com/anaconda3/envs/llava/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/pdelgado_harlemnext_com/LLaVA/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/home/pdelgado_harlemnext_com/LLaVA/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
  File "/home/pdelgado_harlemnext_com/LLaVA/llava/model/language_model/llava_llama.py", line 22, in <module>
    from transformers import AutoConfig, AutoModelForCausalLM, \
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/transformers/utils/__init__.py", line 30, in <module>
    from .generic import (
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/transformers/utils/generic.py", line 29, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 34, in <module>
    from . import logging
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/transformers/utils/logging.py", line 35, in <module>
    import huggingface_hub.utils as hf_hub_utils
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/huggingface_hub/utils/__init__.py", line 32, in <module>
    from ._errors import (
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 3, in <module>
    from requests import HTTPError, Response
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/requests/packages.py", line 16, in <module>
    locals()[package] = __import__(package)
ModuleNotFoundError: No module named 'idna'
```

the module idna is installed
```pip show  idna ```
```
Name: idna
Version: 3.3
Summary: Internationalized Domain Names in Applications (IDNA)
Home-page: https://github.com/kjd/idna
Author: Kim Davies
Author-email: kim@cynosure.com.au
License: BSD-3-Clause
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: anyio, httpx, requests, yarl
```

**Comment by haotian-liu** [comment]
It seems that the packages are not installed successfully in your conda env?

 File "/home/pdelgado_harlemnext_com/anaconda3/envs/llava/lib/python3.10/runpy.py"
File "/home/pdelgado_harlemnext_com/.local/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
Location: /usr/lib/python3/dist-packages

Including transformers, and idna, especially the package idna (as it seems that it is installed in the system python, which may have version mismatch.

Theoretically all these package should be within your anaconda env.
