### ISSUE TITLE
[Question] llava_v1.5 pretrain

### ISSUE THREAD

**Issue by nj159** [haotian-liu/LLaVA#641]
### Question

excuse me，I would like to ask you that why I get the following error when pretraining v1.5，My code is: ./scripts/v1_5/pretrain.sh
output：
[2023-10-21 19:41:04,065] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-21 19:41:06,429] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-10-21 19:41:06,430] [INFO] [runner.py:555:main] cmd = /home/nj/.conda/envs/llava/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None llava/train/train_mem.py --deepspeed ./scripts/zero2.json --model_name_or_path lmsys/vicuna-7b-v1.5 --version plain --data_path ./playground/data/LLaVA-Pretrain/blip_laion_cc_sbu_558k_first500.json --image_folder ./playground/data/LLaVA-Pretrain/images --vision_tower openai/clip-vit-large-patch14-336 --mm_projector_type mlp2x_gelu --tune_mm_mlp_adapter True --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --fp16 True --output_dir ./liuhaotian2/llava-v1.5-7b-pretrain --num_train_epochs 1 --per_device_train_batch_size 32 --per_device_eval_batch_size 4 --gradient_accumulation_steps 1 --evaluation_strategy no --save_strategy steps --save_steps 24000 --save_total_limit 1 --learning_rate 1e-3 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 1 --tf32 False --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to wandb
[2023-10-21 19:41:07,902] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-21 19:41:09,817] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2023-10-21 19:41:09,817] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=4, node_rank=0
[2023-10-21 19:41:09,818] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2023-10-21 19:41:09,818] [INFO] [launch.py:163:main] dist_world_size=4
[2023-10-21 19:41:09,818] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2023-10-21 19:41:12,902] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-21 19:41:12,952] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-21 19:41:13,003] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-21 19:41:13,021] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/media/nj/data2/nj/Models/LLaVA/llava/train/llama_flash_attn_monkey_patch.py:108: UserWarning: Flash attention is only supported on A100 or H100 GPU during training due to head dim > 64 backward.ref: https://github.com/HazyResearch/flash-attention/issues/190#issuecomment-1523359593
  warnings.warn(
/media/nj/data2/nj/Models/LLaVA/llava/train/llama_flash_attn_monkey_patch.py:108: UserWarning: Flash attention is only supported on A100 or H100 GPU during training due to head dim > 64 backward.ref: https://github.com/HazyResearch/flash-attention/issues/190#issuecomment-1523359593
  warnings.warn(
/media/nj/data2/nj/Models/LLaVA/llava/train/llama_flash_attn_monkey_patch.py:108: UserWarning: Flash attention is only supported on A100 or H100 GPU during training due to head dim > 64 backward.ref: https://github.com/HazyResearch/flash-attention/issues/190#issuecomment-1523359593
  warnings.warn(
/media/nj/data2/nj/Models/LLaVA/llava/train/llama_flash_attn_monkey_patch.py:108: UserWarning: Flash attention is only supported on A100 or H100 GPU during training due to head dim > 64 backward.ref: https://github.com/HazyResearch/flash-attention/issues/190#issuecomment-1523359593
  warnings.warn(
[2023-10-21 19:41:13,693] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-10-21 19:41:13,694] [INFO] [comm.py:594:init_distributed] cdb=None
[2023-10-21 19:41:13,699] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-10-21 19:41:13,699] [INFO] [comm.py:594:init_distributed] cdb=None
[2023-10-21 19:41:13,700] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2023-10-21 19:41:13,782] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-10-21 19:41:13,782] [INFO] [comm.py:594:init_distributed] cdb=None
[2023-10-21 19:41:13,789] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-10-21 19:41:13,789] [INFO] [comm.py:594:init_distributed] cdb=None
You are using a model of type llama to instantiate a model of type llava. This is not supported for all configurations of models and can yield errors.
You are using a model of type llama to instantiate a model of type llava. This is not supported for all configurations of models and can yield errors.
You are using a model of type llama to instantiate a model of type llava. This is not supported for all configurations of models and can yield errors.
You are using a model of type llama to instantiate a model of type llava. This is not supported for all configurations of models and can yield errors.
[2023-10-21 19:41:56,780] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 10468
[2023-10-21 19:41:56,809] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 10469
[2023-10-21 19:41:57,776] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 10470
[2023-10-21 19:41:58,770] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 10471
[2023-10-21 19:41:59,773] [ERROR] [launch.py:321:sigkill_handler] ['/home/nj/.conda/envs/llava/bin/python', '-u', 'llava/train/train_mem.py', '--local_rank=3', '--deepspeed', './scripts/zero2.json', '--model_name_or_path', 'lmsys/vicuna-7b-v1.5', '--version', 'plain', '--data_path', './playground/data/LLaVA-Pretrain/blip_laion_cc_sbu_558k_first500.json', '--image_folder', './playground/data/LLaVA-Pretrain/images', '--vision_tower', 'openai/clip-vit-large-patch14-336', '--mm_projector_type', 'mlp2x_gelu', '--tune_mm_mlp_adapter', 'True', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--fp16', 'True', '--output_dir', './liuhaotian2/llava-v1.5-7b-pretrain', '--num_train_epochs', '1', '--per_device_train_batch_size', '32', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '24000', '--save_total_limit', '1', '--learning_rate', '1e-3', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'False', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = -9

**Comment by walidmbz** [comment]
any luck with this? I am having the same issue

**Comment by nj159** [comment]
> any luck with this? I am having the same issue

no,i don't know how to deal with it

**Comment by walidmbz** [comment]
I resolved it. Turns out it is actually a OOM error. in the pretrain file change zero2.json to zero3.json and it should work.

**Comment by nj159** [comment]
> 我解决了。事实证明，这实际上是一个OOM错误。在预训练文件中，将 zero2.json 更改为 zero3.json，它应该可以工作。
Thank you very much, but I have a new problem after switching to zero3.json, I don't know why?

[2023-10-23 19:50:53,106] [WARNING] [partition_parameters.py:836:_post_init_method] param `class_embedding` in CLIPVisionEmbeddings not on GPU so was not broadcasted from rank 0
[2023-10-23 19:50:53,321] [INFO] [partition_parameters.py:453:__exit__] finished initializing model with 7.04B parameters
Traceback (most recent call last):
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train_mem.py", line 13, in <module>
    Traceback (most recent call last):
train()
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 920, in train
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train_mem.py", line 13, in <module>
Traceback (most recent call last):
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train_mem.py", line 13, in <module>
    data_module = make_supervised_data_module(tokenizer=tokenizer,
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 747, in make_supervised_data_module
    train()
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 920, in train
    train()
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 920, in train
    train_dataset = LazySupervisedDataset(tokenizer=tokenizer,
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 633, in __init__
    list_data_dict = json.load(open(data_path, "r"))
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/__init__.py", line 293, in load
    data_module = make_supervised_data_module(tokenizer=tokenizer,
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 747, in make_supervised_data_module
    data_module = make_supervised_data_module(tokenizer=tokenizer,
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 747, in make_supervised_data_module
    return loads(fp.read(),
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/decoder.py", line 340, in decode
    train_dataset = LazySupervisedDataset(tokenizer=tokenizer,
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 633, in __init__
    train_dataset = LazySupervisedDataset(tokenizer=tokenizer,
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 633, in __init__
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 15 column 1 (char 358)
    list_data_dict = json.load(open(data_path, "r"))
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/__init__.py", line 293, in load
    list_data_dict = json.load(open(data_path, "r"))
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/__init__.py", line 346, in loads
    return loads(fp.read(),
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/decoder.py", line 340, in decode
    return _default_decoder.decode(s)
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 15 column 1 (char 358)
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 15 column 1 (char 358)
Traceback (most recent call last):
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 920, in train
    data_module = make_supervised_data_module(tokenizer=tokenizer,
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 747, in make_supervised_data_module
    train_dataset = LazySupervisedDataset(tokenizer=tokenizer,
  File "/media/nj/data2/nj/Models/LLaVA/llava/train/train.py", line 633, in __init__
    list_data_dict = json.load(open(data_path, "r"))
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/nj/.conda/envs/llava/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 15 column 1 (char 358)
[2023-10-23 19:51:13,558] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 19799
[2023-10-23 19:51:13,577] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 19800
[2023-10-23 19:51:13,590] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 19801
[2023-10-23 19:51:13,602] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 19802
[2023-10-23 19:51:13,602] [ERROR] [launch.py:321:sigkill_handler] ['/home/nj/.conda/envs/llava/bin/python', '-u', 'llava/train/train_mem.py', '--local_rank=3', '--deepspeed', './scripts/zero3.json', '--model_name_or_path', 'lmsys/vicuna-7b-v1.5', '--version', 'plain', '--data_path', './playground/data/LLaVA-Pretrain/blip_laion_cc_sbu_558k_first500.json', '--image_folder', './playground/data/LLaVA-Pretrain/images', '--vision_tower', 'openai/clip-vit-large-patch14-336', '--mm_projector_type', 'mlp2x_gelu', '--tune_mm_mlp_adapter', 'True', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--fp16', 'True', '--output_dir', './liuhaotian2/llava-v1.5-7b-pretrain', '--num_train_epochs', '1', '--per_device_train_batch_size', '32', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '24000', '--save_total_limit', '1', '--learning_rate', '1e-3', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'False', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = 1

**Comment by haotian-liu** [comment]
> Flash attention is only supported on A100 or H100 GPU during training due to hardware ...

Seems that you are using Flash-Attention on an  unsupported hardware? Maybe you can try `train.py` instead of `train_mem.py`, but it may have a larger memory requirement.

**Comment by nj159** [comment]
> > Flash attention is only supported on A100 or H100 GPU during training due to hardware ...
> 
> Seems that you are using Flash-Attention on an unsupported hardware? Maybe you can try `train.py` instead of `train_mem.py`, but it may have a larger memory requirement.

thank you vary much，i have solved it
