### ISSUE TITLE
[Usage] Cannot load the pretrained weight.

### ISSUE THREAD

**Issue by gemcollector** [haotian-liu/LLaVA#663]
### Describe the issue

Issue:
Hi, nice work! But I have met an issue of trying the following command when loading the pre-trained weights. 

Command:
python -m llava.serve.cli     --model-path ./pre_trained_models/llava1.5/llava-v1.5-13b/     --image-file "https://llava-vl.github.io/static/images/view.jpg"     --load-8bit

Log: 
```
[2023-10-25 12:13:37,129] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_acc[27/2031]
to cuda (auto detect)
model_name: llava-v1.5-13b
yes!
Loading checkpoint shards:   0%|                                            | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.p
y", line 460, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/site-packages/torch/serialization.py", line
 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/site-packages/torch/serialization.py", line
 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.p
y", line 464, in load_state_dict
    if f.read(7) == "version":
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/yzc/shared/project/LLaVA/llava/serve/cli.py", line 126, in <module>
    main(args)
  File "/home/yzc/shared/project/LLaVA/llava/serve/cli.py", line 33, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.m
odel_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/home/yzc/shared/project/LLaVA/llava/model/builder.py", line 104, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.p
y", line 2903, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.p
y", line 3246, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/home/yzc/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.p
y", line 476, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for './pre_trained_models/llava1.5/ll
ava-v1.5-13b/pytorch_model-00001-of-00003.bin' at './pre_trained_models/llava1.5/llava-v1.5-13b/py
torch_model-00001-of-00003.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, pl
ease set from_tf=True.

```

**Comment by White1973** [comment]
I updated PyTorch version to 2.0.1, and the issue was solved.

**Comment by gemcollector** [comment]
I think this issue mainly caused by unsuccessful downloading of the whole model. Therefore, it cannot load the model. I fix this bug by re-downloading the whole model.
