### ISSUE TITLE
[Usage] Issues with fine-tuning using pretrained weights

### ISSUE THREAD

**Issue by lzw-lzw** [haotian-liu/LLaVA#667]
### Describe the issue

Issue:
Hi, when I perform the first stage pre-training, instead of only saving the weights of the mm_projector, I save the complete weights of the model. However, when I finetune on the pretrained full weights, I got an error when loading the weights.

Command:
deepspeed llava/train/train.py
--deepspeed ./scripts/zero2.json
--model_name_or_path ./checkpoints/pretrained_vicuna7b/checkpoint-4500
--version plain
--data_path /path/dataset/LLaVA-Instruct-150K/llava_instruct_150k.json
--image_folder /path/data/coco/train2017
--vision_tower openai/clip-vit-large-patch14
--tune_mm_mlp_adapter True
--mm_vision_select_layer -2
--mm_use_im_start_end True
--mm_use_im_patch_token True
--bf16 False
--fp16 True
--output_dir ./checkpoints/finetunes_vicuna7b
--num_train_epochs 1
--per_device_train_batch_size 16
--per_device_eval_batch_size 4
--gradient_accumulation_steps 1
--evaluation_strategy "no"
--save_strategy "steps"
--save_steps 1000
--save_total_limit 1
--learning_rate 2e-5
--weight_decay 0.
--warmup_ratio 0.03
--lr_scheduler_type "cosine"
--logging_steps 1
--tf32 True
--model_max_length 2048
--gradient_checkpointing True
--dataloader_num_workers 4
--lazy_preprocess True
--report_to wandb

Log: 
```
- This IS expected if you are initializing CLIPVisionModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CLIPVisionModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading checkpoint shards:   0%|                                                                                                       | 0/2 [00:00<?, ?it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 875976 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 875977 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 875978 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 3 (pid: 875979) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tiger/.local/share/code-server/extensions/ms-python.python-2022.16.1-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/tiger/.local/share/code-server/extensions/ms-python.python-2022.16.1-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/tiger/.local/share/code-server/extensions/ms-python.python-2022.16.1-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/home/tiger/.local/share/code-server/extensions/ms-python.python-2022.16.1-universal/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tiger/.local/share/code-server/extensions/ms-python.python-2022.16.1-universal/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 996, in <module>
    main()
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 992, in main
    launch_command(args)
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 971, in launch_command
    deepspeed_launcher(args)
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 687, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```
I would like to ask what is the reason for this situation, thank you.

**Comment by Krisdddd** [comment]
Try:
ulimit -u 8192
