### ISSUE TITLE
[Usage] pip install flash-attn --no-build-isolation ERRORs

### ISSUE THREAD

**Issue by bioinfomagic** [haotian-liu/LLaVA#698]
### Describe the issue

Issue:
I had errors when run the command, "pip install flash-attn --no-build-isolation"
It seems that because I don't have cuda, I am only using the M1 max chip of mac book pro with 64GB of ram. 

Command:
```
pip install flash-attn --no-build-isolation

```

Log: 
```
Collecting flash-attn
  Using cached flash_attn-2.3.3.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /private/var/folders/r1/_sncvgk15lb_fhsrrjjhj_wh0000gn/T/pip-install-swug64eb/flash-attn_a0697bca31734576b03cf6574720853a/setup.py:79: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/r1/_sncvgk15lb_fhsrrjjhj_wh0000gn/T/pip-install-swug64eb/flash-attn_a0697bca31734576b03cf6574720853a/setup.py", line 136, in <module>
          CUDAExtension(
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1048, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2223, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      
      
      torch.__version__  = 2.0.1
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
flash-attn is not supported on Mac. Also, it is not required for running inference on Mac.
