### ISSUE TITLE
[Usage] Error while pip install -e ".[train]" 

### ISSUE THREAD

**Issue by Ryan-ZL-Lin** [haotian-liu/LLaVA#716]
### Describe the issue

Issue:
Error while pip install -e ".[train]" even though I setup CUDA_HOME in system environment and reboot, has anybody encountered the same error? 

BTW, I'm using WSL2 to setup the conda environment.

Command:
```
pip install -e ".[train]"
```

Log: 
```
Collecting deepspeed==0.9.5
  Using cached deepspeed-0.9.5.tar.gz (809 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jig9096n/deepspeed_807b83ecd8ea4b0a9adf8e88dd84130d/setup.py", line 82, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-jig9096n/deepspeed_807b83ecd8ea4b0a9adf8e88dd84130d/op_builder/builder.py", line 41, in installed_cuda_version
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Screenshots:
<img width="467" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/33056320/a7e1ae87-6f28-4ec9-a026-4a476ba431fa">

**Comment by haotian-liu** [comment]
Hi, training is currently not supported on Windows. Please try with WSL2 (which is confirmed by some other users), thanks!
