### ISSUE TITLE
[Usage]  finetune_task_lora in custom datasets, but KeyError: 'LlavaConfig'

### ISSUE THREAD

**Issue by qiuhaining** [haotian-liu/LLaVA#718]
### Describe the issue

Issue: KeyError: 'LlavaConfig'

Command:
./scripts/v1_5/finetune_task_lora.sh

Log: 

[2023-10-31 16:49:49,791] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-31 16:51:00,501] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-10-31 16:51:00,501] [INFO] [runner.py:555:main] cmd = /home/luban/miniconda3/envs/llava/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None llava/train/train_mem.py --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 --deepspeed ./scripts/zero3.json --model_name_or_path /nfs/dataset-adas/qiushi_data/LLM/llava-v1.5-13b --version v1 --data_path ./playground/data/llava_v1_5_mix665k.json --image_folder ./playground/data --vision_tower /mnt/clip-vit-large-patch14-336 --mm_projector_type mlp2x_gelu --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --image_aspect_ratio pad --group_by_modality_length True --bf16 True --output_dir ./checkpoints/llava-v1.5-13b-task-lora --num_train_epochs 1 --per_device_train_batch_size 2 --per_device_eval_batch_size 2 --gradient_accumulation_steps 1 --evaluation_strategy no --save_strategy steps --save_steps 50000 --save_total_limit 1 --learning_rate 2e-4 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 1 --tf32 True --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to wandb
[2023-10-31 16:51:09,706] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-31 16:51:25,892] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-10-31 16:51:25,892] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-10-31 16:51:25,892] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-10-31 16:51:25,892] [INFO] [launch.py:163:main] dist_world_size=1
[2023-10-31 16:51:25,892] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-10-31 16:51:43,162] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-31 16:51:58,497] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-10-31 16:51:58,497] [INFO] [comm.py:594:init_distributed] cdb=None
[2023-10-31 16:51:58,497] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:29500 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[2023-10-31 16:52:24,341] [INFO] [partition_parameters.py:453:__exit__] finished initializing model with 13.05B parameters
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [02:25<00:00, 48.62s/it]
Adding LoRA adapters...
Traceback (most recent call last):
  File "/nfs/volume-379-4/qiushi/codes/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/nfs/volume-379-4/qiushi/codes/LLaVA/llava/train/train.py", line 850, in train
    tokenizer = transformers.AutoTokenizer.from_pretrained(
  File "/home/luban/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/home/luban/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 663, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
KeyError: 'LlavaConfig'
[2023-10-31 16:58:30,440] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2885847
[2023-10-31 16:58:30,440] [ERROR] [launch.py:321:sigkill_handler] ['/home/luban/miniconda3/envs/llava/bin/python', '-u', 'llava/train/train_mem.py', '--local_rank=0', '--lora_enable', 'True', '--lora_r', '128', '--lora_alpha', '256', '--mm_projector_lr', '2e-5', '--deepspeed', './scripts/zero3.json', '--model_name_or_path', '/nfs/dataset-adas/qiushi_data/LLM/llava-v1.5-13b', '--version', 'v1', '--data_path', './playground/data/llava_v1_5_mix665k.json', '--image_folder', './playground/data', '--vision_tower', '/mnt/clip-vit-large-patch14-336', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'True', '--bf16', 'True', '--output_dir', './checkpoints/llava-v1.5-13b-task-lora', '--num_train_epochs', '1', '--per_device_train_batch_size', '2', '--per_device_eval_batch_size', '2', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '50000', '--save_total_limit', '1', '--learning_rate', '2e-4', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = 1

Screenshots:
<img width="738" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/23293902/0612ad4e-4f43-41cb-9804-89132f585583">

**Comment by haotian-liu** [comment]
Can you please check if you have the proper tokenizer config in the local folder? Thanks.

https://huggingface.co/liuhaotian/llava-v1.5-13b/blob/main/tokenizer_config.json

**Comment by qiuhaining** [comment]
> Can you please check if you have the proper tokenizer config in the local folder? Thanks.
> 
> https://huggingface.co/liuhaotian/llava-v1.5-13b/blob/main/tokenizer_config.json

 Yes，this is my tokenizer_config.json , the same to yours
'''
{
  "add_bos_token": true,
  "add_eos_token": false,
  "bos_token": {
    "__type": "AddedToken",
    "content": "<s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "clean_up_tokenization_spaces": false,
  "eos_token": {
    "__type": "AddedToken",
    "content": "</s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "legacy": false,
  "model_max_length": 2048,
  "pad_token": null,
  "padding_side": "right",
  "sp_model_kwargs": {},
  "tokenizer_class": "LlamaTokenizer",
  "unk_token": {
    "__type": "AddedToken",
    "content": "<unk>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  }
}
'''

**Comment by haotian-liu** [comment]
This is strange. What if you manually load from this directory: `transformers.AutoTokenizer.from_pretrained('xxx')`? I don't see why it will try to find something related to `llava`

> tokenizer = transformers.AutoTokenizer.from_pretrained(
> File "/home/luban/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
> tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
> File "/home/luban/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 663, in getitem
> model_type = self._reverse_config_mapping[key.name]
> KeyError: 'LlavaConfig'

**Comment by qiuhaining** [comment]
> This is strange. What if you manually load from this directory: `transformers.AutoTokenizer.from_pretrained('xxx')`? I don't see why it will try to find something related to `llava`
> 
> > tokenizer = transformers.AutoTokenizer.from_pretrained(
> > File "/home/luban/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
> > tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
> > File "/home/luban/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 663, in getitem
> > model_type = self._reverse_config_mapping[key.name]
> > KeyError: 'LlavaConfig'

I found something maybe related to this problem.
1、  tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)， tokenizer_config == {}

**Comment by qiuhaining** [comment]
its my fault for not have “tokenizer_config.json” in local dir
