### ISSUE TITLE
[Usage] RuntimeError: Error(s) in loading state_dict for Linear:

### ISSUE THREAD

**Issue by Road2Redemption** [haotian-liu/LLaVA#728]
### Describe the issue

Issue:
Thanks to your contribution to the work! I met some issues while training.
I want to finetune the llava-llama2-7b-chat model on custom data. I used a two step finetuning process: I firstly did finetune-lora on one dataset, and got the lora weights and then merged them as llava-llama2-7b-chat-MERGE. Then I wanted to use the MERGE model to train on another dataset, and when I did this, there is something wrong with my adaptor.
Command:
```
#!/bin/bash

# Uncomment and set the following variables correspondingly to run this script:

################## VICUNA ##################
# PROMPT_VERSION=v1
# MODEL_VERSION="vicuna-v1-3-7b"
################## VICUNA ##################

################## LLaMA-2 ##################
PROMPT_VERSION="llava_llama_2"
MODEL_VERSION="llama-2-7b-chat"
################## LLaMA-2 ##################

deepspeed --num_gpus=2 llava/train/train_mem.py \
    --deepspeed ./scripts/zero3_offload.json \
    --lora_enable True \
    --model_name_or_path /data6/xyc/chartcaption/LLaVA/checkpoints/llava-llama-2-7b-chat-finetune_lora-MERGE \
    --version $PROMPT_VERSION \
    --data_path ./playground/data/vistext_train_full.json \
    --image_folder /data6/xyc/chartcaption/vistext/data/baseline_data-v2/train \
    --vision_tower ./openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter /data6/xyc/models/llava-$MODEL_VERSION-pretrain/mm_projector.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-$MODEL_VERSION-finetune_lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

Log: 
```
Adding LoRA adapters...
[2023-11-01 04:16:24,003] [WARNING] [partition_parameters.py:836:_post_init_method] param `class_embedding` in CLIPVisionEmbeddings not on GPU so was not broadcasted from rank 0
[2023-11-01 04:16:25,785] [INFO] [partition_parameters.py:453:__exit__] finished initializing model with 7.05B parameters
Traceback (most recent call last):
  File "/data6/xyc/chartcaption/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/data6/xyc/chartcaption/LLaVA/llava/train/train.py", line 875, in train
    model.get_model().initialize_vision_modules(
  File "/data6/xyc/chartcaption/LLaVA/llava/model/llava_arch.py", line 82, in initialize_vision_modules
    self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Linear:
	size mismatch for weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([0]).
	size mismatch for bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).
Traceback (most recent call last):
  File "/data6/xyc/chartcaption/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/data6/xyc/chartcaption/LLaVA/llava/train/train.py", line 875, in train
    model.get_model().initialize_vision_modules(
  File "/data6/xyc/chartcaption/LLaVA/llava/model/llava_arch.py", line 82, in initialize_vision_modules
    self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Linear:
	size mismatch for weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([0]).
	size mismatch for bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).
[2023-11-01 04:16:31,040] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1912392
[2023-11-01 04:16:31,136] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1912393
[2023-11-01 04:16:31,136] [ERROR] [launch.py:321:sigkill_handler] ['/opt/conda/envs/llava/bin/python', '-u', 'llava/train/train_mem.py', '--local_rank=1', '--deepspeed', './scripts/zero3_offload.json', '--lora_enable', 'True', '--model_name_or_path', '/data6/xyc/chartcaption/LLaVA/checkpoints/llava-llama-2-7b-chat-finetune_lora-MERGE', '--version', 'llava_llama_2', '--data_path', './playground/data/vistext_train_full.json', '--image_folder', '/data6/xyc/chartcaption/vistext/data/baseline_data-v2/train', '--vision_tower', './openai/clip-vit-large-patch14', '--pretrain_mm_mlp_adapter', '/data6/xyc/models/llava-llama-2-7b-chat-pretrain/mm_projector.bin', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--bf16', 'True', '--output_dir', './checkpoints/llava-llama-2-7b-chat-finetune_lora', '--num_train_epochs', '1', '--per_device_train_batch_size', '16', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '50000', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = 1
```
![image](https://github.com/haotian-liu/LLaVA/assets/114891845/bffeb5e8-10aa-4344-943d-3dc8e5e9bdc6)
![image](https://github.com/haotian-liu/LLaVA/assets/114891845/159e9781-4e00-4cbf-968b-6897634886b5)

I am not quite familiar about how the adaptor works, is there any solution to this? Thanks a lot!

**Comment by Road2Redemption** [comment]
--pretrain_mm_mlp_adapter /data6/xyc/models/llava-$MODEL_VERSION-pretrain/mm_projector.bin \
when I deleted this line, the training works, but I am afraid that the performance will be not as good as that with the adaptor.

**Comment by Road2Redemption** [comment]
ummm I changed zero3_offload to zero2 and it also worked

**Comment by kindasweetgal** [comment]
I have the same question, I don't understand why

**Comment by JJJoeha** [comment]
same issue here, any updates?

**Comment by 459737087** [comment]
same issue

**Comment by zhang9302002** [comment]
same issue, dun

**Comment by Road2Redemption** [comment]
I saw on other issues that the --pretrain_mm_mlp_adapter is used only for fine tuning after LLaVA's own pretraining. If continuous task fine tuning on our own custom dataset, this parameter should not be included.

However I am still not sure how the deepseed zero2/zero3_offload affects this problem T_T

**Comment by zhang9302002** [comment]
Guys, It seems that deepspeed zero3 will do a lazy parameter initialization. So in our main() function, the parameters of model are set to [ ]. It cannot be reload from --pretrain_mm_mlp_adapter.
I solve this by use full deepspeed ckpt, instead of --pretrain_mm_mlp_adapter, Have a try.

**Comment by xinyuliu-jeffrey** [comment]
@zhang9302002 Could you please share how to load pretrain mlp without --pretrain_mm_mlp_adapter? Thanks.

**Comment by zhang9302002** [comment]
@xinyuliu-jeffrey If you are using deepspeed, use `--model_name_or_path your_model/checkpoint-3000` argument to let deepspeed load the full model itself.
BTW, I suggest comment `def _save_checkpoint()` and `def _save()` in llava_trainer.py to avoid overriding original deepspeed implementation.

**Comment by xinyuliu-jeffrey** [comment]
@zhang9302002 Thanks! I saved full model with deepseed and the pretrained weights can be successfully loaded. Only adapter will be saved when `--tune_mm_mlp_adapter` is True, so these functions shall be indeed commented.
