### ISSUE TITLE
[Usage] How to load fine-tuned lora checkpoint for CLI inference

### ISSUE THREAD

**Issue by pipilurj** [haotian-liu/LLaVA#730]
### Describe the issue

Issue:

Hi! Could you explain how to load the model weights for lora after fine-tuning? Also the mm_projector seems to need be separately loaded? I did not find an argument to specify the path to the mm_projector for cli inference. Thanks for your help!

**Comment by baiyuting** [comment]
does the scripts/finetune_lora.sh tune the mm_projector ?  or Just the LLM? I am also trying to fine-tuned with lora, but a little bit confused with the setting

**Comment by Nomiluks** [comment]
Have you got any solution to load the fine-tuned model using LORA?

**Comment by Nomiluks** [comment]
I am able to load the model using the following parameters:

```
python -m llava.serve.cli --model-path /home/user/LLaVA/checkpoints/llava-v1.5-13b-task-lora --model-base /home/user/llava-v1.5-7b --image-file "/home/user/LLaVA/digital_tampering/test_data/image.jpeg"
```

**Comment by SoniaGrh** [comment]
Try to use the Predictor class in the file [predict.py](https://github.com/haotian-liu/LLaVA/blob/main/predict.py) and replace the setup function of the class with this:

`def setup(self) -> None:`
`
        self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model("checkpoints/llava-v1.5-13b-task-lora", model_name="llava-v1.5-13b-lora-finetuned", model_base="liuhaotian/llava-v1.5-13b", load_8bit=False, load_4bit=False)
`

(If you have 'lora' in the model_name, you don't need the mm_projector)

It is working for me after launching this finetune script [scripts/v1_5/finetune_task_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh) with my own parameters.

**Comment by hai-qi** [comment]
> 我可以使用以下命令加载模型：
> 
> ```
> python -m llava.serve.cli --model-path /home/user/LLaVA/checkpoints/llava-v1.5-13b-task-lora --model-base /home/user/llava-v1.5-7b --image-file "/home/user/LLaVA/digital_tampering/test_data/image.jpeg"
> ```

When I use this command for inference, the following error occurs, but this file is missing from the fine-tuned file. What is the reason?
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/llava-data_know/mm_projector.bin'

**Comment by SoniaGrh** [comment]
> > 我可以使用以下命令加载模型：
> > ```
> > python -m llava.serve.cli --model-path /home/user/LLaVA/checkpoints/llava-v1.5-13b-task-lora --model-base /home/user/llava-v1.5-7b --image-file "/home/user/LLaVA/digital_tampering/test_data/image.jpeg"
> > ```
> 
> When I use this command for inference, the following error occurs, but this file is missing from the fine-tuned file. What is the reason? FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/llava-data_know/mm_projector.bin'

You need to give the parameter model-name with the string 'lora' in the name, for example model_name="llava-v1.5-13b-lora-finetuned". Then the script will understand that it is a different type of model.

**Comment by hai-qi** [comment]
> > > 我可以使用以下命令加载模型：
> > > ```
> > > python -m llava.serve.cli --model-path /home/user/LLaVA/checkpoints/llava-v1.5-13b-task-lora --model-base /home/user/llava-v1.5-7b --image-file "/home/user/LLaVA/digital_tampering/test_data/image.jpeg"
> > > ```
> > 
> > 
> > When I use this command for inference, the following error occurs, but this file is missing from the fine-tuned file. What is the reason? FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/llava-data_know/mm_projector.bin'
> 
> You need to give the parameter model-name with the string 'lora' in the name, for example model_name="llava-v1.5-13b-lora-finetuned". Then the script will understand that it is a different type of model.

Thank you very much for your reply, I will be able to use it after adding it.

**Comment by Nomiluks** [comment]
> @Nomiluks could you produce a slightly more full example than what is found in https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md ? It looks like you were successful at training a LoRA and saving a checkpoint.
> 
> I would like to run https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh
> 
> But there are no instructions provided as to which parameter is the images directory, and then which JSON is your custom dataset as indicated in Finetune_Custom_Data.md
> 
> What is deepspeed ./scripts/zero3.json \
> 
> And is there documentation on the 37 command line flags here? I'd love to see just a minimal tutorial that I could follow since I was able to successfully prepare a custom dataset


**Following things I did:**
note: Please make sure you have installed the necessary dependencies and you have an activated conda environment.
1. Update the `finetune_task_lora.sh`:
>  --data_path ./playground/data/complete_normalized_training_with_paths.json
> --image_folder ./playground/data/images 
> --output_dir ./checkpoints/llava-v1.5-7b-task-lora
> --per_device_train_batch_size 12 ----> Due to memory constraints

2. conda activate llava
 
3. Run the script : bash scripts/v1_5/finetune_task_lora.sh

4. Model test: python -m llava.serve.cli --model-path "checkpoints/llava-v1.5-7b-task-lora" --model-base "llava-v1.5-7b" --image-file "training_data/test_cropped_document_samples/6599560327fb1c3dc1155689/front/front.jpg"

**Comment by Nomiluks** [comment]
> Try to use the Predictor class in the file [predict.py](https://github.com/haotian-liu/LLaVA/blob/main/predict.py) and replace the setup function of the class with this:
> 
> `def setup(self) -> None:` `self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model("checkpoints/llava-v1.5-13b-task-lora", model_name="llava-v1.5-13b-lora-finetuned", model_base="liuhaotian/llava-v1.5-13b", load_8bit=False, load_4bit=False)`
> 
> (If you have 'lora' in the model_name, you don't need the mm_projector)
> 
> It is working for me after launching this finetune script [scripts/v1_5/finetune_task_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh) with my own parameters.

I want to load the model predict without the conversation behavior. 
I used your suggestion, but I am facing the following error:

`ModuleNotFoundError: No module named 'cog'`

Could you please help me to resolve this error?

**Comment by SoniaGrh** [comment]
> > Try to use the Predictor class in the file [predict.py](https://github.com/haotian-liu/LLaVA/blob/main/predict.py) and replace the setup function of the class with this:
> > `def setup(self) -> None:` `self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model("checkpoints/llava-v1.5-13b-task-lora", model_name="llava-v1.5-13b-lora-finetuned", model_base="liuhaotian/llava-v1.5-13b", load_8bit=False, load_4bit=False)`
> > (If you have 'lora' in the model_name, you don't need the mm_projector)
> > It is working for me after launching this finetune script [scripts/v1_5/finetune_task_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh) with my own parameters.
> 
> I want to load the model predict without the conversation behavior. I used your suggestion, but I am facing the following error:
> 
> `ModuleNotFoundError: No module named 'cog'`
> 
> Could you please help me to resolve this error?

It doesn't resolve the error to install this package: [cog](https://pypi.org/project/cog/) ?

**Comment by conheaven** [comment]
> > @Nomiluks could you produce a slightly more full example than what is found in https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md ? It looks like you were successful at training a LoRA and saving a checkpoint.你能提供一个比https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md更完整的例子吗?看起来你成功地训练了一个LoRA并保存了一个检查点。
> > I would like to run https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh我想跑https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh
> > But there are no instructions provided as to which parameter is the images directory, and then which JSON is your custom dataset as indicated in Finetune_Custom_Data.md但是没有说明哪个参数是图像目录，然后哪个JSON是您的自定义数据集，如Finetune_Custom_Data.md所示
> > What is deepspeed ./scripts/zero3.json \什么是deepspeed ./scripts/zero3。json \
> > And is there documentation on the 37 command line flags here? I'd love to see just a minimal tutorial that I could follow since I was able to successfully prepare a custom dataset这里有关于37个命令行标志的文档吗?我希望看到一个最小的教程，我可以遵循，因为我能够成功地准备一个自定义数据集
> 
> **Following things I did: 我做了以下事情:** note: Please make sure you have installed the necessary dependencies and you have an activated conda environment.注意:请确保您已经安装了必要的依赖项，并且您有一个激活的conda环境。
> 
> 1. Update the `finetune_task_lora.sh`:   更新:
> 
> > --data_path ./playground/data/complete_normalized_training_with_paths.json——data_path。/操场/数据/ complete_normalized_training_with_paths.json
> > --image_folder ./playground/data/images——image_folder。/操场/数据/图像
> > --output_dir ./checkpoints/llava-v1.5-7b-task-lora——output_dir。/检查点/ llava-v1.5-7b-task-lora
> > --per_device_train_batch_size 12 ----> Due to memory constraints——per_device_train_batch_size 12 ---->由于内存限制
> 
> 2. conda activate llava   康达激活熔岩
> 3. Run the script : bash scripts/v1_5/finetune_task_lora.sh执行如下脚本:bash scripts/v1_5/finetune_task_lora.sh
> 4. Model test: python -m llava.serve.cli --model-path "checkpoints/llava-v1.5-7b-task-lora" --model-base "llava-v1.5-7b" --image-file "training_data/test_cropped_document_samples/6599560327fb1c3dc1155689/front/front.jpg"模型测试:python -m llava. server .cli——模型路径“检查点/llava-v1.5-7b-任务-lora”——模型基础“llava-v1.5-7b”——图像文件“training_data/test_cropped_document_samples/6599560327fb1c3dc1155689/front/front.jpg”

in the 4. my command is "python -m llava.serve.cli \
    --model-base /data1/khw/llava \
    --model-path /data1/khw/output_llava/merge_model-lora \
    --image-file /data1/khw/img/1.jpg \"
    but it show
    Traceback (most recent call last):
  File "/home/khw/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/khw/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/khw/llava/LLaVA/llava/serve/cli.py", line 126, in <module>
    main(args)
  File "/home/khw/llava/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/home/khw/llava/LLaVA/llava/model/builder.py", line 122, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, **kwargs)
  File "/home/khw/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, LlavaConfig, LlavaMptConfig, LlavaMistralConfig.

could you help me? thank you in advance

**Comment by iremonur** [comment]
Hi @conheaven,

I got the same error, did you find a solution?

**Comment by conheaven** [comment]
> Hi @conheaven,
> 
> I got the same error, did you find a solution?

sorry, i didn't find any feasible solution

**Comment by lowestbuaaer** [comment]
Just use the "scripts/merge_lora_weights.py" to merge lora checkpoints into models before inference.
Guidance:https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md
