### ISSUE TITLE
facing issue while running finetuning script (v1.5 - lora) - AttributeError: 'DummyScheduler' object has no attribute 'get_last_lr'.

### ISSUE THREAD

**Issue by csvlrs-lak** [haotian-liu/LLaVA#746]
### Describe the issue

Issue:
AttributeError: 'DummyScheduler' object has no attribute 'get_last_lr'.

Command:
```
sh scripts/v1_5/finetune_lora.sh
 ```

Log: 
```
Traceback (most recent call last):
  File "llava/train/train.py", line 956, in <module>
    train()
  File "llava/train/train.py", line 934, in train
    trainer.train()
  File "/home/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/.local/lib/python3.8/site-packages/transformers/trainer.py", line 2011, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/.local/lib/python3.8/site-packages/transformers/trainer.py", line 2292, in _maybe_log_save_evaluate
    logs["learning_rate"] = self._get_learning_rate()
  File "/home/.local/lib/python3.8/site-packages/transformers/trainer_pt_utils.py", line 846, in _get_learning_rate
    last_lr = self.lr_scheduler.get_last_lr()[0]
AttributeError: 'DummyScheduler' object has no attribute 'get_last_lr'.
```

**Comment by haotian-liu** [comment]
Hi, it seems that the environment is not in Conda and may have package version mismatch issues.

Please follow the instructions here to create a new environment for LLaVA: https://github.com/haotian-liu/LLaVA#install

**Comment by csvlrs-lak** [comment]
Thank you for the response @haotian-liu. I will try the fix suggested!!

**Comment by csvlrs-lak** [comment]
worked!!

**Comment by csvlrs-lak** [comment]
Not sure how, getting this error again!!
