### ISSUE TITLE
[Usage] Model eval.py Out of Memory error when running model eval on T4 but not RTX 3050Ti 

### ISSUE THREAD

**Issue by yikun-chi** [haotian-liu/LLaVA#756]
### Describe the issue

Issue: 

Hi, I am trying to run the model_vqa.py for some test. My input only contains one image and one prompt. Right now on my own laptop (RTX 3050Ti) GPU, I was able to successfully run the model_vqa.py. But when I move the same input and prompt to a Vertex workbench with NVIDIA T4 GPU, I got the out of memory error. Also if I use the CLI inference process laid out in CLI Inference section, I was able to run and ask the prompt. 

Given the model_vqa.py finished running on RTX 3050Ti, I am not sure why it would fail with T4 GPU. Any recommendation on how to start debugging this process would be appreciated. Thanks! 

 

Command:
```
python model_vqa.py \
    --model-path ./checkpoints/llava-v1.5-7b \
    --question-file \
    playground/data/cellphone_screenshot_eval/prompt/cellphone_screenshot_questions.jsonl \
    --image-folder \
    playground/data/cellphone_screenshot_eval/images \
    --answers-file \
    playground/data/cellphone_screenshot_eval/answer.jsonl
```

Log: 
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:18<00:00, 39.11s/it]
  0%|                                                                                                                                                           | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/jupyter/yc/LLaVA/model_vqa.py", line 112, in <module>
    eval_model(args)
  File "/home/jupyter/yc/LLaVA/model_vqa.py", line 66, in eval_model
    output_ids = model.generate(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/yc/LLaVA/llava/model/language_model/llava_llama.py", line 78, in forward
    outputs = self.model(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 346, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 14.58 GiB total capacity; 13.54 GiB already allocated; 13.38 MiB free; 13.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
It should require 24GB to run with full precision. You can try using 4-bit quantization on T4 (and it will even fit 13B model).

https://huggingface.co/spaces/badayvedat/LLaVA

**Comment by yikun-chi** [comment]
Thanks for the response! I guess my confusion is how did the process finish in RTX 3050Ti, which only has 4GB of memory?

**Comment by haotian-liu** [comment]
Were you running it on Linux or Windows?

**Comment by yikun-chi** [comment]
Laptop is Windows, but the process was run in Ubuntu through WSL

**Comment by haotian-liu** [comment]
I noticed that on Windows, it uses part of the CPU RAM as sort of SWAP for the VRAM. Not sure if this transfer towards WSL as well -- you may check when you run the program, does your CPU RAM goes up by around 10GB?

**Comment by yikun-chi** [comment]
I see. Interesting property, that's probably it. . Yeah, the PC has 32 GB of RAM. Closing the issue. Thank you so much for your help!
