### ISSUE TITLE
[Question] size mismatch for mm_projector

### ISSUE THREAD

**Issue by mengjiexu** [haotian-liu/LLaVA#775]
### Question

the error:
'''
```
image features: tensor([[[ 0.4863, -0.5620,  0.2654,  ...,  0.3267,  0.1172,  0.2654],
         [ 0.2347, -0.2360,  0.3865,  ...,  0.6465,  0.9463,  0.1743],
         [ 1.7607,  1.1641, -0.4541,  ...,  2.9082, -0.4727,  1.9062],
         ...,
         [ 1.6406,  1.4521,  0.0803,  ...,  2.3066, -0.6611,  1.5059],
         [ 1.6182,  1.1221, -0.3940,  ...,  2.7715, -0.3125,  1.8516],
         [ 0.2793,  0.3804,  0.5850,  ...,  0.5508,  0.4658,  0.1287]]],
       device='cuda:0', dtype=torch.float16) torch.Size([1, 576, 1024])
mm_projector: Sequential(
  (0): Linear4bit(in_features=1024, out_features=5120, bias=True)
  (1): GELU(approximate='none')
  (2): Linear4bit(in_features=5120, out_features=5120, bias=True)
)
Traceback (most recent call last):
  File "/home/xmj/projects/LLaVA/llava/eval/test.py", line 111, in <module>
    output_ids = model.generate(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1538, in generate
    return self.greedy_search(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2362, in greedy_search
    outputs = self(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/projects/LLaVA/llava/model/language_model/llava_llama.py", line 79, in forward
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/home/xmj/projects/LLaVA/llava/model/llava_arch.py", line 124, in prepare_inputs_labels_for_multimodal
    image_features = self.encode_images(images)
  File "/home/xmj/projects/LLaVA/llava/model/llava_arch.py", line 98, in encode_images
    image_features = self.get_model().mm_projector(image_features)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 248, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 516, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, state).to(A.dtype).t(), bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (576x1024 and 1x2621440)
```
the origin code is:
`

class LlavaMetaForCausalLM(ABC):

    def encode_images(self, images):
        image_features = self.get_model().get_vision_tower()(images)
        print('image features:', image_features, image_features.shape)
        print('mm_projector:', self.get_model().mm_projector)
        image_features = self.get_model().mm_projector(image_features)
        print('image features2:', image_features, image_features.shape)
        return image_features

`
why the image features can't multiply with the mm_projector weights?

**Comment by devaansh100** [comment]
Hello! I faced this error too. [This thread](https://github.com/haotian-liu/LLaVA/issues/744) helped me out

**Comment by mengjiexu** [comment]
this is because code wrong.

**Comment by haotian-liu** [comment]
@mengjiexu 

Can you share how you fixed it? It would be beneficial to the community if we can incorporate the fix. Thanks.

**Comment by mengjiexu** [comment]
I used myself code to load the mm_projector.bin again after the load_model func, so it is wrong, I remove the code then the model is normal.

**Comment by mikeogezi** [comment]
@mengjiexu Could you share the code you used to reload mm_projector?
