### ISSUE TITLE
run_llava.py may need modify after switch transformers?

### ISSUE THREAD

**Issue by tensorboy** [haotian-liu/LLaVA#78]
The error after I switch to transformers from transformers by:
```
pip uninstall transformers
pip install git+https://github.com/huggingface/transformers@cae78c46
```
https://github.com/haotian-liu/LLaVA/blob/main/llava/eval/run_llava.py

```
python -m llava.eval.run_llava \
>     --model-name /mnt/bd/data-tns-algo-masp-llm/weights/llama-dl-main/LLaVA-13B-v0 \
>     --image-file "https://llava-vl.github.io/static/images/view.jpg" \
>     --query "What are the things I should be cautious about when I visit here?"

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████| 3/3 [00:16<00:00,  5.36s/it]
Traceback (most recent call last):
  File "/mnt/bd/data-tns-algo-masp-llm/environment/anaconda3/envs/caption/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/bd/data-tns-algo-masp-llm/environment/anaconda3/envs/caption/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/bd/data-tns-algo-masp-llm/experiment/LLaVA/llava/eval/run_llava.py", line 164, in <module>
    eval_model(args)
  File "/mnt/bd/data-tns-algo-masp-llm/experiment/LLaVA/llava/eval/run_llava.py", line 65, in eval_model
    vision_tower = model.model.vision_tower[0]
  File "/mnt/bd/data-tns-algo-masp-llm/environment/anaconda3/envs/caption/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaModel' object has no attribute 'vision_tower'
```

**Comment by haotian-liu** [comment]
Thanks for the feedback, it has been fixed now :)
