### ISSUE TITLE
[Usage] RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by RicRicci22** [haotian-liu/LLaVA#780]
### Describe the issue

Issue: I pulled last commits from the repo, tried to run cli inference, the network is creating NaN as probability outputs.

Command:
```
python -m llava.serve.cli --model-path liuhaotian/llava-v1.5-7b --image-file "https://llava-vl.github.io/static/images/view.jpg"     --load-4bit
```

I also tried to create a fresh environment, still same bug. 
I explored the token in input to the network, and I noticed a strange -200 token. Not sure if this is causing the issue, maybe someone can have a look? I'm trying to debug it and come here if I have news! 

Log: 
```
Traceback (most recent call last):
  File "/home/riccardoricci/miniconda3/envs/chat_osm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/riccardoricci/miniconda3/envs/chat_osm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/data/Riccardo/chat_with_OSM/LLaVA/llava/serve/cli.py", line 125, in <module>
    main(args)
  File "/media/data/Riccardo/chat_with_OSM/LLaVA/llava/serve/cli.py", line 95, in main
    output_ids = model.generate(
  File "/home/riccardoricci/miniconda3/envs/chat_osm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/riccardoricci/miniconda3/envs/chat_osm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/riccardoricci/miniconda3/envs/chat_osm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2678, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

![image](https://github.com/haotian-liu/LLaVA/assets/44427504/18b080df-a642-4782-8839-6dfc0a06b764)

**Comment by crazycth** [comment]
+1 , I met the same problem here 

I output the input_ids:
```
[DEBUG] input_ids: tensor([[    1,   319, 13563,  1546,   263, 12758,  5199,   322,   385, 23116,
         21082, 20255, 29889,   450, 20255,  4076,  8444, 29892, 13173, 29892,
           322,  1248,   568,  6089,   304,   278,  5199, 29915, 29879,  5155,
         29889,  3148,  1001, 29901, 29871,  -200, 29871,    13,  5816, 29915,
         29879,   445,  1967,  1048,   319,  1799,  9047, 13566, 29901]],
       device='cuda:0')
```

**Comment by RicRicci22** [comment]
Follow up, still I don't know the origin of the issue.. 

Tried to do input_ids = torch.abs(input_ids) before generate in cli.py.

Interesting fact: 
size of input embeddings (before line 90 in llava_llama.py) changes.

with torch.abs()
input embeds -> torch.Size([1, 45, 4096])

without
input embeds: torch.Size([1, 620, 4096])

Still don't know the issue..

**Comment by RicRicci22** [comment]
Just discovered that token -200 is the image token.. So, my guess is that it is a tokenization problem! 

Just look at the size of the input_embeds with the "correct tokens"

**Comment by crazycth** [comment]
-200 is the image token and don't change that

Is the problem with weights ? have you tried lora and it works well?

**Comment by RicRicci22** [comment]
Just discovered that the gradio interface works fine if I do
export CUDA_VISIBLE_DEVICES=0 when starting the model worker. Otherwise it completely freezes the workstation.

Instead in cli.py, after doing export CUDA_VISIBLE_DEVICES=0, I receive the above mentioned error: 
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by ntoxeg** [comment]
I had to add a bunch of arguments (missing in the README) to the arguments object and it turns out I get this error when `”num_beams” > 1`. Like this:
```
       "temperature": 0.2,
       "top_p": 0.5,
       "num_beams": 1,
       "max_new_tokens": 300,
```

**Comment by waltonfuture** [comment]
@haotian-liu
same question. Can you help us on it?

**Comment by user074** [comment]
Okay. I think I solved it through change the dtype in cli.py, basically I changed `dtype=torch.float16` to `dtype=torch.bfloat16`. I think you also can change it to float32. Also you need to change the model dtype. For me I added `model.to(dtype=torch.bfloat16)` but there are probably more elegant way to handle this.

The issue is probably related to the float16 causing overflow as the [issue here](https://github.com/haotian-liu/LLaVA/issues/463#issuecomment-1788226258)

**Comment by ghazalsaheb** [comment]
I have been facing the same issue.

**Comment by ghazalsaheb** [comment]
Update: I was able to resolve the issue by changing the base model from hugging face's "llava-hf/llava-1.5-7b-hf"to "liuhaotian/llava-v1.5-7b". It resolved the NaN issue and the training performance got much better.
