### ISSUE TITLE
Error when training finetune_qlora_13b.sh :only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by mengjiexu** [haotian-liu/LLaVA#783]
### Describe the issue

The Error:
`[2023-11-10 09:35:37,861] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:35<00:00, 11.70s/it]
Adding LoRA adapters...
Traceback (most recent call last):
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/train/train.py", line 874, in train
    model.get_model().initialize_vision_modules(
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/model/llava_arch.py", line 76, in initialize_vision_modules
    p.requires_grad = True
RuntimeError: only Tensors of floating point and complex dtype can require gradients`

The train script:
`deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --lora_enable True --bits 8 \
    --model_name_or_path LLaVA/llava-v1.5-13b \
    --version $PROMPT_VERSION \
    --data_path LLaVA/llava_instruct_80k.json \
    --image_folder COCO/train2017 \
    --vision_tower LLaVA/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter LLaVA/llava-v1.5-13b/mm_projector.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-$MODEL_VERSION-finetune_lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 32 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 100 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --dataloader_num_workers 4`

Why it shows this error? I used pip install the training environment and run the finetune_qlora_13b.sh.

**Comment by haotian-liu** [comment]
Hi, does https://github.com/haotian-liu/LLaVA/commit/8467850a63aa0d6f47aa150c53aca4751f0d3d14 fix the issue?

**Comment by mengjiexu** [comment]
yes, it fix the problem, but another error occus:
  ```
0%|                                                                                                                                                                                                                      | 0/80000 [00:00<?, ?it/s]/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:322: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/train/train.py", line 933, in train
    trainer.train()
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1735, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/model/language_model/llava_llama.py", line 88, in forward
    return super().forward(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 685, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 681, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 305, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/peft/tuners/lora.py", line 1076, in forward
    self.lora_A[self.active_adapter](self.lora_dropout[self.active_adapter](x))
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found BFloat16
```

**Comment by mengjiexu** [comment]
I turn off the bfloat16 use: --bfloat False , but it shows Error:

```
Rank: 0 partition count [1, 1, 1] and sizes[(319815680, False), (20971520, False), (8192, False)] 
  0%|                                                                                                                                                                                                                      | 0/80000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/train/train.py", line 933, in train
    trainer.train()
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1735, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/model/language_model/llava_llama.py", line 79, in forward
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/model/llava_arch.py", line 129, in prepare_inputs_labels_for_multimodal
    image_features = self.encode_images(images)
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/model/llava_arch.py", line 103, in encode_images
    image_features = self.get_model().get_vision_tower()(images)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/model/multimodal_encoder/clip_encoder.py", line 48, in forward
    image_forward_outs = self.vision_tower(images.to(device=self.device, dtype=self.dtype), output_hidden_states=True)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 941, in forward
    return self.vision_model(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 867, in forward
    hidden_states = self.pre_layrnorm(hidden_states)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float
```

**Comment by a2382625920** [comment]
Hi, I'm experiencing the same error, has the error been resolved yet?

**Comment by hanoonaR** [comment]
Hi @haotian-liu , @mengjiexu 

Do you have any suggestions on how to solve this issue in qLoRA training with `--lora_r 128 --lora_alpha 256 --bits 8 --bf16 True --tf32 True`

return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found BFloat16

Thank you in advance.

**Comment by mengjiexu** [comment]
> Hi @haotian-liu , @mengjiexu
> 
> Do you have any suggestions on how to solve this issue in qLoRA training with `--lora_r 128 --lora_alpha 256 --bits 8 --bf16 True --tf32 True`
> 
> return F.linear(input, self.weight, self.bias) RuntimeError: expected scalar type Float but found BFloat16
> 
> Thank you in advance.

you can add code below in the F.linear:
`
if self.weight.dtype != input.dtype:
    input = input.to(self.weight.dtype)
`

**Comment by attnmamba** [comment]
@mengjiexu Did you finally solve the problem?

**Comment by mengjiexu** [comment]
https://github.com/haotian-liu/LLaVA/issues/783#issuecomment-1913075499

**Comment by hanoonaR** [comment]
The best solution I could find for this issue is: https://github.com/huggingface/peft/pull/874/files.

**Comment by sudan94** [comment]
I encountered a similar issue when fine-tuning DistilBERT for classification task, and I managed to resolve it using the following configuration:

```python
bnb_config = BitsAndBytesConfig(
  load_in_4bit=True,
  bnb_4bit_use_double_quant=True,
  bnb_4bit_quant_type="nf4",
  bnb_4bit_compute_dtype='int8',
)```
The addition of ```bnb_4bit_compute_dtype='int8'``` specifically resolves the issue by using int8 data type for computation.
