### ISSUE TITLE
train finetune_qlora_7b.sh error: RuntimeError: expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by mengjiexu** [haotian-liu/LLaVA#785]
### Question

Error is:
```
Formatting inputs...Skip in lazy mode
Rank: 0 partition count [1, 1, 1] and sizes[(319815680, False), (20971520, False), (8192, False)] 
  0%|          | 0/80000 [00:00<?, ?it/s]/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:322: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/train/train.py", line 936, in train
    trainer.train()
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1735, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava/model/language_model/llava_llama.py", line 88, in forward
    return super().forward(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 685, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 681, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 305, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/peft/tuners/lora.py", line 1076, in forward
    self.lora_A[self.active_adapter](self.lora_dropout[self.active_adapter](x))
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found BFloat16
```
the train config:
```
deepspeed llava/train/train_mem.py \
    --lora_enable True --bits 8 --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path /home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava-v1.5-7b \
    --version v1 \
    --data_path /home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava_instruct_80k.json \
    --image_folder /home/xmj/mycipan2/COCO/train2017 \
    --vision_tower /home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/llava-v1.5-7b/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-7b-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True
```

**Comment by mengjiexu** [comment]
the training log is 
[log.txt](https://github.com/haotian-liu/LLaVA/files/13316131/log.txt)

**Comment by mengjiexu** [comment]
I find the some of the linear layers' input becomes tf.float32, I don't know why, and  forced conversion to bfloat16 , then it can run.

**Comment by mengjiexu** [comment]
the param list shows after every lora.A.weight layer, the data willl become tf.float32:

base_model.model.model.layers.7.self_attn.q_proj.lora_A.default.weight ------- torch.Size([128, 4096]) torch.bfloat16
base_model.model.model.layers.7.self_attn.q_proj.lora_B.default.weight ------- torch.Size([4096, 128]) torch.bfloat16
base_model.model.model.layers.7.self_attn.k_proj.weight ------- torch.Size([4096, 4096]) torch.int8
base_model.model.model.layers.7.self_attn.k_proj.lora_A.default.weight ------- torch.Size([128, 4096]) torch.bfloat16
base_model.model.model.layers.7.self_attn.k_proj.lora_B.default.weight ------- torch.Size([4096, 128]) torch.bfloat16
base_model.model.model.layers.7.self_attn.v_proj.weight ------- torch.Size([4096, 4096]) torch.int8
base_model.model.model.layers.7.self_attn.v_proj.lora_A.default.weight ------- torch.Size([128, 4096]) torch.bfloat16
base_model.model.model.layers.7.self_attn.v_proj.lora_B.default.weight ------- torch.Size([4096, 128]) torch.bfloat16
base_model.model.model.layers.7.self_attn.o_proj.weight ------- torch.Size([4096, 4096]) torch.int8
base_model.model.model.layers.7.self_attn.o_proj.lora_A.default.weight ------- torch.Size([128, 4096]) torch.bfloat16
base_model.model.model.layers.7.self_attn.o_proj.lora_B.default.weight ------- torch.Size([4096, 128]) torch.bfloat16

Does someone know why?

**Comment by attnmamba** [comment]
@mengjiexu How did you solve your problem?

**Comment by mengjiexu** [comment]
https://github.com/haotian-liu/LLaVA/issues/785#issuecomment-1805189303
