### ISSUE TITLE
[Usage] A path to the LoRA adapters isn't being handled properly

### ISSUE THREAD

**Issue by StrangeTcy** [haotian-liu/LLaVA#788]
### Describe the issue

Following the docs on LoRA models (https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md) we've run the following command:
```
python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path /root/raw_data_for_llava/raw_data_for_llava/LLaVAR/further_finetuning/lora --model-base meta-llama/Llama-2-7b-hf
```
and ran into the following error:
```
2023-11-10 13:00:47 | ERROR | stderr | 
2023-11-10 13:00:47 | INFO | stdout | Loading LoRA weights from /root/raw_data_for_llava/raw_data_for_llava/LLaVAR/further_finetuning/lora
2023-11-10 13:00:47 | ERROR | stderr | Traceback (most recent call last):
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/anaconda3/envs/llava/lib/python3.10/site-packages/peft/utils/config.py", line 177, in _get_peft_type
2023-11-10 13:00:47 | ERROR | stderr |     config_file = hf_hub_download(
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/anaconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub-0.19.0-py3.8.egg/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/anaconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub-0.19.0-py3.8.egg/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
2023-11-10 13:00:47 | ERROR | stderr | huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/root/raw_data_for_llava/raw_data_for_llava/LLaVAR/further_finetuning/lora'. Use `repo_type` argument if needed.
2023-11-10 13:00:47 | ERROR | stderr | 
2023-11-10 13:00:47 | ERROR | stderr | During handling of the above exception, another exception occurred:
2023-11-10 13:00:47 | ERROR | stderr | 
2023-11-10 13:00:47 | ERROR | stderr | Traceback (most recent call last):
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/anaconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-11-10 13:00:47 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/anaconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
2023-11-10 13:00:47 | ERROR | stderr |     exec(code, run_globals)
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/raw_data_for_llava/raw_data_for_llava/LLaVAR/LLaVA/llava/serve/model_worker.py", line 275, in <module>
2023-11-10 13:00:47 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/raw_data_for_llava/raw_data_for_llava/LLaVAR/LLaVA/llava/serve/model_worker.py", line 65, in __init__
2023-11-10 13:00:47 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/raw_data_for_llava/raw_data_for_llava/LLaVAR/LLaVA/llava/model/builder.py", line 115, in load_pretrained_model
2023-11-10 13:00:47 | ERROR | stderr |     model = PeftModel.from_pretrained(model, model_path)
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/anaconda3/envs/llava/lib/python3.10/site-packages/peft/peft_model.py", line 244, in from_pretrained
2023-11-10 13:00:47 | ERROR | stderr |     PeftConfig._get_peft_type(
2023-11-10 13:00:47 | ERROR | stderr |   File "/home/developer/anaconda3/envs/llava/lib/python3.10/site-packages/peft/utils/config.py", line 183, in _get_peft_type
2023-11-10 13:00:47 | ERROR | stderr |     raise ValueError(f"Can't find '{CONFIG_NAME}' at '{model_id}'")
2023-11-10 13:00:47 | ERROR | stderr | ValueError: Can't find 'adapter_config.json' at '/root/raw_data_for_llava/raw_data_for_llava/LLaVAR/further_finetuning/lora'
```

So apparently something is going wrong with parsing the path to the adapter; after reviewing https://github.com/huggingface/huggingface_hub/blob/18d0ae2ebfcfc696c50a67e7dad8fa63f5f23068/src/huggingface_hub/utils/_validators.py#L123 and further 
my guess is we're interpreting a `repo_type` as a `repo_id` or something similar.
Why might that be?

**Comment by sdip15fa** [comment]
did you solve the problem?
