### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by tensorboy** [haotian-liu/LLaVA#81]
With current transformers installed by (newest code in this repo):
```
pip uninstall transformers
pip install git+https://github.com/huggingface/transformers@cae78c46
```
my command:
```
python -m llava.serve.controller --host 0.0.0.0 --port 10000

python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path /media/tensorboy/4df39736-fd86-443e-b6fe-a6ae0fe28d72/llama-dl-main/LLaVA-7B-v0 --multi-modal --num-gpus 2

python -m llava.serve.gradio_web_server --controller http://localhost:10000 --share
```

logs:

```
2023-05-01 20:46:05 | ERROR | stderr | INFO:     Started server process [3502503]
2023-05-01 20:46:05 | ERROR | stderr | INFO:     Waiting for application startup.
2023-05-01 20:46:05 | ERROR | stderr | INFO:     Application startup complete.
2023-05-01 20:46:05 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:40000 (Press CTRL+C to quit)
2023-05-01 20:46:20 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:46:35 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:46:50 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:47:05 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:47:20 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:47:35 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:47:48 | INFO | stdout | INFO:     127.0.0.1:56932 - "POST /worker_get_status HTTP/1.1" 200 OK
2023-05-01 20:47:50 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:48:05 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:48:20 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: None. global_counter: 0
2023-05-01 20:48:25 | INFO | model_worker | Send heart beat. Models: ['LLaVA-7B-v0']. Semaphore: Semaphore(value=4, locked=False). global_counter: 1
2023-05-01 20:48:25 | INFO | stdout | INFO:     127.0.0.1:57470 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-05-01 20:48:27 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-05-01 20:48:27 | ERROR | stderr | Traceback (most recent call last):
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-05-01 20:48:27 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     raise exc
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     raise exc
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     raise e
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     await self.app(scope, receive, send)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-05-01 20:48:27 | ERROR | stderr |     await self.app(scope, receive, send)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
2023-05-01 20:48:27 | ERROR | stderr |     await response(scope, receive, send)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2023-05-01 20:48:27 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
2023-05-01 20:48:27 | ERROR | stderr |     raise exceptions[0]
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2023-05-01 20:48:27 | ERROR | stderr |     await func()
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
2023-05-01 20:48:27 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
2023-05-01 20:48:27 | ERROR | stderr |     yield await anyio.to_thread.run_sync(_next, iterator)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-05-01 20:48:27 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-05-01 20:48:27 | ERROR | stderr |     return await future
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-05-01 20:48:27 | ERROR | stderr |     result = context.run(func, *args)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/starlette/concurrency.py", line 53, in _next
2023-05-01 20:48:27 | ERROR | stderr |     return next(iterator)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/LLaVA/llava/serve/model_worker.py", line 292, in generate_stream_gate
2023-05-01 20:48:27 | ERROR | stderr |     for x in self.generate_stream(params):
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
2023-05-01 20:48:27 | ERROR | stderr |     response = gen.send(None)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/LLaVA/llava/serve/model_worker.py", line 239, in generate_stream
2023-05-01 20:48:27 | ERROR | stderr |     out = model(
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
2023-05-01 20:48:27 | ERROR | stderr |     return forward_call(*input, **kwargs)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-05-01 20:48:27 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/LLaVA/llava/model/llava.py", line 218, in forward
2023-05-01 20:48:27 | ERROR | stderr |     outputs = self.model(
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/anaconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
2023-05-01 20:48:27 | ERROR | stderr |     return forward_call(*input, **kwargs)
2023-05-01 20:48:27 | ERROR | stderr |   File "/home/tensorboy/LLaVA/llava/model/llava.py", line 159, in forward
2023-05-01 20:48:27 | ERROR | stderr |     cur_new_input_embeds = torch.cat((cur_input_embeds[:image_start_token_pos+1], cur_image_features, cur_input_embeds[image_start_token_pos + num_patches + 1:]), dim=0)
2023-05-01 20:48:27 | ERROR | stderr | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_cat)

```

relevant issues:
https://github.com/haotian-liu/LLaVA/issues/20
https://github.com/haotian-liu/LLaVA/issues/60

**Comment by haotian-liu** [comment]
Thanks for letting me know, this patch was not merged to the new training pipeline.  It should be fixed now :)
