### ISSUE TITLE
[Usage] 我在一个A100 80GB下进行全模型训练，告诉我显存不够

### ISSUE THREAD

**Issue by Williamsunsir** [haotian-liu/LLaVA#827]
### Describe the issue

Issue:

Command:
```
sh /notebooks/projects/git/LLaVA/scripts/v1_5/finetune_task.sh
```

Log: 
```
# sh /notebooks/projects/git/LLaVA/scripts/v1_5/finetune_task.sh
[2023-11-20 08:23:39,414] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-11-20 08:23:41.034618: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-20 08:23:41.071501: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-20 08:23:41.071534: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-20 08:23:41.072821: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-20 08:23:41.078730: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-20 08:23:41.820408: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2023-11-20 08:23:42,801] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-11-20 08:23:42,802] [INFO] [runner.py:555:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None /notebooks/projects/git/LLaVA/llava/train/train_mem.py --deepspeed /notebooks/projects/git/LLaVA/scripts/zero3.json --model_name_or_path /notebooks/Data/hf-models/llava/llava-v1.5-7b --version v1 --data_path /notebooks/Data/llava/train/llava_v1_5_mix2k.json --image_folder /notebooks/Data/llava/train --vision_tower /notebooks/Data/hf-models/clip/clip-vit-large-patch14-336 --mm_projector_type mlp2x_gelu --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --image_aspect_ratio pad --group_by_modality_length True --bf16 True --output_dir /notebooks/projects/git/LLaVA/checkpoints/llava-v1.5-7b-task --num_train_epochs 1 --per_device_train_batch_size 1 --per_device_eval_batch_size 4 --gradient_accumulation_steps 1 --evaluation_strategy no --save_strategy steps --save_steps 50000 --save_total_limit 1 --learning_rate 2e-5 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 1 --tf32 True --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to none
[2023-11-20 08:23:44,121] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-11-20 08:23:45.647684: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-20 08:23:45.684273: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-20 08:23:45.684298: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-20 08:23:45.685574: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-20 08:23:45.691474: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-20 08:23:46.418401: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2023-11-20 08:23:47,404] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.13.4-1
[2023-11-20 08:23:47,404] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.13.4-1
[2023-11-20 08:23:47,404] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2023-11-20 08:23:47,404] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2023-11-20 08:23:47,404] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7
[2023-11-20 08:23:47,404] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.13.4-1+cuda11.7
[2023-11-20 08:23:47,404] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.13.4-1
[2023-11-20 08:23:47,404] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-11-20 08:23:47,404] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-11-20 08:23:47,404] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-11-20 08:23:47,404] [INFO] [launch.py:163:main] dist_world_size=1
[2023-11-20 08:23:47,404] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-11-20 08:23:50,220] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-11-20 08:23:50.502602: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-20 08:23:50.539659: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-20 08:23:50.539684: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-20 08:23:50.540975: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-20 08:23:50.546813: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-20 08:23:51.348687: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2023-11-20 08:23:52,339] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-11-20 08:23:52,339] [INFO] [comm.py:594:init_distributed] cdb=None
[2023-11-20 08:23:52,339] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2023-11-20 08:23:53,315] [INFO] [partition_parameters.py:453:__exit__] finished initializing model with 6.76B parameters
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.86s/it]
[2023-11-20 08:24:06,582] [WARNING] [partition_parameters.py:836:_post_init_method] param `class_embedding` in CLIPVisionEmbeddings not on GPU so was not broadcasted from rank 0
[2023-11-20 08:24:06,769] [INFO] [partition_parameters.py:453:__exit__] finished initializing model with 7.06B parameters
Formatting inputs...Skip in lazy mode
Parameter Offload: Total persistent parameters: 599040 in 312 params
Traceback (most recent call last):
  File "/notebooks/projects/git/LLaVA/llava/train/train_mem.py", line 16, in <module>
    train()
  File "/notebooks/projects/git/LLaVA/llava/train/train.py", line 934, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1656, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1198, in prepare
    result = self._prepare_deepspeed(*args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1184, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1474, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage3.py", line 300, in __init__
    self._setup_for_real_optimizer()
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage3.py", line 382, in _setup_for_real_optimizer
    self.initialize_optimizer_states()
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage3.py", line 892, in initialize_optimizer_states
    self._optimizer_step(i)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage3.py", line 817, in _optimizer_step
    self.optimizer.step()
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/adamw.py", line 171, in step
    adamw(
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/adamw.py", line 321, in adamw
    func(
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/adamw.py", line 564, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.77 GiB (GPU 0; 79.15 GiB total capacity; 72.29 GiB already allocated; 2.91 GiB free; 75.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2023-11-20 08:24:22,443] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2442
[2023-11-20 08:24:22,444] [ERROR] [launch.py:321:sigkill_handler] ['/usr/bin/python3', '-u', '/notebooks/projects/git/LLaVA/llava/train/train_mem.py', '--local_rank=0', '--deepspeed', '/notebooks/projects/git/LLaVA/scripts/zero3.json', '--model_name_or_path', '/notebooks/Data/hf-models/llava/llava-v1.5-7b', '--version', 'v1', '--data_path', '/notebooks/Data/llava/train/llava_v1_5_mix2k.json', '--image_folder', '/notebooks/Data/llava/train', '--vision_tower', '/notebooks/Data/hf-models/clip/clip-vit-large-patch14-336', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'True', '--bf16', 'True', '--output_dir', '/notebooks/projects/git/LLaVA/checkpoints/llava-v1.5-7b-task', '--num_train_epochs', '1', '--per_device_train_batch_size', '1', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '50000', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'none'] exits with return code = 1
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by Williamsunsir** [comment]
> change finetune config to zero3_offload and reduce batch_size and increase gradient_accumulation_steps, i use this method and finialy run 7b finetune by using 50GB vram

非常感谢地你的建议，我通过使用zero3_offload.json 的配置，并且调大gradient_accumulation_steps 参数，但是我的系统内存在持续增长，并且很快占满，我该如何进行处理这个情况呢

![微信截图_20231122110710](https://github.com/haotian-liu/LLaVA/assets/48049042/f24d032c-4c2e-4b30-aa0f-bd493ef743de)

**Comment by Linziyang1999** [comment]
yes it take a lot of ram, the workset memory is 232~252GiB during training

**Comment by Williamsunsir** [comment]
> yes it take a lot of ram, the workset memory is 232~252GiB during training

刚刚服务器卡死了，这么大的内存加载或许对我有些吃力，有没有其他的方式方法呢

**Comment by Linziyang1999** [comment]
https://huggingface.co/docs/transformers/v4.15.0/main_classes/deepspeed
check this，you can reduce stage3_max_live_parameters: 1e9    stage3_max_reuse_distance: 1e9 
i see below in huggingface deepspeed, hope this can help you ^^
If you are getting OOMs, because your model or activations don’t fit into the GPU memory and you have unutilized CPU memory offloading the optimizer states and parameters to CPU memory with "device": "cpu" may solve this limitation. If you don’t want to offload to CPU memory, use none instead of cpu for the device entry. Offloading to NVMe is discussed further down.

Pinned memory is enabled with pin_memory set to true. This feature can improve the throughput at the cost of making less memory available to other processes. Pinned memory is set aside to the specific process that requested it and its typically accessed much faster than normal CPU memory.

**Comment by 459737087** [comment]
when I use zero3_offload.json it reported wrong

```
[2024-01-12 06:48:37,198] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1201
[2024-01-12 06:48:37,199] [ERROR] [launch.py:321:sigkill_handler] ['/usr/local/bin/python', '-u', 'llava/train/train.py', '--local_rank=0', '--deepspeed', './scripts/zero3_offload.json', '--model_name_or_path', '/output/LLaVA-vicuna-7b', '--version', 'v1', '--data_path', './data/blip_laion_cc_sbu_558k.json', '--image_folder', '/input4/', '--vision_tower', 'openai/clip-vit-large-patch14', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--bf16', 'True', '--output_dir', './checkpoints/llava-LLaVA-vicuna-7b-finetune', '--num_train_epochs', '1', '--per_device_train_batch_size', '2', '--per_device_eval_batch_size', '2', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '100', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = -9
```

**Comment by Linziyang1999** [comment]
> when I use zero3_offload.json it reported wrong
> 
> ```
> [2024-01-12 06:48:37,198] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1201
> [2024-01-12 06:48:37,199] [ERROR] [launch.py:321:sigkill_handler] ['/usr/local/bin/python', '-u', 'llava/train/train.py', '--local_rank=0', '--deepspeed', './scripts/zero3_offload.json', '--model_name_or_path', '/output/LLaVA-vicuna-7b', '--version', 'v1', '--data_path', './data/blip_laion_cc_sbu_558k.json', '--image_folder', '/input4/', '--vision_tower', 'openai/clip-vit-large-patch14', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--bf16', 'True', '--output_dir', './checkpoints/llava-LLaVA-vicuna-7b-finetune', '--num_train_epochs', '1', '--per_device_train_batch_size', '2', '--per_device_eval_batch_size', '2', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '100', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = -9
> ```

It's out of memory , return code = -9 mean your vram/ram not enough

**Comment by yqy2001** [comment]
一个人用中文一个人用英文在这一问一答真的太搞笑了哈哈哈

It's really funny when one person uses Chinese and the other uses English to conduct conversations round after round. Hahaha

“有没有其他的方式方法呢” -> "check this, you can reduce ....." -> "好的，感谢"

**Comment by Jeremy-lf** [comment]
> > when I use zero3_offload.json it reported wrong
> > ```
> > [2024-01-12 06:48:37,198] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1201
> > [2024-01-12 06:48:37,199] [ERROR] [launch.py:321:sigkill_handler] ['/usr/local/bin/python', '-u', 'llava/train/train.py', '--local_rank=0', '--deepspeed', './scripts/zero3_offload.json', '--model_name_or_path', '/output/LLaVA-vicuna-7b', '--version', 'v1', '--data_path', './data/blip_laion_cc_sbu_558k.json', '--image_folder', '/input4/', '--vision_tower', 'openai/clip-vit-large-patch14', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--bf16', 'True', '--output_dir', './checkpoints/llava-LLaVA-vicuna-7b-finetune', '--num_train_epochs', '1', '--per_device_train_batch_size', '2', '--per_device_eval_batch_size', '2', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '100', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb'] exits with return code = -9
> > ```
> 
> It's out of memory , return code = -9 mean your vram/ram not enough

![image](https://github.com/haotian-liu/LLaVA/assets/45171399/c1d82885-fc76-47ae-a6d9-65bd671c63a7)
When i train pretraining, it encounter a error with return code = -8, how to solve it?  Thank you very much!!!!!

**Comment by ThisisBillhe** [comment]
same OOM problem here when finetuning 7B models on a single A100-80G. The error log is exactly the same as @Williamsunsir . Theoretically, finetuning a 7B model takes 14G (model weights) + 28G (adam) VRAM under BF16. I wonder why using deepspeed lead to OOM? Is there any additional VRAM cost?

> change finetune config to zero3_offload and reduce batch_size and increase gradient_accumulation_steps, i use this method and finialy run 7b finetune by using 50GB vram

**Comment by feiyangsuo** [comment]
> same OOM problem here when finetuning 7B models on a single A100-80G. The error log is exactly the same as @Williamsunsir . Theoretically, finetuning a 7B model takes 14G (model weights) + 28G (adam) VRAM under BF16. I wonder why using deepspeed lead to OOM? Is there any additional VRAM cost?
> 
> > change finetune config to zero3_offload and reduce batch_size and increase gradient_accumulation_steps, i use this method and finialy run 7b finetune by using 50GB vram

Facing OOM issue too currently. Guess is that in fact it's not GPU OOM but CPU OOM. I'm using 1 A100-80G. If I use zero3.json the training will sometimes raise OOM. However once switched to zero3_offload.json, the training raises OOM every time just after started.
Last time I changed `stage3_max_live_parameters` and `stage3_max_reuse_distance` in zero3.json from default 1e9 to 5e8 and the training is done with no error
