### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by ThugJudy** [haotian-liu/LLaVA#890]
## How do I use the finetuned Model in CLI interactive mode?

I have finetuned the model using the following Script: 
```
#!/bin/bash

deepspeed llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-v1.5-13b \
    --version v1 \
    --data_path /projects/bbpr/psg4/llm/bargraph_data.json \
    --image_folder /dataset/imgs \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-13b-task-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

it fine-tuned model is generated successfully, but, when I try to use it using the following command to open an interactive mode with my model:

```
python -m llava.serve.cli --model-path ./checkpoints/llava-v1.5-13b-task-lora --image-file /projects/bbpr/psg4/llm/LLaVA/dataset/imgs/000000.png --load-4bit --model-base liuhaotian/llava-v1.5-13b
```

I get the following error:

```
[2023-12-03 15:33:18,196] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 749/749 [00:00<00:00, 4.18MB/s]
tokenizer.model: 100%|████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 34.1MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████| 438/438 [00:00<00:00, 2.90MB/s]
Loading LLaVA from base model...
pytorch_model.bin.index.json: 100%|██████████████████████████████████████████████████████████████████████████| 33.7k/33.7k [00:00<00:00, 248MB/s]
pytorch_model-00001-of-00003.bin: 100%|██████████████████████████████████████████████████████████████████████| 9.95G/9.95G [00:45<00:00, 218MB/s]
pytorch_model-00002-of-00003.bin: 100%|█████████████████████████████████████████████████████████████████████| 9.90G/9.90G [02:36<00:00, 63.2MB/s]
pytorch_model-00003-of-00003.bin: 100%|██████████████████████████████████████████████████████████████████████| 6.24G/6.24G [00:27<00:00, 228MB/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 3/3 [03:49<00:00, 76.67s/it]
config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 4.76k/4.76k [00:00<00:00, 27.4MB/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.30s/it]
generation_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 154/154 [00:00<00:00, 954kB/s]
Loading additional LLaVA weights...
Traceback (most recent call last):
  File "/u/psg4/.conda/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u/psg4/.conda/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/projects/bbpr/psg4/llm/LLaVA/llava/serve/cli.py", line 124, in <module>
    main(args)
  File "/projects/bbpr/psg4/llm/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/projects/bbpr/psg4/llm/LLaVA/llava/model/builder.py", line 75, in load_pretrained_model
    model.load_state_dict(non_lora_trainables, strict=False)
  File "/u/psg4/.conda/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlavaLlamaForCausalLM:
        size mismatch for model.mm_projector.0.weight: copying a param with shape torch.Size([5120, 1024]) from checkpoint, the shape in current model is torch.Size([2621440, 1]).
        size mismatch for model.mm_projector.2.weight: copying a param with shape torch.Size([5120, 5120]) from checkpoint, the shape in current model is torch.Size([13107200, 1]).
```

Not sure if I'm doing something wrong. Kindly guide me.

**Comment by haotian-liu** [comment]
Hi, `--load-4bit` is not currently compatible with LoRA. You can either remove this option, or first [create merged checkpoint](https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#create-merged-checkpoints) and then load it with 4-bit.
