### ISSUE TITLE
Issue: Can not download pretrain dataset

### ISSUE THREAD

**Issue by yummyKnight** [haotian-liu/LLaVA#912]
### Describe the issue

Issue:
I am trying download LAION-CC-SBU from HF using command:
Command:
```
from datasets import load_dataset
dataset = load_dataset("liuhaotian/LLaVA-Pretrain")
```
But after cache are downloaded i got error: 
Log: 
```
Traceback (most recent call last):
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/builder.py", line 1932, in _prepare_split_single
    writer.write_table(table)
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/arrow_writer.py", line 573, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/table.py", line 2332, in table_cast
    return cast_table_to_schema(table, schema)
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/table.py", line 2290, in cast_table_to_schema
    raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast
id: string
url: string
image: string
blip_caption: string
to
{'id': Value(dtype='string', id=None), 'conversations': [{'from': Value(dtype='string', id=None), 'value': Value(dtype='string', id=None)}], 'image': Value(dtype='string', id=None)}
because column names don't match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jovyan/LLaVA/download_ds.py", line 11, in <module>
    dataset = load_dataset("liuhaotian/LLaVA-Pretrain")
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/load.py", line 2152, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/builder.py", line 948, in download_and_prepare
    self._download_and_prepare(
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/builder.py", line 1043, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/builder.py", line 1805, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/home/user/conda/envs/llava/lib/python3.10/site-packages/datasets/builder.py", line 1950, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
```
Version of datasets==2.15.0 
Have somebody experienced same problem?

**Comment by jkli1998** [comment]
I have encountered the same problem. May I ask how you solved it?

**Comment by yummyKnight** [comment]
@jkli1998 same as here (#1139)
