### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'skip_next'[Usage] 

### ISSUE THREAD

**Issue by kimimorgam** [haotian-liu/LLaVA#915]
### Describe the issue

Issue: AttributeError: 'NoneType' object has no attribute 'skip_next'

Command:
python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload

Log: 
2023-12-12 02:27:46 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=10, model_list_mode='reload', share=False, moderate=False, embed=False)
2023-12-12 02:27:50 | INFO | gradio_web_server | Models: []
2023-12-12 02:27:50 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=10, model_list_mode='reload', share=False, moderate=False, embed=False)
2023-12-12 02:27:55 | INFO | stdout | Running on local URL:  http://0.0.0.0:7860
2023-12-12 02:27:55 | INFO | stdout |
2023-12-12 02:27:55 | INFO | stdout | To create a public link, set `share=True` in `launch()`.
2023-12-12 02:28:25 | INFO | gradio_web_server | load_demo. ip: 127.0.0.1
2023-12-12 02:28:27 | INFO | gradio_web_server | add_text. ip: 127.0.0.1. len: 33
2023-12-12 02:28:27 | ERROR | stderr | Traceback (most recent call last):
2023-12-12 02:28:27 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\routes.py", line 437, in run_predict
2023-12-12 02:28:27 | ERROR | stderr |     output = await app.get_blocks().process_api(
2023-12-12 02:28:27 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:27 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\blocks.py", line 1352, in process_api
2023-12-12 02:28:27 | ERROR | stderr |     result = await self.call_function(
2023-12-12 02:28:27 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:27 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\blocks.py", line 1077, in call_function
2023-12-12 02:28:27 | ERROR | stderr |     prediction = await anyio.to_thread.run_sync(
2023-12-12 02:28:27 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:27 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
2023-12-12 02:28:27 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-12-12 02:28:27 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:27 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
2023-12-12 02:28:27 | ERROR | stderr |     return await future
2023-12-12 02:28:27 | ERROR | stderr |            ^^^^^^^^^^^^
2023-12-12 02:28:27 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
2023-12-12 02:28:27 | ERROR | stderr |     result = context.run(func, *args)
2023-12-12 02:28:27 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:27 | ERROR | stderr |   File "C:\gpt4\LLaVA\llava\serve\gradio_web_server.py", line 148, in add_text
2023-12-12 02:28:27 | ERROR | stderr |     if len(state.get_images(return_pil=True)) > 0:
2023-12-12 02:28:27 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2023-12-12 02:28:27 | ERROR | stderr | AttributeError: 'NoneType' object has no attribute 'get_images'
2023-12-12 02:28:28 | INFO | gradio_web_server | http_bot. ip: 127.0.0.1
2023-12-12 02:28:28 | ERROR | stderr | Traceback (most recent call last):
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\routes.py", line 437, in run_predict
2023-12-12 02:28:28 | ERROR | stderr |     output = await app.get_blocks().process_api(
2023-12-12 02:28:28 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\blocks.py", line 1352, in process_api
2023-12-12 02:28:28 | ERROR | stderr |     result = await self.call_function(
2023-12-12 02:28:28 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\blocks.py", line 1093, in call_function
2023-12-12 02:28:28 | ERROR | stderr |     prediction = await utils.async_iteration(iterator)
2023-12-12 02:28:28 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\utils.py", line 341, in async_iteration
2023-12-12 02:28:28 | ERROR | stderr |     return await iterator.__anext__()
2023-12-12 02:28:28 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\utils.py", line 334, in __anext__
2023-12-12 02:28:28 | ERROR | stderr |     return await anyio.to_thread.run_sync(
2023-12-12 02:28:28 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
2023-12-12 02:28:28 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-12-12 02:28:28 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
2023-12-12 02:28:28 | ERROR | stderr |     return await future
2023-12-12 02:28:28 | ERROR | stderr |            ^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
2023-12-12 02:28:28 | ERROR | stderr |     result = context.run(func, *args)
2023-12-12 02:28:28 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\Users\kimim\miniconda3\Lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
2023-12-12 02:28:28 | ERROR | stderr |     return next(iterator)
2023-12-12 02:28:28 | ERROR | stderr |            ^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr |   File "C:\gpt4\LLaVA\llava\serve\gradio_web_server.py", line 161, in http_bot
2023-12-12 02:28:28 | ERROR | stderr |     if state.skip_next:
2023-12-12 02:28:28 | ERROR | stderr |        ^^^^^^^^^^^^^^^
2023-12-12 02:28:28 | ERROR | stderr | AttributeError: 'NoneType' object has no attribute 'skip_next'
2023-12-12 02:28:31 | INFO | gradio_web_server | Models: ['llava-v1.5-13b']

Screenshots:

![image](https://github.com/haotian-liu/LLaVA/assets/140536250/d1dc51fc-c490-434c-b251-242b51bdc3fd)

After installed, running things, when test "what is a unusual..." this happens

![image](https://github.com/haotian-liu/LLaVA/assets/140536250/1a6ac959-2ac9-4f24-b08b-b745682833ab)

**Comment by kimimorgam** [comment]
![image](https://github.com/haotian-liu/LLaVA/assets/140536250/76e10344-6d31-4394-8eb2-14246c86bd5d)

And it, too :/

**Comment by learnerljh** [comment]
I met the same error. Has anyone fixed it?

**Comment by HarvestHan** [comment]
pip install gradio==4.16.0
