### ISSUE TITLE
[Question] RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

### ISSUE THREAD

**Issue by 1106280506Hx** [haotian-liu/LLaVA#938]
### Question

2023-12-21 20:51 Traceback (most recent call last):
2023-12-21 20:51   File "/gemini/code/llava_batch0.py", line 97, in <module>
2023-12-21 20:51     process_images_new(url[i])
2023-12-21 20:51   File "/gemini/code/llava_batch0.py", line 78, in process_images_new
2023-12-21 20:51     sentences=VQA_batch(image_path)
2023-12-21 20:51   File "/gemini/code/llava_batch0.py", line 32, in VQA_batch
2023-12-21 20:51     output = model.generate(**inputs, max_new_tokens=200).to("cuda")
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-12-21 20:51     return func(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/transformers/generation/utils.py", line 1718, in generate
2023-12-21 20:51     return self.greedy_search(
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/transformers/generation/utils.py", line 2579, in greedy_search
2023-12-21 20:51     outputs = self(
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-12-21 20:51     return forward_call(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-12-21 20:51     output = module._old_forward(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/transformers/models/llava/modeling_llava.py", line 433, in forward
2023-12-21 20:51     outputs = self.language_model(
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-12-21 20:51     return forward_call(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-12-21 20:51     output = module._old_forward(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1174, in forward
2023-12-21 20:51     outputs = self.model(
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-12-21 20:51     return forward_call(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-12-21 20:51     output = module._old_forward(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1061, in forward
2023-12-21 20:51     layer_outputs = decoder_layer(
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-12-21 20:51     return forward_call(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-12-21 20:51     output = module._old_forward(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 789, in forward
2023-12-21 20:51     hidden_states, self_attn_weights, present_key_value = self.self_attn(
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-12-21 20:51     return forward_call(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-12-21 20:51     output = module._old_forward(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 386, in forward
2023-12-21 20:51     query_states = self.q_proj(hidden_states)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-12-21 20:51     return forward_call(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-12-21 20:51     output = module._old_forward(*args, **kwargs)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/nn/modules.py", line 256, in forward
2023-12-21 20:51     out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 577, in matmul_4bit
2023-12-21 20:51     return MatMul4Bit.apply(A, B, out, bias, quant_state)
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
2023-12-21 20:51     return super().apply(*args, **kwargs)  # type: ignore[misc]
2023-12-21 20:51   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 516, in forward
2023-12-21 20:51     output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)
2023-12-21 20:51 RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`              When I was reasoning, I ran into this problem

**Comment by xmy0916** [comment]
https://github.com/pytorch/pytorch/issues/56747, I have encountered the same error during inference phase. maybe is the bug of pytorch. maybe upgrade your cuda, cudnn, pytorch version will help.

**Comment by lucasjinreal** [comment]
Same error but not in llava, so eried.
