### ISSUE TITLE
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

### ISSUE THREAD

**Issue by kirayomato** [haotian-liu/LLaVA#957]
### Describe the issue

Issue: Webui always shows **NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE**.

I have tried CLI Inference, and it can work successfully.
Command:
```
python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1.5-7b
```
Usually the console will just show **Caught Unknown Error**,
![2023123014_2616_RayLink_hU65](https://github.com/haotian-liu/LLaVA/assets/38139345/179c28e7-52ff-4cf3-8576-fd8f93e6365c)

but occasionally the error will like this

Log: 
```
2023-12-30 14:28:22 | ERROR | stderr | Exception in thread Thread-6 (generate):
2023-12-30 14:28:22 | ERROR | stderr | Traceback (most recent call last):
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\threading.py", line 1016, in _bootstrap_inner
2023-12-30 14:28:22 | ERROR | stderr |     self.run()
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\threading.py", line 953, in run
2023-12-30 14:28:22 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
2023-12-30 14:28:22 | ERROR | stderr |     return func(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\transformers\generation\utils.py", line 1588, in generate
2023-12-30 14:28:22 | ERROR | stderr |     return self.sample(
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\transformers\generation\utils.py", line 2642, in sample
2023-12-30 14:28:22 | ERROR | stderr |     outputs = self(
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
2023-12-30 14:28:22 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
2023-12-30 14:28:22 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "D:\Program\VLM\LLaVA\llava\model\language_model\llava_llama.py", line 88, in forward
2023-12-30 14:28:22 | ERROR | stderr |     return super().forward(
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\transformers\models\llama\modeling_llama.py", line 806, in forward
2023-12-30 14:28:22 | ERROR | stderr |     outputs = self.model(
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
2023-12-30 14:28:22 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\transformers\models\llama\modeling_llama.py", line 693, in forward
2023-12-30 14:28:22 | ERROR | stderr |     layer_outputs = decoder_layer(
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
2023-12-30 14:28:22 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
2023-12-30 14:28:22 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\transformers\models\llama\modeling_llama.py", line 405, in forward
2023-12-30 14:28:22 | ERROR | stderr |     hidden_states = self.input_layernorm(hidden_states)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
2023-12-30 14:28:22 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
2023-12-30 14:28:22 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\transformers\models\llama\modeling_llama.py", line 89, in forward
2023-12-30 14:28:22 | ERROR | stderr |     return self.weight * hidden_states.to(input_dtype)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\_prims_common\wrappers.py", line 220, in _fn
2023-12-30 14:28:22 | ERROR | stderr |     result = fn(*args, **kwargs)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\_prims_common\wrappers.py", line 130, in _fn
2023-12-30 14:28:22 | ERROR | stderr |     result = fn(**bound.arguments)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\_refs\__init__.py", line 926, in _ref
2023-12-30 14:28:22 | ERROR | stderr |     return prim(a, b)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\_refs\__init__.py", line 1532, in mul
2023-12-30 14:28:22 | ERROR | stderr |     return prims.mul(a, b)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\_ops.py", line 287, in __call__
2023-12-30 14:28:22 | ERROR | stderr |     return self._op(*args, **kwargs or {})
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\_prims\__init__.py", line 346, in _elementwise_meta
2023-12-30 14:28:22 | ERROR | stderr |     utils.check_same_device(*args_, allow_cpu_scalar_tensors=True)
2023-12-30 14:28:22 | ERROR | stderr |   File "C:\Software\Miniconda\envs\llava\lib\site-packages\torch\_prims_common\__init__.py", line 596, in check_same_device
2023-12-30 14:28:22 | ERROR | stderr |     raise RuntimeError(msg)
2023-12-30 14:28:22 | ERROR | stderr | RuntimeError: Tensor on device cuda:0 is not on the expected device meta!
2023-12-30 14:28:28 | INFO | stdout | Caught Unknown Error
```

**Comment by phong-diagon1** [comment]
Me too, waiting for solution
