### ISSUE TITLE
[Usage]  v1.5 LoRA /  scripts/merge_lora_weights.py `ValueError: MPTForCausalLM only supports tied word embeddings` 

### ISSUE THREAD

**Issue by z3ugma** [haotian-liu/LLaVA#962]
### Describe the issue

Issue:

after doing a finetune on v1.5 per the docs and then calling the `merge_lora_weights.py` script, the resulting merged model throws the error `ValueError: MPTForCausalLM only supports tied word embeddings` 

Command:
 python scripts/merge_lora_weights.py --model-base liuhaotian/llava-v1.5-13b --model-path ./checkpoints/llava-v1.5-13b-task-lora-/ --save-model-path ~/prompts_llava1.5
```

Log: 
```
root@C.8074266:~$ python -m llava.serve.cli --model-path ~/civitai_prompts_llava1.5/ --image-file ~/images/2cc612d6-818c-4927-b9f9-cc54ddb00220.png
[2024-01-02 04:49:05,746] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You are using a model of type llava to instantiate a model of type llava_mpt. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/LLaVA/llava/serve/cli.py", line 124, in <module>
    main(args)
  File "/root/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/root/LLaVA/llava/model/builder.py", line 103, in load_pretrained_model
    model = LlavaMPTForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/LLaVA/llava/model/language_model/llava_mpt.py", line 53, in __init__
    raise ValueError('MPTForCausalLM only supports tied word embeddings')
ValueError: MPTForCausalLM only supports tied word embeddings
```

**Comment by haotian-liu** [comment]
This was due to the way we identify model version using file path, pro**mpt**s makes it think it is MPT..

We are working on a more robust implementation now, but for now, please avoid including "mpt" in your file path.
