### ISSUE TITLE
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: ./scripts/zero2.json

### ISSUE THREAD

**Issue by 459737087** [haotian-liu/LLaVA#979]
### Describe the issue

Issue:
```
[2024-01-09 05:12:39,036] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
  File "/usr/local/lib/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../llava/train/train_mem.py", line 13, in <module>
    train()
  File "/output/LLaVA/llava/train/train.py", line 761, in train
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/usr/local/lib/python3.8/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 127, in __init__
  File "/usr/local/lib/python3.8/site-packages/transformers/training_args.py", line 1607, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/usr/local/lib/python3.8/site-packages/transformers/deepspeed.py", line 76, in __init__
    super().__init__(config_file_or_dict)
  File "/usr/local/lib/python3.8/site-packages/transformers/deepspeed.py", line 66, in __init__
    super().__init__(config_file_or_dict)
  File "/usr/local/lib/python3.8/site-packages/accelerate/utils/deepspeed.py", line 55, in __init__
    raise ValueError(
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: ./scripts/zero2.json
```
Command:
```
sh finetune_lora.sh
```

Log: 
```
PROMPT_VERSION="llava_llama_2"
MODEL_VERSION="llama-2-7b-chat"
################## LLaMA-2 ##################

deepspeed ../llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --lora_enable True \
    --model_name_or_path /input1/ \
    --version $PROMPT_VERSION \
    --data_path ./playground/data/llava_instruct_80k.json \
    --image_folder /path/to/coco/train2017 \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter ./checkpoints/llava-$MODEL_VERSION-pretrain/mm_projector.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-$MODEL_VERSION-finetune_lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --dataloader_num_workers 4 \
    --report_to wandb

```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by 459737087** [comment]
change the model_path name.
