### ISSUE TITLE
[Usage] can‘t run gradio_web_server.py

### ISSUE THREAD

**Issue by J-e-l-l-y-Z** [haotian-liu/LLaVA#986]
### Describe the issue

Issue: I can't run the gradio_web_server.py to reach the gradio interface, while the controller is working normally

Command:
```
# in the first terminal
cd LLaVA
conda activate llava
python -m llava.serve.controller --host 0.0.0.0 --port 10000
```

Log: 
```
2024-01-12 16:06:25 | INFO | controller | args: Namespace(host='0.0.0.0', port=10000, dispatch_method='shortest_queue')
2024-01-12 16:06:25 | INFO | controller | Init controller
2024-01-12 16:06:25 | ERROR | stderr | INFO:     Started server process [2696939]
2024-01-12 16:06:25 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-12 16:06:25 | ERROR | stderr | INFO:     Application startup complete.
2024-01-12 16:06:25 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:10000 (Press CTRL+C to quit)
```

Command:
```
# in the second terminal
cd LLaVA
conda activate llava
python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload

```

Log: 
```
2024-01-12 16:24:21 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=10, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-01-12 16:24:22 | ERROR | stderr | Traceback (most recent call last):
2024-01-12 16:24:22 | ERROR | stderr |   File "/home/rix2usr2/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-01-12 16:24:22 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-01-12 16:24:22 | ERROR | stderr |   File "/home/rix2usr2/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
2024-01-12 16:24:22 | ERROR | stderr |     exec(code, run_globals)
2024-01-12 16:24:22 | ERROR | stderr |   File "/home/rix2usr2/LLaVA/llava/serve/gradio_web_server.py", line 459, in <module>
2024-01-12 16:24:22 | ERROR | stderr |     models = get_model_list()
2024-01-12 16:24:22 | ERROR | stderr |   File "/home/rix2usr2/LLaVA/llava/serve/gradio_web_server.py", line 40, in get_model_list
2024-01-12 16:24:22 | ERROR | stderr |     assert ret.status_code == 200
2024-01-12 16:24:22 | ERROR | stderr | AssertionError
```

**Comment by J-e-l-l-y-Z** [comment]
占楼

**Comment by yangyangtaizi** [comment]
me too……

**Comment by anonymousz97** [comment]
I believe you should specify port larger than 8000 for that, current ones is 7860. Mine solved by using port 8006. See line 468 in server/gradio_web_server.py

**Comment by J-e-l-l-y-Z** [comment]
> I believe you should specify port larger than 8000 for that, current ones is 7860. Mine solved by using port 8006. See line 468 in server/gradio_web_server.py
just like python -m llava.serve.controller --host 0.0.0.0 --port 8006;  python -m llava.serve.gradio_web_server --controller http://localhost:8006 --model-list-mode reload --port 8007?
I tried it but it doesn't work.

**Comment by anonymousz97** [comment]
you run it from local or from docker? how about proxy? or try lsof -i -P -n | grep LISTEN to check if all the port is working?

**Comment by 1429904852** [comment]
how to fix this problem? i have the same question

**Comment by YuyaOkazakiaaa** [comment]
me too.

**Comment by 459737087** [comment]
Hey! Did you solve it @1429904852

**Comment by 1429904852** [comment]
> Hey! Did you solve it @1429904852

Not yet

**Comment by 1429904852** [comment]
Hi, all, I have solved this problem. Before executing the demo command, please run the following three lines of code:

export http_proxy=
export https_proxy=
export all_proxy=

**Comment by 459737087** [comment]
Hi ! I know, you close the proxy,you can succeed. Thank you !

**Comment by NamHuynh1308** [comment]
> Hi, all, I have solved this problem. Before executing the demo command, please run the following three lines of code:
> 
> export http_proxy= export https_proxy= export all_proxy=

hey did you run both controller and gadio at the same time? Thanks

**Comment by g-makerr** [comment]
just check your proxy and unset them
`unset http_proxy`
`unset https_proxy`
